/* 自动生成 —— 不要手改这个文件！
   事实源：tools/build_fn_cards.py（卡片文字 + 示例代码）
   这里是它真跑一遍之后的输出，每张卡带 ok / out 两个字段。
   重跑：python tools/build_fn_cards.py */
window.LAB_FN_CARDS = [
 {
  "id": "sql.skeleton",
  "lang": "sql",
  "cat": "SQL",
  "stage": "现在",
  "name": "SELECT … FROM …",
  "brief": "所有查询的骨架：先说「要哪几列」，再说「从哪张表」",
  "code": "SELECT name, class FROM students;",
  "where": "第3课① · 任何一条 SQL 都长这样",
  "gotcha": "`SELECT *` 能跑但别常用 —— 列的顺序以后会变，代码会悄悄错位",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "name | class  \n-----+--------\n韩立 | 讯飞班 \n小明 | 讯飞班 \n小红 | 计科1班\n小刚 | 计科1班\n小美 | 计科1班\n（5 行）",
  "ok": true
 },
 {
  "id": "sql.where",
  "lang": "sql",
  "cat": "SQL",
  "stage": "现在",
  "name": "WHERE",
  "brief": "先在脑子里选出全部，再一条条筛掉不要的",
  "code": "SELECT name, class FROM students WHERE class = '讯飞班';",
  "where": "第3课 · 筛选；D8 作业至少要用一次",
  "gotcha": "筛完只剩 2 行不是因为「表里只有 2 行」，是 WHERE 把它们筛掉了",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "name | class \n-----+-------\n韩立 | 讯飞班\n小明 | 讯飞班\n（2 行）",
  "ok": true
 },
 {
  "id": "sql.on_vs_where",
  "lang": "sql",
  "cat": "SQL",
  "stage": "现在",
  "name": "ON / WHERE 分工",
  "brief": "ON = 怎么配对（横着拼），WHERE = 要哪些（竖着筛）",
  "code": "SELECT s.name, e.cid\nFROM students s\nJOIN enrollments e ON s.id = e.sid\nWHERE e.cid = 1;",
  "where": "第3课④ · 全课最该分清的一对",
  "gotcha": "把 `e.cid = 1` 挪到 ON 里，INNER JOIN 结果一样 —— 但换成 LEFT JOIN 就天差地别（留在 ON 里 = 右表筛完再拼，放 WHERE 里 = 拼完再筛，会把 NULL 行筛掉）",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "name | cid\n-----+----\n韩立 | 1  \n小明 | 1  \n（2 行）",
  "ok": true
 },
 {
  "id": "sql.order_by",
  "lang": "sql",
  "cat": "SQL",
  "stage": "近期",
  "name": "ORDER BY",
  "brief": "排序；默认升序，DESC 反过来",
  "code": "SELECT s.name, e.grade\nFROM enrollments e JOIN students s ON s.id = e.sid\nORDER BY e.grade DESC;",
  "where": "出榜单 / 看最大的那个",
  "gotcha": "NULL 在 SQLite 里排在最前（DESC 时排最后）—— 想让它垫底要写 `ORDER BY grade IS NULL, grade DESC`",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "name | grade\n-----+------\n小明 | 92.0 \n韩立 | 88.5 \n小明 | 81.0 \n韩立 | 76.0 \n小红 | 59.0 \n小刚 | NULL \n（6 行）",
  "ok": true
 },
 {
  "id": "sql.limit",
  "lang": "sql",
  "cat": "SQL",
  "stage": "近期",
  "name": "LIMIT / OFFSET",
  "brief": "只要前 N 条 / 跳过前 N 条（分页就靠它）",
  "code": "SELECT name, credit FROM courses ORDER BY credit DESC LIMIT 2;",
  "where": "Top-N 排行榜；翻页",
  "gotcha": "`LIMIT` 没有 `ORDER BY` 时顺序是**未定义**的 —— 每次跑可能不一样",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "name   | credit\n-------+-------\n高数   | 5     \n数据库 | 3     \n（2 行）",
  "ok": true
 },
 {
  "id": "sql.distinct",
  "lang": "sql",
  "cat": "SQL",
  "stage": "近期",
  "name": "DISTINCT",
  "brief": "一行里多个列都相同才算重复，去重后只剩一种",
  "code": "SELECT DISTINCT class FROM students;",
  "where": "「有几种」而不是「有几条」",
  "gotcha": "`COUNT(DISTINCT 列)` 才是「数几种」；`COUNT(*)` 数的是行数",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "class  \n-------\n讯飞班 \n计科1班\n（2 行）",
  "ok": true
 },
 {
  "id": "sql.and_or",
  "lang": "sql",
  "cat": "SQL",
  "stage": "近期",
  "name": "AND / OR 的优先级",
  "brief": "AND 比 OR 先算 —— 所以 OR 两边一定要加括号",
  "code": "SELECT name, class FROM students\nWHERE (class = '讯飞班' OR class = '计科1班') AND name <> '小红';",
  "where": "多条件筛选",
  "gotcha": "不加括号会变成「讯飞班的人，或者（计科1班且不叫小红的人）」—— 结果多出来的人你还不一定看得出来",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "name | class  \n-----+--------\n韩立 | 讯飞班 \n小明 | 讯飞班 \n小刚 | 计科1班\n小美 | 计科1班\n（4 行）",
  "ok": true
 },
 {
  "id": "sql.in",
  "lang": "sql",
  "cat": "SQL",
  "stage": "近期",
  "name": "IN",
  "brief": "一个字段对一串值，比写一堆 OR 干净",
  "code": "SELECT name FROM students WHERE class IN ('讯飞班', '计科1班');",
  "where": "按一批 id 批量查（爬虫/接口返回的 id 列表）",
  "gotcha": "`NOT IN` 遇到 NULL 会整体变空 —— 子查询里可能有 NULL 时别用",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "name\n----\n韩立\n小明\n小红\n小刚\n小美\n（5 行）",
  "ok": true
 },
 {
  "id": "sql.between",
  "lang": "sql",
  "cat": "SQL",
  "stage": "近期",
  "name": "BETWEEN",
  "brief": "区间筛选，**两头都算在内**",
  "code": "SELECT name, credit FROM courses WHERE credit BETWEEN 2 AND 5;",
  "where": "按时间/分数区间查",
  "gotcha": "`BETWEEN 2 AND 5` = `>= 2 AND <= 5`（含 5）—— 差一个边界是常见 off-by-one",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "name     | credit\n---------+-------\n数据库   | 3     \n高数     | 5     \n机器学习 | 2     \n英语     | 2     \n（4 行）",
  "ok": true
 },
 {
  "id": "sql.like",
  "lang": "sql",
  "cat": "SQL",
  "stage": "近期",
  "name": "LIKE 通配",
  "brief": "`%` = 任意多个字符，`_` = 正好一个字符",
  "code": "SELECT id, name FROM courses WHERE name LIKE '_数';",
  "where": "模糊搜索 / 清洗数据时找脏值",
  "gotcha": "SQLite 的 LIKE 对 ASCII **大小写不敏感**，对中文当然无所谓 —— 但换成 PostgreSQL 就敏感了",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "id | name\n---+-----\n2  | 高数\n（1 行）",
  "ok": true
 },
 {
  "id": "sql.count",
  "lang": "sql",
  "cat": "SQL",
  "stage": "现在",
  "name": "COUNT(*) / COUNT(列)",
  "brief": "COUNT(*) 数行；COUNT(列) 只数**这一列不是 NULL** 的行",
  "code": "SELECT COUNT(*) AS rows_all, COUNT(grade) AS rows_graded FROM enrollments;",
  "where": "第3课⑥ 诊断第一步：单独数绳子表",
  "gotcha": "两者不一样就说明这列有 NULL —— 这个差值本身就是线索，不是 bug",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "rows_all | rows_graded\n---------+------------\n6        | 5          \n（1 行）",
  "ok": true
 },
 {
  "id": "sql.count_distinct",
  "lang": "sql",
  "cat": "SQL",
  "stage": "近期",
  "name": "COUNT(DISTINCT 列)",
  "brief": "数「有几种」，不是「有几条」",
  "code": "SELECT COUNT(*) AS rows_all, COUNT(DISTINCT cid) AS kinds FROM enrollments;",
  "where": "统计去重后的数量（多少门课被选过）",
  "gotcha": "`COUNT(DISTINCT a, b)` 在 SQLite 里是**语法错误**，多列去重得用子查询",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "rows_all | kinds\n---------+------\n6        | 5    \n（1 行）",
  "ok": true
 },
 {
  "id": "sql.aggregate",
  "lang": "sql",
  "cat": "SQL",
  "stage": "近期",
  "name": "SUM / AVG / MIN / MAX / ROUND",
  "brief": "五个聚合函数，NULL 一律不参与计算",
  "code": "SELECT ROUND(AVG(grade), 1) AS avg_g, MAX(grade) AS top, MIN(grade) AS low\nFROM enrollments WHERE grade IS NOT NULL;",
  "where": "算总分/均分；第7章预习要用",
  "gotcha": "`AVG` 忽略 NULL，所以分母是「有分数的行数」而不是总行数 —— 拿不准就先 `COUNT(*)` 和 `COUNT(列)` 都打出来看",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "avg_g | top  | low \n------+------+-----\n79.3  | 92.0 | 59.0\n（1 行）",
  "ok": true
 },
 {
  "id": "sql.group_by",
  "lang": "sql",
  "cat": "SQL",
  "stage": "近期",
  "name": "GROUP BY",
  "brief": "把行按某列分成堆，每堆出一行（聚合函数的分母就变成「这一堆」）",
  "code": "SELECT cid, COUNT(*) AS n FROM enrollments GROUP BY cid ORDER BY n DESC;",
  "where": "第7章预习 · 每个群的成员数这种「分堆统计」",
  "gotcha": "SELECT 里只能出现**分组列 + 聚合函数**，出现别的列时 SQLite 不报错但会随便挑一行给你（别的数据库直接报错）",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "cid | n\n----+--\n1   | 2\n5   | 1\n4   | 1\n3   | 1\n2   | 1\n（5 行）",
  "ok": true
 },
 {
  "id": "sql.having",
  "lang": "sql",
  "cat": "SQL",
  "stage": "近期",
  "name": "HAVING",
  "brief": "筛「堆」。WHERE 筛行、发生在分组前，HAVING 筛堆、发生在分组后",
  "code": "SELECT cid, COUNT(*) AS n FROM enrollments GROUP BY cid HAVING COUNT(*) > 1;",
  "where": "第7章预习 · 「选课人数 > 1 的课」",
  "gotcha": "写成 `WHERE COUNT(*) > 1` 会直接报错 —— 因为 WHERE 执行时还没分组，没有「每堆」这个概念",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "cid | n\n----+--\n1   | 2\n（1 行）",
  "ok": true
 },
 {
  "id": "sql.where_aggregate_err",
  "lang": "sql",
  "cat": "SQL",
  "stage": "近期",
  "name": "坑：WHERE 里用聚合函数",
  "brief": "WHERE 比 GROUP BY 先执行，所以它根本看不到 COUNT(*)",
  "code": "SELECT cid FROM enrollments WHERE COUNT(*) > 1 GROUP BY cid;",
  "where": "报错现场",
  "gotcha": "看到 `misuse of aggregate function` 就一个动作：把条件从 WHERE 挪到 HAVING",
  "verify": null,
  "err": true,
  "extra": "",
  "out": "OperationalError: misuse of aggregate: COUNT()",
  "ok": false
 },
 {
  "id": "sql.coalesce",
  "lang": "sql",
  "cat": "SQL",
  "stage": "近期",
  "name": "IFNULL / COALESCE",
  "brief": "NULL 换个默认值再显示（NULL 参与算术会让整行变 NULL）",
  "code": "SELECT sid, cid, IFNULL(grade, 0) AS grade FROM enrollments;",
  "where": "配 LEFT JOIN 用：没匹配上的那侧全是 NULL",
  "gotcha": "别用 `IFNULL(grade,0)` 去「修」平均值 —— 用 0 冒充「没考」会把均分拉低，该用 `WHERE grade IS NOT NULL`",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "sid | cid | grade\n----+-----+------\n1   | 1   | 88.5 \n1   | 2   | 76.0 \n2   | 1   | 92.0 \n2   | 3   | 81.0 \n3   | 5   | 59.0 \n4   | 4   | 0    \n（6 行）",
  "ok": true
 },
 {
  "id": "sql.null_eq_trap",
  "lang": "sql",
  "cat": "SQL",
  "stage": "近期",
  "name": "坑：`= NULL` 永远查不出东西",
  "brief": "NULL 的意思是「不知道」，所以「等不等于不知道」的答案是「我也不知道」",
  "code": "SELECT sid, cid FROM enrollments WHERE grade = NULL;",
  "where": "查「没填的那几条」时最常踩",
  "gotcha": "要判 NULL 只能用 `IS NULL` / `IS NOT NULL` —— 这个坑**不报错、只是静默返回 0 行**",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "sid | cid\n----+----\n（0 行）",
  "ok": true
 },
 {
  "id": "sql.is_null",
  "lang": "sql",
  "cat": "SQL",
  "stage": "近期",
  "name": "IS NULL / IS NOT NULL",
  "brief": "判断「这格是不是空的」唯一正确写法",
  "code": "SELECT sid, cid FROM enrollments WHERE grade IS NULL;",
  "where": "找脏数据 / 找漏填的记录",
  "gotcha": "反过来记住：`WHERE grade <> 80` **也不会**把 NULL 的行选出来（NULL 不满足任何比较）",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "sid | cid\n----+----\n4   | 4  \n（1 行）",
  "ok": true
 },
 {
  "id": "sql.case_when",
  "lang": "sql",
  "cat": "SQL",
  "stage": "以后",
  "name": "CASE WHEN",
  "brief": "SQL 里的 if-else，可以放在 SELECT 里造一个新列",
  "code": "SELECT name, CASE WHEN credit >= 3 THEN 'major' ELSE 'minor' END AS weight\nFROM courses;",
  "where": "给数据打标签（分数段/等级），打标后直接喂给模型",
  "gotcha": "不写 `ELSE` 时默认是 NULL，不是原值",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "name     | weight\n---------+-------\n数据库   | major \n高数     | major \n机器学习 | minor \n体育     | minor \n英语     | minor \n（5 行）",
  "ok": true
 },
 {
  "id": "sql.cast",
  "lang": "sql",
  "cat": "SQL",
  "stage": "以后",
  "name": "CAST",
  "brief": "改类型。SQLite 类型松，但拼接/比较时该转还得转",
  "code": "SELECT CAST('42' AS INTEGER) + 1 AS n, CAST(3.7 AS INTEGER) AS i;",
  "where": "从文本里提出来的数字要参与计算时",
  "gotcha": "`CAST(3.7 AS INTEGER)` 是**截断**不是四舍五入（得 3）；要四舍五入用 `ROUND`",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "n  | i\n---+--\n43 | 3\n（1 行）",
  "ok": true
 },
 {
  "id": "sql.string_fn",
  "lang": "sql",
  "cat": "SQL",
  "stage": "以后",
  "name": "UPPER / LOWER / LENGTH",
  "brief": "大小写与长度。注意 LENGTH 数的是**字符**，不是字节",
  "code": "SELECT UPPER('abc') AS u, LOWER('ABC') AS l, LENGTH('数据库') AS n;",
  "where": "数据清洗；校验字段长度",
  "gotcha": "`LENGTH('数据库')` = 3（SQLite 数字符），但 `LENGTH(CAST('数据库' AS BLOB))` = 9 —— 中文是 3 字节",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "u   | l   | n\n----+-----+--\nABC | abc | 3\n（1 行）",
  "ok": true
 },
 {
  "id": "sql.substr_replace",
  "lang": "sql",
  "cat": "SQL",
  "stage": "以后",
  "name": "SUBSTR / REPLACE / TRIM",
  "brief": "截取、替换、去首尾空格 —— 清洗三件套",
  "code": "SELECT SUBSTR('2026-09-24', 1, 4) AS y, REPLACE('a-b', '-', '/') AS r, TRIM('  x  ') AS t;",
  "where": "日志/网页文本清洗",
  "gotcha": "SQLite 的 `SUBSTR` 下标**从 1 开始**（Python 从 0 开始），`SUBSTR(s, 1, 4)` 才是钱 4 个字符",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "y    | r   | t\n-----+-----+--\n2026 | a/b | x\n（1 行）",
  "ok": true
 },
 {
  "id": "sql.date_fn",
  "lang": "sql",
  "cat": "SQL",
  "stage": "以后",
  "name": "date('now') / strftime",
  "brief": "SQLite 没有专门的日期类型，日期就是文本，靠这些函数算",
  "code": "SELECT date('now') AS today, strftime('%Y-%m', 'now') AS ym,\n       CAST(julianday('now') - julianday('2026-09-21') AS INTEGER) AS days;",
  "where": "按天统计；算「距今几天」",
  "gotcha": "`date('now')` 取的是 **UTC** —— 想按北京时间算要写 `date('now','+8 hours')`",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "today      | ym      | days\n-----------+---------+-----\n2026-09-28 | 2026-09 | 7   \n（1 行）",
  "ok": true
 },
 {
  "id": "sql.group_concat",
  "lang": "sql",
  "cat": "SQL",
  "stage": "以后",
  "name": "GROUP_CONCAT",
  "brief": "把一堆行的某列拼成一个字符串（默认用逗号）",
  "code": "SELECT cid, GROUP_CONCAT(sid) AS sids FROM enrollments GROUP BY cid;",
  "where": "「这个群都有谁」 —— 一行拿到全部成员",
  "gotcha": "拼接顺序不保证；要固定顺序得先在外面排序（SQLite 3.44+ 才支持 `GROUP_CONCAT(x ORDER BY y)`）",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "cid | sids\n----+-----\n1   | 1,2 \n2   | 1   \n3   | 2   \n4   | 4   \n5   | 3   \n（5 行）",
  "ok": true
 },
 {
  "id": "sql.join2",
  "lang": "sql",
  "cat": "SQL",
  "stage": "现在",
  "name": "JOIN … ON（两表）",
  "brief": "拿一边的 id 去另一边配对，配对成功才出一行",
  "code": "SELECT s.name, e.cid\nFROM students s\nJOIN enrollments e ON s.id = e.sid;",
  "where": "第3课④ · 本课核心",
  "gotcha": "结果行数 = **配对成功的次数**，不是任何一张表的行数",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "name | cid\n-----+----\n韩立 | 1  \n韩立 | 2  \n小明 | 1  \n小明 | 3  \n小红 | 5  \n小刚 | 4  \n（6 行）",
  "ok": true
 },
 {
  "id": "sql.join3",
  "lang": "sql",
  "cat": "SQL",
  "stage": "现在",
  "name": "三表 JOIN（中间那张是「绳子」）",
  "brief": "行数由中间那张绳子表说了算；两头都只是「换名字」",
  "code": "SELECT s.name AS student, c.name AS course, e.grade\nFROM students s\nJOIN enrollments e ON s.id = e.sid\nJOIN courses     c ON e.cid = c.id;",
  "where": "第3课④ · 第6章换皮就是把它改名",
  "gotcha": "三张表的顺序可以换，但**每一句 ON 必须紧跟着它要拼的那张表**",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "student | course   | grade\n--------+----------+------\n韩立    | 数据库   | 88.5 \n韩立    | 高数     | 76.0 \n小明    | 数据库   | 92.0 \n小明    | 机器学习 | 81.0 \n小红    | 英语     | 59.0 \n小刚    | 体育     | NULL \n（6 行）",
  "ok": true
 },
 {
  "id": "sql.join_alias",
  "lang": "sql",
  "cat": "SQL",
  "stage": "现在",
  "name": "坑：两边都有 id，不给表起别名",
  "brief": "两张表都有 `id` 列时，`ON students.id = courses.id` 里的 id 到底是谁的？",
  "code": "SELECT id, name FROM students JOIN courses ON students.id = courses.id;",
  "where": "报错现场 —— 别名就是为了解决它",
  "gotcha": "`ambiguous column name` 的正确解法是给表起别名然后写全：`s.id`、`c.id`",
  "verify": null,
  "err": true,
  "extra": "",
  "out": "OperationalError: ambiguous column name: id",
  "ok": false
 },
 {
  "id": "sql.join_wrong_zero",
  "lang": "sql",
  "cat": "SQL",
  "stage": "现在",
  "name": "坑①：ON 接反 → 0 行（不报错）",
  "brief": "groups.id 是 1/2/3，group_members.uid 是 7/9/7 —— 一个都对不上",
  "code": "SELECT persons.name AS person, groups.name AS grp\nFROM groups\nJOIN group_members ON groups.id = group_members.uid\nJOIN persons       ON group_members.gid = persons.id;",
  "where": "第3课④ 实测反例 1（低危：空的一眼看得出来）",
  "gotcha": "**JOIN 查出空表时的第一反应应该是「怀疑 ON」，而不是「数据没了」**",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "person | grp\n-------+----\n（0 行）",
  "ok": true
 },
 {
  "id": "sql.join_wrong_fake",
  "lang": "sql",
  "cat": "SQL",
  "stage": "现在",
  "name": "坑②：id 重叠 → 照样出数据（最危险）",
  "brief": "students.id 和 courses.id 都从 1 开始，接反了照样配得上 —— 于是给你一张看着完全合理的假表",
  "code": "SELECT s.name AS student, c.name AS course\nFROM students s\nJOIN enrollments e ON s.id = e.cid\nJOIN courses     c ON e.sid = c.id;",
  "where": "第3课④ 实测反例 2（🔴 高危：静默错误）",
  "gotcha": "「不为空」**绝不等于**「对」。唯一的防线是**挑一行人工核对内容**——这张表里有**根本没选课的小美**、还有对不上课的小红，一眼就能看出不对",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "student | course  \n--------+---------\n韩立    | 数据库  \n小明    | 数据库  \n韩立    | 高数    \n小红    | 高数    \n小美    | 机器学习\n小刚    | 体育    \n（6 行）",
  "ok": true
 },
 {
  "id": "sql.fake_proof",
  "lang": "sql",
  "cat": "SQL",
  "stage": "现在",
  "name": "证明它到底错在哪：行数一样，内容不同",
  "brief": "同一批数据，正确写法和接反写法**都出 6 行**；真正差的是其中 2 行的内容",
  "code": "SELECT\n (SELECT COUNT(*) FROM (\n    SELECT s.name, c.name FROM students s\n      JOIN enrollments e ON s.id = e.sid JOIN courses c ON e.cid = c.id\n    EXCEPT\n    SELECT s.name, c.name FROM students s\n      JOIN enrollments e ON s.id = e.cid JOIN courses c ON e.sid = c.id\n )) AS missing_in_wrong,\n (SELECT COUNT(*) FROM (\n    SELECT s.name, c.name FROM students s\n      JOIN enrollments e ON s.id = e.cid JOIN courses c ON e.sid = c.id\n    EXCEPT\n    SELECT s.name, c.name FROM students s\n      JOIN enrollments e ON s.id = e.sid JOIN courses c ON e.cid = c.id\n )) AS rows_that_are_fake;",
  "where": "第3课④ 那张假数据卡的下半句 —— 用 SQL 自己证明",
  "gotcha": "左边 = 正确结果里有、接反结果里没有的（**漏了 2 行**）；右边 = 接反结果凭空多出来的（**假了 2 行**）。⇒ 只数行数永远发现不了，必须看内容",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "missing_in_wrong | rows_that_are_fake\n-----------------+-------------------\n2                | 2                 \n（1 行）",
  "ok": true
 },
 {
  "id": "sql.diagnose",
  "lang": "sql",
  "cat": "SQL",
  "stage": "现在",
  "name": "诊断三步：先数绳子，再数结果",
  "brief": "① 单独数绳子表 ② 数 JOIN 结果 ③ 两数一致不算过关，再挑一行核对内容",
  "code": "SELECT (SELECT COUNT(*) FROM enrollments) AS rope_rows,\n       (SELECT COUNT(*) FROM students s JOIN enrollments e ON s.id = e.sid) AS join_rows;",
  "where": "第3课⑥ · 本课最实用的迁移技能",
  "gotcha": "数字对不上（空 / 多很多）→ 几乎一定是 ON；数字**对得上**也可能内容错（id 重叠时）",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "rope_rows | join_rows\n----------+----------\n6         | 6        \n（1 行）",
  "ok": true
 },
 {
  "id": "sql.left_join",
  "lang": "sql",
  "cat": "SQL",
  "stage": "现在",
  "name": "LEFT JOIN",
  "brief": "左表一行都不能丢；右表配不上就整行填 NULL",
  "code": "SELECT s.name, e.cid, e.grade\nFROM students s LEFT JOIN enrollments e ON s.id = e.sid;",
  "where": "第3课⑤ 换皮3 · 统计时最常见",
  "gotcha": "把 `LEFT` 去掉，**没选课的人会整个消失** —— 人数从 5 变 4，而且不报错",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "name | cid  | grade\n-----+------+------\n韩立 | 1    | 88.5 \n韩立 | 2    | 76.0 \n小明 | 1    | 92.0 \n小明 | 3    | 81.0 \n小红 | 5    | 59.0 \n小刚 | 4    | NULL \n小美 | NULL | NULL \n（7 行）",
  "ok": true
 },
 {
  "id": "sql.inner_vs_left",
  "lang": "sql",
  "cat": "SQL",
  "stage": "现在",
  "name": "INNER vs LEFT：差在哪一行",
  "brief": "同一条查询，只差 `LEFT` 四个字母，结果少一行",
  "code": "SELECT s.name FROM students s JOIN enrollments e ON s.id = e.sid;",
  "where": "对照上一张卡看：5 个人变成了 4 个人，小美没了",
  "gotcha": "要「一个都不漏」的清单（点名、对账、覆盖率）时必须 LEFT",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "name\n----\n韩立\n韩立\n小明\n小明\n小红\n小刚\n（6 行）",
  "ok": true
 },
 {
  "id": "sql.subquery",
  "lang": "sql",
  "cat": "SQL",
  "stage": "以后",
  "name": "子查询",
  "brief": "把一条 SELECT 的结果当另一条的条件用",
  "code": "SELECT name FROM courses\nWHERE id IN (SELECT cid FROM enrollments WHERE grade > 85);",
  "where": "两步查询懒得写两遍时",
  "gotcha": "`IN (子查询)` 里如果出现 NULL，`NOT IN` 会整体返回空 —— 拿不准就用 `EXISTS`",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "name  \n------\n数据库\n（1 行）",
  "ok": true
 },
 {
  "id": "sql.union",
  "lang": "sql",
  "cat": "SQL",
  "stage": "以后",
  "name": "UNION",
  "brief": "上下摞两条结果集；UNION 去重，UNION ALL 不去重（也更快）",
  "code": "SELECT name FROM students WHERE class = '讯飞班'\nUNION\nSELECT name FROM students WHERE id <= 3;",
  "where": "合并两张结构相同的表（比如两个月的日志）",
  "gotcha": "两边**列数必须一样**，列名以第一条为准 —— 列对不齐时不报错，只会悄悄错位",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "name\n----\n小明\n小红\n韩立\n（3 行）",
  "ok": true
 },
 {
  "id": "sql.tables",
  "lang": "sql",
  "cat": "SQL",
  "stage": "现在",
  "name": "看这个库有哪些表",
  "brief": "不用装数据库工具，一条 SQL 就能看清家底",
  "code": "SELECT name FROM sqlite_master WHERE type = 'table' ORDER BY name;",
  "where": "第3课① 「这库里一共几张表」那道题的正确做法",
  "gotcha": "`sqlite_master` 是 SQLite 专有；MySQL 里叫 `SHOW TABLES`",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "name         \n-------------\ncourses      \nenrollments  \ngroup_members\ngroups       \npersons      \nstudents     \n（6 行）",
  "ok": true
 },
 {
  "id": "sql.pragma",
  "lang": "sql",
  "cat": "SQL",
  "stage": "现在",
  "name": "看一张表的结构",
  "brief": "列名、类型、是否主键，一条 PRAGMA 全给你",
  "code": "PRAGMA table_info(enrollments);",
  "where": "忘了列名时先看这个，别猜",
  "gotcha": "`PRAGMA` 不是标准 SQL（且不吃 `?` 占位符）—— 表名只能拼字符串，只用于自己写死的表名",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "cid | name  | type    | notnull | dflt_value | pk\n----+-------+---------+---------+------------+---\n0   | sid   | INTEGER | 0       | NULL       | 0 \n1   | cid   | INTEGER | 0       | NULL       | 0 \n2   | grade | REAL    | 0       | NULL       | 0 \n（3 行）",
  "ok": true
 },
 {
  "id": "sql.create_table",
  "lang": "sql",
  "cat": "SQL",
  "stage": "现在",
  "name": "CREATE TABLE",
  "brief": "并列三件事：列定义、主键、外键约束",
  "code": "CREATE TABLE enrollments_new (\n    sid   INTEGER NOT NULL REFERENCES students(id),\n    cid   INTEGER NOT NULL REFERENCES courses(id),\n    grade REAL,\n    PRIMARY KEY (sid, cid)\n);",
  "where": "第3课③ · D8 作业的第一件事",
  "gotcha": "**复合主键** `PRIMARY KEY (sid, cid)` 直接防住「同一个人重复选同一门课」—— 比在 Python 里查一遍再插可靠",
  "verify": "PRAGMA table_info(enrollments_new);",
  "err": false,
  "extra": "",
  "out": "cid | name  | type    | notnull | dflt_value | pk\n----+-------+---------+---------+------------+---\n0   | sid   | INTEGER | 1       | NULL       | 1 \n1   | cid   | INTEGER | 1       | NULL       | 2 \n2   | grade | REAL    | 0       | NULL       | 0 \n（3 行）",
  "ok": true
 },
 {
  "id": "sql.insert",
  "lang": "sql",
  "cat": "SQL",
  "stage": "现在",
  "name": "INSERT INTO",
  "brief": "列名写全，值用 `?` 占位（Python 里）",
  "code": "INSERT INTO students (id, name, class) VALUES (6, '小七', '计科1班');",
  "where": "D8 作业：插 3 行数据",
  "gotcha": "列名和值**数量必须一致**，否则报 `table has N columns but M values were supplied`",
  "verify": "SELECT * FROM students WHERE id = 6;",
  "err": false,
  "extra": "",
  "out": "id | name | class  \n---+------+--------\n6  | 小七 | 计科1班\n（1 行）",
  "ok": true
 },
 {
  "id": "sql.update",
  "lang": "sql",
  "cat": "SQL",
  "stage": "近期",
  "name": "UPDATE … WHERE",
  "brief": "改数据。**没有 WHERE 就是改全表**（没有撤销）",
  "code": "UPDATE enrollments SET grade = 90 WHERE sid = 3 AND cid = 5;",
  "where": "补分数、改状态",
  "gotcha": "养成习惯：先把 `WHERE` 那段单拎出来 `SELECT` 一遍，确认命中行数，再改成 UPDATE",
  "verify": "SELECT sid, cid, grade FROM enrollments WHERE sid = 3 AND cid = 5;",
  "err": false,
  "extra": "",
  "out": "sid | cid | grade\n----+-----+------\n3   | 5   | 90.0 \n（1 行）",
  "ok": true
 },
 {
  "id": "sql.delete",
  "lang": "sql",
  "cat": "SQL",
  "stage": "近期",
  "name": "DELETE FROM … WHERE",
  "brief": "删行。同样：**没有 WHERE 就是清空整张表**",
  "code": "DELETE FROM students WHERE id = 5;",
  "where": "删脏数据",
  "gotcha": "删之前先 `SELECT COUNT(*)`；真删表用 `DROP TABLE`（连表结构一起没）",
  "verify": "SELECT COUNT(*) AS left_rows FROM students;",
  "err": false,
  "extra": "",
  "out": "left_rows\n---------\n4        \n（1 行）",
  "ok": true
 },
 {
  "id": "py.sqlite_skeleton",
  "lang": "py",
  "cat": "sqlite3",
  "stage": "现在",
  "name": "六行骨架：连接 → 游标 → 执行 → 取 → 关",
  "brief": "连 Python 和数据库的全部动作就这六行",
  "code": "import sqlite3\nconn = sqlite3.connect(\":memory:\")          # 文件路径；:memory: = 内存库\ncur  = conn.cursor()\ncur.execute(\"CREATE TABLE t (x)\")\ncur.execute(\"INSERT INTO t VALUES (1), (2)\")\nconn.commit()                               # 写操作必须 commit\nfor row in cur.execute(\"SELECT x FROM t\"):\n    print(row)\nconn.close()",
  "where": "第3课 · 所有 SQL 作业的外壳",
  "gotcha": "`commit()` 忘写的后果见下一张卡 —— 它和 `close()` 是**两件事**",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "(1,)\n(2,)",
  "ok": true
 },
 {
  "id": "py.sqlite_commit",
  "lang": "py",
  "cat": "sqlite3",
  "stage": "现在",
  "name": "commit() vs close()：谁在丢数据",
  "brief": "P-014 的实测：换一个连接去读，看数据还在不在",
  "code": "import sqlite3, tempfile, os, shutil\nd = tempfile.mkdtemp(); p = os.path.join(d, \"k.db\")\n\nc = sqlite3.connect(p); c.execute(\"CREATE TABLE t(x)\")\nc.execute(\"INSERT INTO t VALUES (1)\")\nc.close()                                   # 只 close，不 commit\nc2 = sqlite3.connect(p)\nprint(\"commit ✗ / close ✓  → 另一个连接读到\", c2.execute(\"SELECT COUNT(*) FROM t\").fetchone()[0], \"行\")\nc2.close()\n\nc = sqlite3.connect(p); c.execute(\"INSERT INTO t VALUES (2)\")\nc.commit(); c.close()                       # 先 commit，再 close\nc2 = sqlite3.connect(p)\nprint(\"commit ✓ / close ✓  → 另一个连接读到\", c2.execute(\"SELECT COUNT(*) FROM t\").fetchone()[0], \"行\")\nc2.close(); shutil.rmtree(d, ignore_errors=True)",
  "where": "第3课① 检索题（当场答错的那道）· P-014",
  "gotcha": "**丢数据的凶手是 `commit`，不是 `close`。** `close()` 忘写的代价是占资源（见下张卡），不是丢数据",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "commit ✗ / close ✓  → 另一个连接读到 0 行\ncommit ✓ / close ✓  → 另一个连接读到 1 行",
  "ok": true
 },
 {
  "id": "py.sqlite_close",
  "lang": "py",
  "cat": "sqlite3",
  "stage": "现在",
  "name": "close() 忘了写会怎样",
  "brief": "连接不关 → 文件被锁住 → 连删都删不掉",
  "code": "import sqlite3, tempfile, os, shutil\nd = tempfile.mkdtemp(); p = os.path.join(d, \"k.db\")\nc = sqlite3.connect(p); c.execute(\"CREATE TABLE t(x)\"); c.commit()\ntry:\n    os.remove(p)                            # 连接还开着，Windows 不让删\n    print(\"删掉了（没锁）\")\nexcept PermissionError as e:\n    print(\"PermissionError:\", e)\nc.close()\nos.remove(p)                                # 关掉之后再删就成功了\nprint(\"close 之后再删：成功\")\nshutil.rmtree(d, ignore_errors=True)",
  "where": "P-014 的另一半：close 的真实代价",
  "gotcha": "Linux/Mac 上删得掉，**只有 Windows 会当场报 `WinError 32`** —— 所以这个坑在 Windows 上反而更容易被发现",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'E:\\\\Temp\\\\tmptwk_r4_e\\\\k.db'\nclose 之后再删：成功",
  "ok": true
 },
 {
  "id": "py.sqlite_fetch",
  "lang": "py",
  "cat": "sqlite3",
  "stage": "现在",
  "name": "fetchone / fetchall / 直接遍历",
  "brief": "三种取结果的方式，选中一条就不可能再回头",
  "code": "import sqlite3\nconn = sqlite3.connect(\":memory:\")\nconn.execute(\"CREATE TABLE t(x)\")\nconn.executemany(\"INSERT INTO t VALUES (?)\", [(1,), (2,), (3,)])\ncur = conn.cursor()\ncur.execute(\"SELECT x FROM t\")\nprint(\"fetchone →\", cur.fetchone())         # 拿走第 1 行，游标前移\nprint(\"fetchall →\", cur.fetchall())         # 剩下的全拿走\ncur.execute(\"SELECT x FROM t\")\nprint(\"遍历     →\", [r[0] for r in cur])\nconn.close()",
  "where": "取查询结果",
  "gotcha": "游标是**一次性**的：`fetchone()` 之后再 `fetchall()` 拿不到已经取走的那行。要重复用就把结果存进 list",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "fetchone → (1,)\nfetchall → [(2,), (3,)]\n遍历     → [1, 2, 3]",
  "ok": true
 },
 {
  "id": "py.sqlite_executemany",
  "lang": "py",
  "cat": "sqlite3",
  "stage": "现在",
  "name": "executemany() 批量插入",
  "brief": "一次插 20 行，别写 20 条 execute",
  "code": "import sqlite3\nconn = sqlite3.connect(\":memory:\")\nconn.execute(\"CREATE TABLE s(name TEXT, score REAL)\")\nrows = [(\"小明\", 88.5), (\"小红\", 92.0), (\"小刚\", 76.5)]\nconn.executemany(\"INSERT INTO s VALUES (?, ?)\", rows)\nconn.commit()\nprint(conn.execute(\"SELECT COUNT(*) FROM s\").fetchone()[0], \"行\")\nfor r in conn.execute(\"SELECT * FROM s ORDER BY score DESC\"):\n    print(r)\nconn.close()",
  "where": "灌测试数据 / 批量写爬下来的数据",
  "gotcha": "参数是**一个可迭代对象**，每项对应一条语句；写成 `executemany(sql, (1,2))` 会把它当成两行单列",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "3 行\n('小红', 92.0)\n('小明', 88.5)\n('小刚', 76.5)",
  "ok": true
 },
 {
  "id": "py.sqlite_param",
  "lang": "py",
  "cat": "sqlite3",
  "stage": "现在",
  "name": "`?` 占位符（防注入）",
  "brief": "值永远走参数，不要用 f-string 拼进 SQL",
  "code": "import sqlite3\nconn = sqlite3.connect(\":memory:\")\nconn.execute(\"CREATE TABLE t(name TEXT)\"); conn.execute(\"INSERT INTO t VALUES ('小明')\")\nwho = \"小明' OR '1'='1\"                     # 想注入的人会这么输\nn = conn.execute(\"SELECT COUNT(*) FROM t WHERE name = ?\", (who,)).fetchone()[0]\nprint(\"参数化（对）→\", n, \"行\")\nbad = \"SELECT COUNT(*) FROM t WHERE name = '%s'\" % who\nn2 = conn.execute(bad).fetchone()[0]\nprint(\"拼字符串（错）→\", n2, \"行\")\nconn.close()",
  "where": "所有带用户输入的查询",
  "gotcha": "**单元素也必须写成 `(who,)`** —— 少了逗号 `(who)` 只是个字符串，会被当成一个可迭代对象逐字符拆开，报 `Incorrect number of bindings`",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "参数化（对）→ 0 行\n拼字符串（错）→ 1 行",
  "ok": true
 },
 {
  "id": "py.sqlite_row",
  "lang": "py",
  "cat": "sqlite3",
  "stage": "现在",
  "name": "row_factory：按列名取值",
  "brief": "设一次 `row_factory`，之后 `row['name']` 就能用",
  "code": "import sqlite3\nconn = sqlite3.connect(\":memory:\")\nconn.row_factory = sqlite3.Row          # ← 就这一行\nconn.execute(\"CREATE TABLE s(id INTEGER, name TEXT)\")\nconn.execute(\"INSERT INTO s VALUES (1, '小明')\")\nrow = conn.execute(\"SELECT id, name FROM s\").fetchone()\nprint(\"按下标 →\", row[0], row[1])\nprint(\"按列名 →\", row['id'], row['name'])\nprint(\"变字典 →\", dict(row))\nconn.close()",
  "where": "结果列一多，下标就记不住了",
  "gotcha": "`row_factory` 设在 **connection** 上，不是 cursor 上（设 cursor 上是另一套写法）",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "按下标 → 1 小明\n按列名 → 1 小明\n变字典 → {'id': 1, 'name': '小明'}",
  "ok": true
 },
 {
  "id": "py.sqlite_with",
  "lang": "py",
  "cat": "sqlite3",
  "stage": "以后",
  "name": "with：自动 commit / rollback",
  "brief": "`with conn:` 出块时自动提交，出异常自动回滚 —— 但**不会关连接**",
  "code": "import sqlite3\nconn = sqlite3.connect(\":memory:\")\nwith conn:                                  # 成功 → 自动 commit\n    conn.execute(\"CREATE TABLE t(x)\")\n    conn.execute(\"INSERT INTO t VALUES (1)\")\ntry:\n    with conn:                              # 失败 → 自动 rollback\n        conn.execute(\"INSERT INTO t VALUES (2)\")\n        raise ValueError(\"假装中途出错\")\nexcept ValueError as e:\n    print(\"捕获到：\", e)\nprint(\"表里剩\", conn.execute(\"SELECT COUNT(*) FROM t\").fetchone()[0], \"行\")\nconn.close()",
  "where": "写多步操作时不想每步都 commit",
  "gotcha": "`with conn:` ≠ `with sqlite3.connect() as conn:`。后者出块时**会关连接**，很多教程混着讲",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "捕获到： 假装中途出错\n表里剩 1 行",
  "ok": true
 },
 {
  "id": "py.sqlite_error",
  "lang": "py",
  "cat": "sqlite3",
  "stage": "以后",
  "name": "捕获数据库错误",
  "brief": "`IntegrityError` 是约束被违反，`OperationalError` 是表/列名写错",
  "code": "import sqlite3\nconn = sqlite3.connect(\":memory:\")\nconn.execute(\"CREATE TABLE s(id INTEGER PRIMARY KEY, name TEXT UNIQUE)\")\nconn.execute(\"INSERT INTO s VALUES (1, '小明')\")\ntry:\n    conn.execute(\"INSERT INTO s VALUES (2, '小明')\")   # name 重复\nexcept sqlite3.IntegrityError as e:\n    print(\"IntegrityError →\", e)\ntry:\n    conn.execute(\"SELECT * FROM 不存在的表\")\nexcept sqlite3.OperationalError as e:\n    print(\"OperationalError →\", e)\nconn.close()",
  "where": "爬虫/批量写数据时，重复行不该让整个程序崩",
  "gotcha": "两个异常都继承自 `sqlite3.Error`，图省事可以只 `except sqlite3.Error`；但**不要裸 `except:`** —— 会把键盘中断也吞掉",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "IntegrityError → UNIQUE constraint failed: s.name\nOperationalError → no such table: 不存在的表",
  "ok": true
 },
 {
  "id": "py.json_dumps",
  "lang": "py",
  "cat": "标准库",
  "stage": "近期",
  "name": "json.dumps",
  "brief": "Python 对象 → JSON 字符串（接口/存盘都用它）",
  "code": "import json\nd = {\"name\": \"韩立\", \"score\": 88.5, \"tags\": [\"python\", \"sql\"]}\nprint(json.dumps(d, ensure_ascii=False))\nprint(json.dumps(d, ensure_ascii=False, indent=2))",
  "where": "调大模型 API 的请求体；把结果存成文件",
  "gotcha": "`ensure_ascii=False` 不加，中文会变成 `\\u97e9\\u7acb` —— 能用但没法看",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "{\"name\": \"韩立\", \"score\": 88.5, \"tags\": [\"python\", \"sql\"]}\n{\n  \"name\": \"韩立\",\n  \"score\": 88.5,\n  \"tags\": [\n    \"python\",\n    \"sql\"\n  ]\n}",
  "ok": true
 },
 {
  "id": "py.json_loads",
  "lang": "py",
  "cat": "标准库",
  "stage": "近期",
  "name": "json.loads",
  "brief": "JSON 字符串 → Python 对象（大模型返回的就是个字符串）",
  "code": "import json\ns = '{\"answer\": 42, \"ok\": true, \"items\": [1, 2]}'\nd = json.loads(s)\nprint(type(d).__name__, d[\"answer\"], d[\"ok\"], d[\"items\"][1])\nprint(\"访问不存在的键 →\", end=\" \")\ntry:\n    d[\"nope\"]\nexcept KeyError as e:\n    print(\"KeyError\", e)",
  "where": "解析接口/大模型返回",
  "gotcha": "`loads` 吃字符串，`load` 吃文件对象 —— 差一个 s 是两种用法，报错信息很像（都叫 JSONDecodeError）",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "dict 42 True 2\n访问不存在的键 → KeyError 'nope'",
  "ok": true
 },
 {
  "id": "py.json_file",
  "lang": "py",
  "cat": "标准库",
  "stage": "近期",
  "name": "json.dump / json.load 直接读写文件",
  "brief": "省掉 open 那一步",
  "code": "import json, tempfile, os, shutil\nd = tempfile.mkdtemp(); p = os.path.join(d, \"out.json\")\nwith open(p, \"w\", encoding=\"utf-8\") as f:\n    json.dump({\"n\": 3, \"who\": \"韩立\"}, f, ensure_ascii=False)\nwith open(p, encoding=\"utf-8\") as f:\n    print(\"读回来 →\", json.load(f))\nshutil.rmtree(d, ignore_errors=True)",
  "where": "把中间结果存盘，下次不用重跑",
  "gotcha": "**一定要写 `encoding='utf-8'`** —— Windows 默认编码不是 utf-8，中文会乱码或直接 `UnicodeEncodeError`",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "读回来 → {'n': 3, 'who': '韩立'}",
  "ok": true
 },
 {
  "id": "py.open_read",
  "lang": "py",
  "cat": "标准库",
  "stage": "近期",
  "name": "with open(...) 读文件",
  "brief": "`with` 会自动关文件，不用手动 close",
  "code": "import tempfile, os, shutil\nd = tempfile.mkdtemp(); p = os.path.join(d, \"a.txt\")\nopen(p, \"w\", encoding=\"utf-8\").write(\"第一行\\n第二行\\n\")\nwith open(p, encoding=\"utf-8\") as f:\n    for i, line in enumerate(f, 1):\n        print(i, line.rstrip())          # rstrip 去掉行尾换行\nshutil.rmtree(d, ignore_errors=True)",
  "where": "读日志/读 txt 语料",
  "gotcha": "`line` 自带 `\\n`，直接 print 会多一个空行 —— 要么 `rstrip()`，要么 print 时加 `end=''`",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "1 第一行\n2 第二行",
  "ok": true
 },
 {
  "id": "py.open_write",
  "lang": "py",
  "cat": "标准库",
  "stage": "近期",
  "name": "open(..., 'w') 写文件",
  "brief": "`w` 覆盖、`a` 追加，都要显式写编码",
  "code": "import tempfile, os, shutil\nd = tempfile.mkdtemp(); p = os.path.join(d, \"log.txt\")\nwith open(p, \"w\", encoding=\"utf-8\") as f:\n    f.write(\"第一次\\n\")\nwith open(p, \"a\", encoding=\"utf-8\") as f:      # a = 追加，不会覆盖\n    f.write(\"第二次\\n\")\nprint(open(p, encoding=\"utf-8\").read().strip())\nshutil.rmtree(d, ignore_errors=True)",
  "where": "记运行日志 / 导出结果",
  "gotcha": "**`'w'` 会立刻清空原文件** —— 想追加却写了 `'w'`，上一次的结果就没了（且没有提示）",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "第一次\n第二次",
  "ok": true
 },
 {
  "id": "py.os_path",
  "lang": "py",
  "cat": "标准库",
  "stage": "近期",
  "name": "os.path.join / exists",
  "brief": "拼路径永远用 join，别手写 `+ '/' +`",
  "code": "import os\np = os.path.join(\"E:\\\\项目学习\", \"交互演示\", \"函数卡.html\")\nprint(p)\nprint(\"存在吗 →\", os.path.exists(p))\nprint(\"目录名 →\", os.path.dirname(p))\nprint(\"文件名 →\", os.path.basename(p))\nprint(\"扩展名 →\", os.path.splitext(p)[1])",
  "where": "所有涉及文件路径的代码",
  "gotcha": "`os.path.join('E:\\\\a', '/b')` 里第二个参数带开头的斜杠时，**前面的路径会被整个丢掉** —— 得到 `/b`",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "E:\\项目学习\\交互演示\\函数卡.html\n存在吗 → True\n目录名 → E:\\项目学习\\交互演示\n文件名 → 函数卡.html\n扩展名 → .html",
  "ok": true
 },
 {
  "id": "py.os_makedirs",
  "lang": "py",
  "cat": "标准库",
  "stage": "近期",
  "name": "os.makedirs(..., exist_ok=True)",
  "brief": "建多层目录；`exist_ok=True` 让「已存在」不报错",
  "code": "import os, tempfile, shutil\nd = tempfile.mkdtemp()\ntarget = os.path.join(d, \"导出\", \"2026-09\")\nos.makedirs(target, exist_ok=True)\nos.makedirs(target, exist_ok=True)          # 第二次不报错\nprint(\"建好了 →\", os.path.isdir(target))\nshutil.rmtree(d, ignore_errors=True)",
  "where": "写文件前确保目录存在（爬虫存图、导出报告）",
  "gotcha": "不写 `exist_ok=True`，跑第二遍就 `FileExistsError` —— 这是「只在第二次运行才炸」的经典 bug",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "建好了 → True",
  "ok": true
 },
 {
  "id": "py.os_listdir",
  "lang": "py",
  "cat": "标准库",
  "stage": "近期",
  "name": "os.listdir / glob 过滤",
  "brief": "列目录，再按后缀筛",
  "code": "import os, tempfile, shutil\nd = tempfile.mkdtemp()\nfor n in [\"a.txt\", \"b.txt\", \"c.csv\"]:\n    open(os.path.join(d, n), \"w\").close()\nnames = os.listdir(d)\nprint(\"全部 →\", sorted(names))\nprint(\"只要 txt →\", sorted(n for n in names if n.endswith(\".txt\")))\nshutil.rmtree(d, ignore_errors=True)",
  "where": "批量处理一个文件夹里的文件",
  "gotcha": "`listdir` 给的是**文件名**不是完整路径 —— 要打开它得再 `join` 一次（这是最常见的「文件找不到」原因）",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "全部 → ['a.txt', 'b.txt', 'c.csv']\n只要 txt → ['a.txt', 'b.txt']",
  "ok": true
 },
 {
  "id": "py.pathlib",
  "lang": "py",
  "cat": "标准库",
  "stage": "以后",
  "name": "pathlib.Path",
  "brief": "同一件事的现代写法：`/` 拼路径、`.suffix` 取后缀",
  "code": "from pathlib import Path\np = Path(\"E:/项目学习\") / \"交互演示\" / \"函数卡.html\"\nprint(p)\nprint(\"后缀 →\", p.suffix, \"｜ 名字 →\", p.stem, \"｜ 父目录 →\", p.parent.name)\nprint(\"存在吗 →\", p.exists(), \"｜ 是文件吗 →\", p.is_file())",
  "where": "新写的脚本（老代码里 os.path 也常见，两种都要能读）",
  "gotcha": "`Path` 对象不能直接丢给老函数当字符串用 —— 必要时 `str(p)`",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "E:\\项目学习\\交互演示\\函数卡.html\n后缀 → .html ｜ 名字 → 函数卡 ｜ 父目录 → 交互演示\n存在吗 → True ｜ 是文件吗 → True",
  "ok": true
 },
 {
  "id": "py.re_findall",
  "lang": "py",
  "cat": "标准库",
  "stage": "近期",
  "name": "re.findall",
  "brief": "在一段文本里捞出所有符合模式的片段",
  "code": "import re\ntext = \"订单 A1001 金额 88 元；订单 A1002 金额 192 元\"\nprint(\"所有订单号 →\", re.findall(r\"A\\d{4}\", text))\nprint(\"所有数字   →\", re.findall(r\"\\d+\", text))\nprint(\"成对取     →\", re.findall(r\"(A\\d{4}).*?(\\d+) 元\", text))",
  "where": "从网页/日志里提取字段",
  "gotcha": "模式字符串前面**一定要加 r**（原始字符串）—— 不加的话 `\\d` 会被 Python 先当成转义字符处理",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "所有订单号 → ['A1001', 'A1002']\n所有数字   → ['1001', '88', '1002', '192']\n成对取     → [('A1001', '88'), ('A1002', '192')]",
  "ok": true
 },
 {
  "id": "py.re_search",
  "lang": "py",
  "cat": "标准库",
  "stage": "近期",
  "name": "re.search + 分组",
  "brief": "只找第一个；用括号分组把想要的部分单独取出来",
  "code": "import re\nm = re.search(r\"(\\d{4})-(\\d{2})-(\\d{2})\", \"今天是 2026-09-24 周四\")\nif m:\n    print(\"整段 →\", m.group(0))\n    print(\"年 →\", m.group(1), \"｜ 月 →\", m.group(2), \"｜ 日 →\", m.group(3))\n    print(\"命名分组写法 →\", re.search(r\"(?P<y>\\d{4})\", \"2026\").group(\"y\"))\nprint(\"没找到时 →\", re.search(r\"zzz\", \"abc\"))",
  "where": "解析日期、版本号、URL 参数",
  "gotcha": "`re.search` 找不到时返回 **None**，直接 `.group()` 会 `AttributeError` —— 先 `if m:`",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "整段 → 2026-09-24\n年 → 2026 ｜ 月 → 09 ｜ 日 → 24\n命名分组写法 → 2026\n没找到时 → None",
  "ok": true
 },
 {
  "id": "py.re_sub",
  "lang": "py",
  "cat": "标准库",
  "stage": "近期",
  "name": "re.sub",
  "brief": "按模式替换（清洗文本的主力）",
  "code": "import re\ns = \"价格：￥1,299.00 元  （含税）\"\nprint(re.sub(r\"[￥,]\", \"\", s))\nprint(re.sub(r\"\\s+\", \" \", s).strip())\nprint(re.sub(r\"(\\d+)\\.(\\d+)\", r\"\\2.\\1\", \"3.14\"))     # 分组反向引用",
  "where": "清洗爬下来的文本 / 归一化输入",
  "gotcha": "`re.sub` 默认**替换所有**匹配；只想换第一个要加 `count=1`",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "价格：1299.00 元  （含税）\n价格：￥1,299.00 元 （含税）\n14.3",
  "ok": true
 },
 {
  "id": "py.datetime_now",
  "lang": "py",
  "cat": "标准库",
  "stage": "近期",
  "name": "datetime.now() / strftime",
  "brief": "取当前时间，格式化成字符串",
  "code": "from datetime import datetime\nnow = datetime.now()\nprint(\"原样 →\", now)\nprint(\"常用 →\", now.strftime(\"%Y-%m-%d %H:%M:%S\"))\nprint(\"文件名用 →\", now.strftime(\"%Y%m%d-%H%M\"))\nprint(\"星期日历 →\", now.strftime(\"%Y-%m-%d %A\"))",
  "where": "给导出文件起名；记日志时间戳",
  "gotcha": "Windows 上 `strftime('%Y-%m-%d')` 没问题，但**文件名里不能有 `:`** —— `%H:%M` 直接拿去当文件名会失败",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "原样 → 2026-09-28 14:37:48.303849\n常用 → 2026-09-28 14:37:48\n文件名用 → 20260928-1437\n星期日历 → 2026-09-28 Monday",
  "ok": true
 },
 {
  "id": "py.datetime_strptime",
  "lang": "py",
  "cat": "标准库",
  "stage": "近期",
  "name": "strptime：字符串 → 时间",
  "brief": "把文本日期变成能计算的对象（转回来才能减）",
  "code": "from datetime import datetime\nd = datetime.strptime(\"2026-09-21\", \"%Y-%m-%d\")\nprint(\"解析 →\", d, type(d).__name__)\nprint(\"换一种格式 →\", d.strftime(\"%Y年%m月%d日\"))\ntry:\n    datetime.strptime(\"2026/09/21\", \"%Y-%m-%d\")\nexcept ValueError as e:\n    print(\"格式对不上 →\", e)",
  "where": "算复习到期日 / 算实习倒计时",
  "gotcha": "格式串必须和输入**严格一致**（`2026/09/21` 配 `%Y-%m-%d` 会报 `does not match format`）",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "解析 → 2026-09-21 00:00:00 datetime\n换一种格式 → 2026年09月21日\n格式对不上 → time data '2026/09/21' does not match format '%Y-%m-%d'",
  "ok": true
 },
 {
  "id": "py.timedelta",
  "lang": "py",
  "cat": "标准库",
  "stage": "近期",
  "name": "timedelta：日期加减",
  "brief": "算差几天、N 天后是哪天",
  "code": "from datetime import date, timedelta\nanchor = date(2026, 9, 23)                  # 你的倒推起点\nfor n in (1, 3, 7, 30):\n    print(f\"第 {n:>2} 天 →\", anchor + timedelta(days=n))\ngap = date(2027, 3, 1) - anchor\nprint(\"到 2027.03 还有\", gap.days, \"天 ≈\", gap.days // 7, \"周\")",
  "where": "1-3-7-30 复习日程；倒推链",
  "gotcha": "`date - date` 得到 `timedelta`，取天数用 `.days`；`//7` 是**向下取整**的周数（不是四舍五入）",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "第  1 天 → 2026-09-24\n第  3 天 → 2026-09-26\n第  7 天 → 2026-09-30\n第 30 天 → 2026-10-23\n到 2027.03 还有 159 天 ≈ 22 周",
  "ok": true
 },
 {
  "id": "py.counter",
  "lang": "py",
  "cat": "标准库",
  "stage": "以后",
  "name": "collections.Counter",
  "brief": "数词频，一行搞定（比手写字典 +1 干净）",
  "code": "from collections import Counter\nwords = \"数据 数据库 数据 模型 数据库 数据\".split()\nc = Counter(words)\nprint(c)\nprint(\"前三 →\", c.most_common(3))\nprint(\"'数据' 出现 →\", c[\"数据\"], \"次\")\nprint(\"没出现过的词 →\", c[\"不存在\"], \"次（不报错，返回 0）\")",
  "where": "统计标签分布 / 看数据里哪类最多",
  "gotcha": "取不存在的键返回 **0 而不是 KeyError** —— 好处是省事，坏处是拼错词也照样得 0，不报错",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "Counter({'数据': 3, '数据库': 2, '模型': 1})\n前三 → [('数据', 3), ('数据库', 2), ('模型', 1)]\n'数据' 出现 → 3 次\n没出现过的词 → 0 次（不报错，返回 0）",
  "ok": true
 },
 {
  "id": "py.defaultdict",
  "lang": "py",
  "cat": "标准库",
  "stage": "以后",
  "name": "defaultdict(list)：分组",
  "brief": "按 key 把东西塞进不同的桶，不用先判断 key 在不在",
  "code": "from collections import defaultdict\nrows = [(\"讯飞班\", \"韩立\"), (\"计科1班\", \"小红\"), (\"讯飞班\", \"小明\")]\ng = defaultdict(list)\nfor cls, name in rows:\n    g[cls].append(name)\nprint(dict(g))\nprint(\"不存在的班 →\", g[\"不存在\"], \"（自动建了空 list）\")",
  "where": "把一堆 (分类, 内容) 聚成 {分类: [内容]}",
  "gotcha": "读一个不存在的 key 会**顺手创建它** —— 遍历时边读边写会报 `dictionary changed size during iteration`",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "{'讯飞班': ['韩立', '小明'], '计科1班': ['小红']}\n不存在的班 → [] （自动建了空 list）",
  "ok": true
 },
 {
  "id": "py.random",
  "lang": "py",
  "cat": "标准库",
  "stage": "以后",
  "name": "random.choice / sample / randint",
  "brief": "抽一个、抽几个不重复的、抽一个整数",
  "code": "import random\nrandom.seed(42)                             # 固定种子 → 结果可复现\nprint(\"抽一个 →\", random.choice([\"A\", \"B\", \"C\"]))\nprint(\"抽2个不重复 →\", random.sample(range(1, 50), 2))\nprint(\"1~6 的整数 →\", random.randint(1, 6))\nrandom.shuffle(lst := [1, 2, 3, 4])\nprint(\"打乱 →\", lst)",
  "where": "造测试数据 / 切分训练集",
  "gotcha": "`random.seed(42)` 是**可复现**的关键 —— 不设种子，同样的代码每次都出不同结果，bug 就复现不了",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "抽一个 → C\n抽2个不重复 → [8, 2]\n1~6 的整数 → 6\n打乱 → [2, 4, 1, 3]",
  "ok": true
 },
 {
  "id": "py.requests_sig",
  "lang": "py",
  "cat": "第三方",
  "stage": "以后",
  "name": "requests.get（只看签名）",
  "brief": "HTTP 请求最常用的库。这条**只实测了签名**，没联网",
  "code": "import inspect, requests\nprint(\"requests\", requests.__version__)\nprint(\"get\", inspect.signature(requests.get))\nprint(\"post 有 params/data/json →\",\n      all(k in inspect.signature(requests.post).parameters for k in (\"params\", \"data\", \"json\")))",
  "where": "之后调接口 / 爬虫 / 调大模型 API",
  "gotcha": "⚠️ 这段**没有真的发请求**（不允许联网实测）。用法要点：`resp.status_code` 判断成败、`resp.json()` 取 JSON、`resp.text` 取原文、`timeout=` 一定要给（不给会永久挂住）",
  "verify": null,
  "err": false,
  "extra": "[外源] 未联网验证",
  "out": "requests 2.32.5\nget (url, params=None, **kwargs)\npost 有 params/data/json → False",
  "ok": true
 },
 {
  "id": "py.pandas_sig",
  "lang": "py",
  "cat": "第三方",
  "stage": "以后",
  "name": "pandas.read_csv（只看签名）",
  "brief": "读表格数据的事实标准。同样**只实测了签名**",
  "code": "import inspect, pandas as pd\nprint(\"pandas\", pd.__version__)\nprint(\"read_csv\", inspect.signature(pd.read_csv))\ndf = pd.DataFrame({\"a\": [1, 2], \"b\": [\"x\", \"y\"]})\nprint(df.to_string(index=False))",
  "where": "之后做数据分析 / 处理表格数据",
  "gotcha": "⚠️ 只验证了 DataFrame 构造，**没有真读 csv 文件**。要点：`encoding='utf-8'`（中文 csv 常是 `gbk`）、`dtype=` 防手机号被当数字",
  "verify": null,
  "err": false,
  "extra": "[外源] 未读实际文件",
  "out": "pandas 2.3.3\nread_csv (filepath_or_buffer: 'FilePath | ReadCsvBuffer[bytes] | ReadCsvBuffer[str]', *, sep: 'str | None | lib.NoDefault' = <no_default>, delimiter: 'str | None | lib.NoDefault' = None, header: \"int | Sequence[int] | None | Literal['infer']\" = 'infer', names: 'Sequence[Hashable] | None | lib.NoDefault' = <no_default>, index_col: 'IndexLabel | Literal[False] | None' = None, usecols: 'UsecolsArgType' = None, dtype: 'DtypeArg | None' = None, engine: 'CSVEngine | None' = None, converters: 'Mapping[Hashable, Callable] | None' = None, true_values: 'list | None' = None, false_values: 'list | None' = None, skipinitialspace: 'bool' = False, skiprows: 'list[int] | int | Callable[[Hashable], bool] | None' = None, skipfooter: 'int' = 0, nrows: 'int | None' = None, na_values: 'Hashable | Iterable[Hashable] | Mapping[Hashable, Iterable[Hashable]] | None' = None, keep_default_na: 'bool' = True, na_filter: 'bool' = True, verbose: 'bool | lib.NoDefault' = <no_default>, skip_blank_lines: 'bool' = True, parse_dates: 'bool | Sequence[Hashable] | None' = None, infer_datetime_format: 'bool | lib.NoDefault' = <no_default>, keep_date_col: 'bool | lib.NoDefault' = <no_default>, date_parser: 'Callable | lib.NoDefault' = <no_default>, date_format: 'str | dict[Hashable, str] | None' = None, dayfirst: 'bool' = False, cache_dates: 'bool' = True, iterator: 'bool' = False, chunksize: 'int | None' = None, compression: 'CompressionOptions' = 'infer', thousands: 'str | None' = None, decimal: 'str' = '.', lineterminator: 'str | None' = None, quotechar: 'str' = '\"', quoting: 'int' = 0, doublequote: 'bool' = True, escapechar: 'str | None' = None, comment: 'str | None' = None, encoding: 'str | None' = None, encoding_errors: 'str | None' = 'strict', dialect: 'str | csv.Dialect | None' = None, on_bad_lines: 'str' = 'error', delim_whitespace: 'bool | lib.NoDefault' = <no_default>, low_memory: 'bool' = True, memory_map: 'bool' = False, float_precision: \"Literal['high', 'legacy'] | None\" = None, storage_options: 'StorageOptions | None' = None, dtype_backend: 'DtypeBackend | lib.NoDefault' = <no_default>) -> 'DataFrame | TextFileReader'\n a b\n 1 x\n 2 y",
  "ok": true
 },
 {
  "id": "bi.len_range",
  "lang": "py",
  "cat": "内置",
  "stage": "以后",
  "name": "len / range",
  "brief": "len 数长度；range 造一串数字（Python 里**从 0 开始、不含结尾**）",
  "code": "s = \"数据库\"\nprint(\"len →\", len(s), \"｜ range(3) →\", list(range(3)), \"｜ range(1,4) →\", list(range(1, 4)))\nprint(\"倒着数 →\", list(range(3, 0, -1)))\nfor i in range(len(s)):\n    print(i, s[i])",
  "where": "到处都在用",
  "gotcha": "`range(1, 5)` 是 1,2,3,4（**没有 5**）—— 差一个数的 bug 八成来自这里",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "len → 3 ｜ range(3) → [0, 1, 2] ｜ range(1,4) → [1, 2, 3]\n倒着数 → [3, 2, 1]\n0 数\n1 据\n2 库",
  "ok": true
 },
 {
  "id": "bi.enumerate",
  "lang": "py",
  "cat": "内置",
  "stage": "以后",
  "name": "enumerate",
  "brief": "边遍历边拿到序号，别自己维护计数器",
  "code": "for i, name in enumerate([\"小明\", \"小红\"], start=1):\n    print(i, name)\nprint(\"不加 start →\", list(enumerate(\"ab\")))",
  "where": "要「第几条」的时候",
  "gotcha": "`enumerate(x, start=1)` 才是从 1 开始；默认从 **0** 开始",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "1 小明\n2 小红\n不加 start → [(0, 'a'), (1, 'b')]",
  "ok": true
 },
 {
  "id": "bi.zip",
  "lang": "py",
  "cat": "内置",
  "stage": "以后",
  "name": "zip",
  "brief": "把两个列表按位置配对，一次遍历两个",
  "code": "names = [\"小明\", \"小红\", \"小刚\"]\nscores = [88, 92, 76]\nfor n, s in zip(names, scores):\n    print(n, s)\nprint(\"配对成字典 →\", dict(zip(names, scores)))\nprint(\"长度不等时 →\", list(zip([1, 2, 3], \"ab\")))",
  "where": "两个来源的数据要一起处理",
  "gotcha": "长度不等时**按短的截断，不报错** —— 数据对不齐时会静默丢数据（Python 3.10+ 可用 `strict=True` 让它报错）",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "小明 88\n小红 92\n小刚 76\n配对成字典 → {'小明': 88, '小红': 92, '小刚': 76}\n长度不等时 → [(1, 'a'), (2, 'b')]",
  "ok": true
 },
 {
  "id": "bi.sorted_key",
  "lang": "py",
  "cat": "内置",
  "stage": "近期",
  "name": "sorted(key=…)",
  "brief": "排序的万能钥匙：`key` 决定「按什么排」",
  "code": "rows = [(\"小明\", 88.5), (\"小红\", 92.0), (\"小刚\", 76.5)]\nprint(\"按分数 →\", sorted(rows, key=lambda r: r[1], reverse=True))\nd = {\"b\": 2, \"a\": 3, \"c\": 1}\nprint(\"字典按值排 →\", sorted(d.items(), key=lambda kv: kv[1]))\nprint(\"多级排序 →\", sorted(rows, key=lambda r: (-r[1], r[0])))",
  "where": "排行榜 / 按时间排日志 / 结果稳定输出",
  "gotcha": "`key=` 收到的是**函数**，写 `key=r[1]` 会直接报错；`list.sort()` 是原地改，`sorted()` 返回新列表",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "按分数 → [('小红', 92.0), ('小明', 88.5), ('小刚', 76.5)]\n字典按值排 → [('c', 1), ('b', 2), ('a', 3)]\n多级排序 → [('小红', 92.0), ('小明', 88.5), ('小刚', 76.5)]",
  "ok": true
 },
 {
  "id": "bi.sum_min_max",
  "lang": "py",
  "cat": "内置",
  "stage": "以后",
  "name": "sum / min / max",
  "brief": "三个聚合内置，都能配 `key=` 和默认值",
  "code": "nums = [3, 1, 4, 1, 5]\nprint(\"sum →\", sum(nums), \"｜ min →\", min(nums), \"｜ max →\", max(nums))\nprint(\"带初值 →\", sum(nums, 100))\nprint(\"空列表 →\", sum([]), end=\" / \")\ntry:\n    min([])\nexcept ValueError as e:\n    print(\"min 报错：\", e)\nprint(\"按 key 取最大 →\", max([\"aa\", \"bbb\", \"c\"], key=len))",
  "where": "算总分、找最长的那条",
  "gotcha": "`sum([])` 是 0，但 **`min([])` / `max([])` 会报 ValueError** —— 空列表要先用 `default=`（3.4+）或自己判断",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "sum → 14 ｜ min → 1 ｜ max → 5\n带初值 → 114\n空列表 → 0 / min 报错： min() iterable argument is empty\n按 key 取最大 → bbb",
  "ok": true
 },
 {
  "id": "bi.any_all",
  "lang": "py",
  "cat": "内置",
  "stage": "以后",
  "name": "any / all",
  "brief": "一串条件里「有没有一个真的」 / 「是不是全都真」",
  "code": "nums = [2, 4, 6, 8]\nprint(\"全是偶数 →\", all(n % 2 == 0 for n in nums))\nprint(\"有大于 5 的 →\", any(n > 5 for n in nums))\nprint(\"空列表的默认 →\", any([]), all([]))",
  "where": "批量校验（检查所有字段都非空）",
  "gotcha": "空列表时 `all([])` 是 **True**（「全都满足」在逻辑上成立）—— 拿它当「数据没问题」的判断会漏掉空数据的情况",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "全是偶数 → True\n有大于 5 的 → True\n空列表的默认 → False True",
  "ok": true
 },
 {
  "id": "bi.type_cast",
  "lang": "py",
  "cat": "内置",
  "stage": "近期",
  "name": "int / float / str 类型转换",
  "brief": "输入永远是字符串，要算就得先转",
  "code": "print(int(\"42\") + 1, float(\"3.5\") * 2, str(42) + \"!\")\nprint(\"取整 →\", int(3.9), \"（截断不是四舍五入）｜ round →\", round(3.9))\nprint(\"转不了会炸 →\", end=\" \")\ntry:\n    int(\"abc\")\nexcept ValueError as e:\n    print(\"ValueError:\", e)",
  "where": "读用户输入、读文件里的数字",
  "gotcha": "`int(3.9)` 是 **3**（截断）；要四舍五入用 `round()`。`int('3.5')` 也会报错，得先 `float()`",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "43 7.0 42!\n取整 → 3 （截断不是四舍五入）｜ round → 4\n转不了会炸 → ValueError: invalid literal for int() with base 10: 'abc'",
  "ok": true
 },
 {
  "id": "bi.fstring",
  "lang": "py",
  "cat": "内置",
  "stage": "近期",
  "name": "f-string 格式化",
  "brief": "在字符串里直接写变量，还能控制小数位和对齐",
  "code": "name, score = \"韩立\", 88.4567\nprint(f\"{name} 的分数是 {score}\")\nprint(f\"保留两位 → {score:.2f}\")\nprint(f\"百分比   → {score / 100:.1%}\")\nprint(f\"右对齐   → |{name:>8}|｜左对齐 → |{name:<8}|｜补零 → {7:03d}\")",
  "where": "拼日志、拼输出的每一处",
  "gotcha": "f-string 只在字符串**前面有 f** 时生效；`\\n` 在 f-string 里是换行，但**表达式里不能有反斜杠**（3.12 前）",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "韩立 的分数是 88.4567\n保留两位 → 88.46\n百分比   → 88.5%\n右对齐   → |      韩立|｜左对齐 → |韩立      |｜补零 → 007",
  "ok": true
 },
 {
  "id": "llm.client",
  "lang": "py",
  "cat": "LLM API",
  "stage": "阶段A",
  "name": "建客户端：两行换一家模型",
  "brief": "`base_url` 指向谁，就是在用谁家的模型。本机 Ollama 也兼容这套接口",
  "code": "from openai import OpenAI\nclient = OpenAI(base_url=\"http://127.0.0.1:11434/v1\", api_key=\"ollama\")\nprint(\"base_url =\", client.base_url)",
  "where": "AI 应用的第一行代码；物联网线的「大模型 API」也是它",
  "gotcha": "⚠️ **base_url 里写 `127.0.0.1`，不要写 `localhost`** —— Windows 上 localhost 会先解析到 IPv6 `::1`，Ollama 的 `/v1` 在那个地址上连接会被重置（你 09-21 踩过，见 W-28）。`api_key` 用本机 Ollama 时随便填，换真厂商时必须换成真的 key",
  "extra": "",
  "err": false,
  "verify": null,
  "out": "base_url = http://127.0.0.1:11434/v1/",
  "ok": true
 },
 {
  "id": "llm.chat_min",
  "lang": "py",
  "cat": "LLM API",
  "stage": "阶段A",
  "name": "最小一次对话",
  "brief": "`create` 里两个必填：用哪个模型、说什么话",
  "code": "r = client.chat.completions.create(\n    model=MODEL,\n    messages=[{\"role\": \"user\", \"content\": \"只回两个字：你好\"}],\n    temperature=0)\nprint(r.choices[0].message.content)",
  "where": "所有 AI 功能的原子操作",
  "gotcha": "返回的不是字符串，是**对象**：正文在 `r.choices[0].message.content` 里 —— 直接 `print(r)` 会看到一大坨，这是新手第一个卡点",
  "extra": "",
  "err": false,
  "verify": null,
  "out": "你好",
  "ok": true
 },
 {
  "id": "llm.messages",
  "lang": "py",
  "cat": "LLM API",
  "stage": "阶段A",
  "name": "messages 到底是什么",
  "brief": "一个 list，每个元素是 `{role, content}` 的 dict；role 只有四种",
  "code": "msgs = [{\"role\": \"system\", \"content\": \"你只回答一个数字，不要解释\"},\n        {\"role\": \"user\", \"content\": \"1+1 等于几\"}]\nr = client.chat.completions.create(model=MODEL, messages=msgs, temperature=0)\nprint(\"类型 =\", type(msgs).__name__, \"长度 =\", len(msgs))\nprint(\"角色 =\", [m[\"role\"] for m in msgs])\nprint(\"回答 =\", r.choices[0].message.content.strip()[:20])",
  "where": "拼上下文、拼历史、拼检索结果，全是在往这个 list 里塞东西",
  "gotcha": "role 四种：`system`（定规矩）/ `user`（人说的）/ `assistant`（模型说的）/ `tool`（工具结果）。**写错 role 名字不会报错，模型会当成没看见**",
  "extra": "",
  "err": false,
  "verify": null,
  "out": "类型 = list 长度 = 2\n角色 = ['system', 'user']\n回答 = 2",
  "ok": true
 },
 {
  "id": "llm.system",
  "lang": "py",
  "cat": "LLM API",
  "stage": "阶段A",
  "name": "system 与 user 的分工",
  "brief": "system 定规矩、user 提要求。同一句话放进 system，行为会变",
  "code": "q = \"评价一下数据库这门课\"\na = client.chat.completions.create(model=MODEL, temperature=0, max_tokens=30,\n        messages=[{\"role\": \"user\", \"content\": q}]).choices[0].message.content\nb = client.chat.completions.create(model=MODEL, temperature=0, max_tokens=30,\n        messages=[{\"role\": \"system\", \"content\": \"只用四个字回答\"},\n                  {\"role\": \"user\", \"content\": q}]).choices[0].message.content\nprint(\"无 system：\", a.strip()[:40])\nprint(\"有 system：\", b.strip()[:40])",
  "where": "控制输出格式/长度/口吻都在这里",
  "gotcha": "**system 不是必须的**，但它是唯一能稳定约束行为的地方 —— 你 09-21 那个 RAG「装死」问题（检索对了模型却说没有）就是提示词过防御写的，改 system 才好（W-19）",
  "extra": "",
  "err": false,
  "verify": null,
  "out": "无 system： 数据库是一门非常重要的计算机科学课程，它主要研究如何有效地存储和管理大量数据的技\n有 system： 有趣且重要",
  "ok": true
 },
 {
  "id": "llm.temperature",
  "lang": "py",
  "cat": "LLM API",
  "stage": "阶段A",
  "name": "temperature：0 和 1 差在哪",
  "brief": "同一个问题问两次，看回答是否稳定",
  "code": "q = [{\"role\": \"user\", \"content\": \"给这门课起一个名字，只给名字\"}]\nfor t in (0, 1):\n    outs = set()\n    for _ in range(2):\n        r = client.chat.completions.create(model=MODEL, messages=q,\n                                           temperature=t, max_tokens=12)\n        outs.add(r.choices[0].message.content.strip())\n    print(f\"temperature={t}  两次回答不同 = {len(outs) > 1}  {sorted(outs)}\")",
  "where": "要可复现的实验（判分、评测）→ 用 0；要创意/多样 → 调高",
  "gotcha": "**temperature=0 也不保证逐字相同** —— 只能说「更稳定」。所以任何评测都要跑多次取统计，不能拿单次结果下结论（这点在 Agent 消融实验里已经吃过一次）",
  "extra": "",
  "err": false,
  "verify": null,
  "out": "temperature=0  两次回答不同 = False  ['匠心筑梦']\ntemperature=1  两次回答不同 = True  ['智慧探索堂', '智慧探索课']",
  "ok": true
 },
 {
  "id": "llm.max_tokens",
  "lang": "py",
  "cat": "LLM API",
  "stage": "阶段A",
  "name": "max_tokens：把回答截断",
  "brief": "限制生成长度；被截断时 `finish_reason` 会变成 `length`",
  "code": "r = client.chat.completions.create(model=MODEL, temperature=0, max_tokens=5,\n        messages=[{\"role\": \"user\", \"content\": \"用三句话介绍杭州\"}])\nprint(\"内容 =\", repr(r.choices[0].message.content))\nprint(\"finish_reason =\", r.choices[0].finish_reason)",
  "where": "控制成本、控制界面长度",
  "gotcha": "`finish_reason='length'` 就是**被你自己截断的**（不是模型说完了）。做 JSON 输出时被截断 → `json.loads` 直接炸，这时要调大 max_tokens 而不是去改解析代码",
  "extra": "",
  "err": false,
  "verify": null,
  "out": "内容 = '杭州，这座美丽的城市'\nfinish_reason = length",
  "ok": true
 },
 {
  "id": "llm.read_response",
  "lang": "py",
  "cat": "LLM API",
  "stage": "阶段A",
  "name": "从响应里该取哪几个字段",
  "brief": "正文、结束原因、token 用量 —— 三个最常用的",
  "code": "r = client.chat.completions.create(model=MODEL, temperature=0,\n        messages=[{\"role\": \"user\", \"content\": \"只回：好\"}])\nprint(\"正文      =\", r.choices[0].message.content.strip())\nprint(\"结束原因  =\", r.choices[0].finish_reason)\nprint(\"输入 tokens =\", r.usage.prompt_tokens, \" 输出 tokens =\", r.usage.completion_tokens)",
  "where": "算成本、排查「为什么断在半句」都靠它",
  "gotcha": "`usage` 是**按 token 计费**的依据。本机 Ollama 免费，但换真厂商后这一行就是钱 —— 养成每次都看一眼的习惯",
  "extra": "",
  "err": false,
  "verify": null,
  "out": "正文      = 好\n结束原因  = stop\n输入 tokens = 33  输出 tokens = 2",
  "ok": true
 },
 {
  "id": "llm.multiturn",
  "lang": "py",
  "cat": "LLM API",
  "stage": "阶段A",
  "name": "多轮对话：模型其实没有记忆",
  "brief": "它每次都只看到你这次发过去的 messages —— 历史要你自己拼",
  "code": "hist = [{\"role\": \"user\", \"content\": \"我叫韩立\"}]\nr1 = client.chat.completions.create(model=MODEL, messages=hist, temperature=0, max_tokens=20)\nprint(\"第 1 轮问它我是谁（它不知道）：\",\n      client.chat.completions.create(model=MODEL, temperature=0, max_tokens=20,\n        messages=hist + [{\"role\": \"user\", \"content\": \"我叫什么？\"}]).choices[0].message.content.strip()[:24])\nhist.append({\"role\": \"assistant\", \"content\": r1.choices[0].message.content})\nhist.append({\"role\": \"user\", \"content\": \"我叫什么？\"})\nprint(\"第 2 轮先回灌再问：\",\n      client.chat.completions.create(model=MODEL, messages=hist, temperature=0,\n                                     max_tokens=20).choices[0].message.content.strip()[:24])",
  "where": "做聊天界面的核心机制；也是「上下文怎么变长」的根源",
  "gotcha": "🔑 **模型是无状态的**。忘了回灌 assistant 历史 → 它每一轮都像第一次见你。反过来，历史越攒越长 → 迟早爆上下文，所以要裁剪（见 `agent.trim`）",
  "extra": "",
  "err": false,
  "verify": null,
  "out": "第 1 轮问它我是谁（它不知道）： 您叫韩立。\n第 2 轮先回灌再问： 你叫韩立。",
  "ok": true
 },
 {
  "id": "llm.stream",
  "lang": "py",
  "cat": "LLM API",
  "stage": "阶段A",
  "name": "流式输出：一个字一个字吐",
  "brief": "`stream=True` 后返回的是**一堆 chunk**，要自己拼起来",
  "code": "s = client.chat.completions.create(model=MODEL, temperature=0, stream=True,\n        messages=[{\"role\": \"user\", \"content\": \"用三句话介绍杭州，每句以句号结尾。\"}])\nparts = [ch.choices[0].delta.content for ch in s if ch.choices[0].delta.content]\nprint(\"收到\", len(parts), \"个 chunk，前 3 个 =\", parts[:3])\nprint(\"拼起来 =\", \"\".join(parts)[:40])",
  "where": "做「AI 边想边显示」的界面必须用它（否则用户盯着空白等 10 秒）",
  "gotcha": "流式时**没有** `message.content`，只有 `delta.content`；而且最后一块可能是空串，不加 `if` 判断会拼出一堆 `None`",
  "extra": "",
  "err": false,
  "verify": null,
  "out": "收到 20 个 chunk，前 3 个 = ['杭州', '是一座', '历史悠久']\n拼起来 = 杭州是一座历史悠久的城市。西湖以其美丽的风景而闻名。杭州也是美食和茶文化的中心。",
  "ok": true
 },
 {
  "id": "llm.json",
  "lang": "py",
  "cat": "LLM API",
  "stage": "阶段A",
  "name": "让模型吐 JSON（然后真解析）",
  "brief": "`response_format` 要求 JSON；但模型仍可能加解释文字",
  "code": "import json\nr = client.chat.completions.create(model=MODEL, temperature=0,\n        response_format={\"type\": \"json_object\"},\n        messages=[{\"role\": \"user\", \"content\": \"输出 JSON：姓名=韩立，年龄=19\"}])\ntxt = r.choices[0].message.content\nprint(\"原始返回 =\", txt[:50])\nd = json.loads(txt)\nprint(\"解析后 =\", d, type(d).__name__)",
  "where": "让模型当「结构化数据生成器」—— 你要喂给下一段程序的必经一步",
  "gotcha": "模型经常把 JSON 包在 ```json 里。**先 `strip` 掉代码围栏再 `json.loads`**，并且永远包一层 `try/except` —— 它会偶尔漏个引号，你不该因此整个程序崩",
  "extra": "",
  "err": false,
  "verify": null,
  "out": "原始返回 = {\n  \"姓名\": \"韩立\",\n  \"年龄\": 19\n}\n解析后 = {'姓名': '韩立', '年龄': 19} dict",
  "ok": true
 },
 {
  "id": "llm.tools",
  "lang": "py",
  "cat": "LLM API",
  "stage": "阶段A",
  "name": "tools：让模型「要求调用函数」",
  "brief": "你给工具清单，模型决定调哪个、参数是什么 —— 但**它不会真的执行**",
  "code": "tools = [{\"type\": \"function\", \"function\": {\n    \"name\": \"get_weather\", \"description\": \"查某个城市的天气\",\n    \"parameters\": {\"type\": \"object\", \"properties\": {\"city\": {\"type\": \"string\"}},\n                   \"required\": [\"city\"]}}}]\nr = client.chat.completions.create(model=MODEL, temperature=0, tools=tools,\n        messages=[{\"role\": \"user\", \"content\": \"北京现在几度？用工具查\"}])\ntc = r.choices[0].message.tool_calls\nprint(\"finish_reason =\", r.choices[0].finish_reason)\nprint(\"要调的工具 =\", None if not tc else [(x.function.name, x.function.arguments) for x in tc])",
  "where": "Agent 的地基。物联网线的「工具调用」也是这个",
  "gotcha": "🔑 模型只返回**「我想调 get_weather，参数 {\"city\":\"北京\"}」**这串东西 —— **真正执行函数的是你的代码**。参数是**字符串**，要 `json.loads` 才是 dict",
  "extra": "",
  "err": false,
  "verify": null,
  "out": "finish_reason = tool_calls\n要调的工具 = [('get_weather', '{\"city\":\"北京\"}')]",
  "ok": true
 },
 {
  "id": "llm.raw_ollama",
  "lang": "py",
  "cat": "LLM API",
  "stage": "阶段A",
  "name": "原始 /api/chat：为什么还要会这条路",
  "brief": "openai 那条路传不了 `options`（比如 num_ctx），而它决定了你会不会把显存撑爆",
  "code": "import requests\nr = requests.post(\"http://127.0.0.1:11434/api/chat\", timeout=60, json={\n    \"model\": \"qwen2.5:3b\", \"stream\": False,\n    \"messages\": [{\"role\": \"user\", \"content\": \"只回：收到\"}],\n    \"options\": {\"temperature\": 0, \"num_ctx\": 4096}}).json()\nprint(\"正文 =\", r[\"message\"][\"content\"])\nprint(\"本次输出 token =\", r[\"eval_count\"], \"| 耗时 =\", round(r[\"total_duration\"] / 1e9, 2), \"秒\")",
  "where": "你的 `agent_上下文消融.py` 走的就是这条；调本机模型参数必须用它",
  "gotcha": "⚠️ **`num_ctx` 必须给**：Ollama 默认 32768，你 8G 显存撑爆后 runner 会崩，**而且崩之后模型照样输出、只是全是垃圾**（你实测每道题都答 23 —— 比报错危险得多）",
  "extra": "",
  "err": false,
  "verify": null,
  "out": "正文 = 收到\n本次输出 token = 2 | 耗时 = 2.2 秒",
  "ok": true
 },
 {
  "id": "llm.embed_ollama",
  "lang": "py",
  "cat": "LLM API",
  "stage": "阶段A",
  "name": "把文本变成向量（bge-m3）",
  "brief": "embedding 是语义检索的地基：一段文本 → 1024 个数字",
  "code": "e = client.embeddings.create(model=\"bge-m3\", input=\"数据库系统概论\")\nv = e.data[0].embedding\nprint(\"维度 =\", len(v), \"| 前 3 个数 =\", [round(x, 4) for x in v[:3]])\nprint(\"类型 =\", type(v).__name__)",
  "where": "RAG 的第一步；你 09-21 用 bge-m3 把 Recall@1 做到 87%",
  "gotcha": "**向量不是给人看的** —— 单看某个数没有意义，有意义的是两条向量之间的**夹角**（余弦相似度）。同一段文本每次算出来的向量是一样的（不像生成），所以**可以缓存**（见 `rag.cache`）",
  "extra": "",
  "err": false,
  "verify": null,
  "out": "维度 = 1024 | 前 3 个数 = [-0.0232, -0.0057, -0.0558]\n类型 = list",
  "ok": true
 },
 {
  "id": "llm.errors",
  "lang": "py",
  "cat": "LLM API",
  "stage": "阶段A",
  "name": "调用会怎么失败：异常类型 + 重试骨架",
  "brief": "连不上、超时、对方返回错误 —— 三种要分开接",
  "code": "from openai import APIConnectionError, APITimeoutError, APIStatusError\ndef ask(prompt, tries=2):\n    for i in range(tries):\n        try:\n            return client.chat.completions.create(model=MODEL, temperature=0, timeout=3,\n                messages=[{\"role\": \"user\", \"content\": prompt}]).choices[0].message.content\n        except (APITimeoutError, APIConnectionError) as e:\n            print(f\"  第 {i+1} 次失败：{type(e).__name__}\")\n    return None\nprint(\"正常调用 =\", ask(\"只回：好\")[:10])\nbad = OpenAI(base_url=\"http://127.0.0.1:9/v1\", api_key=\"x\", timeout=2)\ntry:\n    bad.chat.completions.create(model=MODEL, messages=[{\"role\": \"user\", \"content\": \"x\"}])\nexcept Exception as e:\n    print(\"打不通的地址会抛 =\", type(e).__name__)",
  "where": "任何要跑一整晚的脚本（评测、消融）都必须有这层",
  "gotcha": "⚠️ 抄你自己代码里那个坑：**`urllib.error.HTTPError` 是 `URLError` 的子类** —— 先接 URLError 会把「服务器返回 500」误报成「连不上」，完全误导排查方向",
  "extra": "",
  "err": false,
  "verify": null,
  "out": "正常调用 = 好\n打不通的地址会抛 = APITimeoutError",
  "ok": true
 },
 {
  "id": "llm.prompt_tpl",
  "lang": "py",
  "cat": "LLM API",
  "stage": "阶段A",
  "name": "提示词模板：把变量拼进问题里",
  "brief": "就是 f-string。但要给模型留出「资料区」，别把指令和资料搅在一起",
  "code": "def build(question, docs):\n    资料 = \"\\n\".join(f\"[{i+1}] {d}\" for i, d in enumerate(docs))\n    return (f\"只根据下面资料回答，资料里没有就说不知道。\\n\\n\"\n            f\"【资料】\\n{资料}\\n\\n【问题】{question}\")\np = build(\"数据库课讲什么\", [\"数据库系统概论讲关系模型和 SQL\", \"高数讲极限\"])\nprint(p)\nprint(\"---\")\nprint(\"模型答：\", client.chat.completions.create(model=MODEL, temperature=0, max_tokens=30,\n        messages=[{\"role\": \"user\", \"content\": p}]).choices[0].message.content.strip()[:40])",
  "where": "RAG 的最后一步；也是「提示词工程」最朴素的形态",
  "gotcha": "给资料**编号**（`[1] [2]`）不是装饰 —— 这样你才能要求模型回答时标「依据 [2]」，出问题时能回溯是哪条资料错了",
  "extra": "",
  "err": false,
  "verify": null,
  "out": "只根据下面资料回答，资料里没有就说不知道。\n\n【资料】\n[1] 数据库系统概论讲关系模型和 SQL\n[2] 高数讲极限\n\n【问题】数据库课讲什么\n---\n模型答： 数据库课讲关系模型和SQL。根据你提供的资料，数据库系统概论课程内容包括关系模型",
  "ok": true
 },
 {
  "id": "agent.tool_schema",
  "lang": "py",
  "cat": "Agent",
  "stage": "阶段A",
  "name": "工具定义：名字 + 说明 + 参数表",
  "brief": "description 写得好不好，直接决定模型会不会用对工具",
  "code": "import json\ndef 定义工具(name, desc, props, required):\n    return {\"type\": \"function\", \"function\": {\"name\": name, \"description\": desc,\n            \"parameters\": {\"type\": \"object\", \"properties\": props, \"required\": required}}}\nt = 定义工具(\"search_notes\", \"在本地学习笔记里搜索关键词，返回命中的片段\",\n             {\"keyword\": {\"type\": \"string\", \"description\": \"要搜的关键词\"}}, [\"keyword\"])\nprint(json.dumps(t, ensure_ascii=False, indent=1))",
  "where": "Agent 的第一块砖；你实验 1-1 里注册的那 4 个工具就是这个结构",
  "gotcha": "`description` 是给**模型**看的（不是注释！）。写「搜索」这种模糊说明，模型就不知道该什么时候用；要写清「**什么时候该用、返回什么**」",
  "extra": "",
  "err": false,
  "verify": null,
  "out": "{\n \"type\": \"function\",\n \"function\": {\n  \"name\": \"search_notes\",\n  \"description\": \"在本地学习笔记里搜索关键词，返回命中的片段\",\n  \"parameters\": {\n   \"type\": \"object\",\n   \"properties\": {\n    \"keyword\": {\n     \"type\": \"string\",\n     \"description\": \"要搜的关键词\"\n    }\n   },\n   \"required\": [\n    \"keyword\"\n   ]\n  }\n }\n}",
  "ok": true
 },
 {
  "id": "agent.dispatch",
  "lang": "py",
  "cat": "Agent",
  "stage": "阶段A",
  "name": "工具分发：名字 → 真函数",
  "brief": "模型只给名字和参数，中间这层映射得你自己写",
  "code": "import json\ndef 查天气(city):        return f\"{city} 晴 26℃\"\ndef 算加法(a, b):        return str(float(a) + float(b))\nTOOLS = {\"get_weather\": 查天气, \"add\": 算加法}\n\ndef 执行(name, args_json):\n    fn = TOOLS.get(name)\n    if fn is None:\n        return f\"没有这个工具：{name}\"\n    try:\n        return fn(**json.loads(args_json))\n    except Exception as e:\n        return f\"工具执行失败：{type(e).__name__}: {e}\"\n\nprint(执行(\"get_weather\", '{\"city\": \"合肥\"}'))\nprint(执行(\"add\", '{\"a\": 1, \"b\": 41}'))\nprint(执行(\"nope\", \"{}\"))",
  "where": "Agent 循环里「模型说要调工具」之后的那一步",
  "gotcha": "🔑 **参数是 JSON 字符串，要 `json.loads`**；模型还可能给不存在的工具名或缺参数 —— **工具执行失败必须变成一段文字回灌给模型**，而不是让程序崩。模型看到「工具执行失败：KeyError」会自己换个参数重试",
  "extra": "",
  "err": false,
  "verify": null,
  "out": "合肥 晴 26℃\n42.0\n没有这个工具：nope",
  "ok": true
 },
 {
  "id": "agent.one_step",
  "lang": "py",
  "cat": "Agent",
  "stage": "阶段A",
  "name": "一步工具调用：完整闭环",
  "brief": "模型要工具 → 你执行 → 把结果回灌 → 模型给最终答案",
  "code": "import json\nTOOLS = [{\"type\": \"function\", \"function\": {\"name\": \"get_weather\", \"description\": \"查城市天气\",\n    \"parameters\": {\"type\": \"object\", \"properties\": {\"city\": {\"type\": \"string\"}}, \"required\": [\"city\"]}}}]\nmsgs = [{\"role\": \"user\", \"content\": \"合肥今天多少度？必须先调工具查，不要猜。\"}]\nr1 = client.chat.completions.create(model=MODEL, messages=msgs, tools=TOOLS, temperature=0)\ncall = r1.choices[0].message.tool_calls[0]\nmsgs.append(r1.choices[0].message)                      # ★ 必须把 assistant 这条也放回去\nmsgs.append({\"role\": \"tool\", \"tool_call_id\": call.id, \"content\": \"合肥 晴 26℃\"})\nr2 = client.chat.completions.create(model=MODEL, messages=msgs, temperature=0, max_tokens=30)\nprint(\"工具要的参数 =\", call.function.arguments)\nprint(\"回灌后最终答 =\", r2.choices[0].message.content.strip()[:30])",
  "where": "Agent 的最小完整闭环；把这段放进 while 就是 Agent 循环",
  "gotcha": "🔑 **`tool` 这条消息必须带 `tool_call_id`**，而且前面必须先把 `assistant`（含 tool_calls）那条塞回历史 —— 少任何一条，模型都不知道你在回应哪个调用",
  "extra": "",
  "err": false,
  "verify": null,
  "out": "工具要的参数 = {\"city\":\"合肥\"}\n回灌后最终答 = 今天合肥的温度是26℃。",
  "ok": true
 },
 {
  "id": "agent.loop",
  "lang": "py",
  "cat": "Agent",
  "stage": "阶段A",
  "name": "Agent 循环骨架（带步数上限）",
  "brief": "while：模型 → 要工具就执行回灌 → 不要工具就结束",
  "code": "import json\nTOOLS = [{\"type\": \"function\", \"function\": {\"name\": \"add\", \"description\": \"两数相加\",\n    \"parameters\": {\"type\": \"object\", \"properties\": {\"a\": {\"type\": \"number\"}, \"b\": {\"type\": \"number\"}},\n                   \"required\": [\"a\", \"b\"]}}}]\nREAL = {\"add\": lambda a, b: a + b}\nmsgs = [{\"role\": \"user\", \"content\": \"先算 (17+25)，再把结果加 8。用工具算。\"}]\nfor step in range(1, 5):\n    r = client.chat.completions.create(model=MODEL, messages=msgs, tools=TOOLS, temperature=0)\n    m = r.choices[0].message\n    if not m.tool_calls:\n        print(f\"第 {step} 步：模型给最终答案 = {m.content.strip()[:40]}\")\n        break\n    msgs.append(m)\n    for c in m.tool_calls:\n        out = REAL[c.function.name](**json.loads(c.function.arguments))\n        print(f\"第 {step} 步：调用 {c.function.name}{c.function.arguments} → {out}\")\n        msgs.append({\"role\": \"tool\", \"tool_call_id\": c.id, \"content\": str(out)})",
  "where": "**这就是 Agent**：LLM + 循环 + 工具。物联网线的「服务组合」和它同构",
  "gotcha": "⚠️ `for step in range(1, 5)` 那个上限**不是可选项** —— 模型可能反复调同一个工具停不下来，没有上限就是死循环 + 无限调用（真厂商那边就是无限花钱）",
  "extra": "",
  "err": false,
  "verify": null,
  "out": "第 1 步：调用 add{\"a\":17,\"b\":25} → 42\n第 1 步：调用 add{\"a\":42,\"b\":8} → 50\n第 2 步：模型给最终答案 = 首先计算 (17+25) 得到 42，然后将结果加 8 得到最终结果 50。",
  "ok": true
 },
 {
  "id": "agent.tool_msg",
  "lang": "py",
  "cat": "Agent",
  "stage": "阶段A",
  "name": "消息序列长什么样（画出来）",
  "brief": "一次工具调用会让 messages 长出两条：assistant(带 tool_calls) 和 tool",
  "code": "import json\nTOOLS = [{\"type\": \"function\", \"function\": {\"name\": \"now\", \"description\": \"取当前时间\",\n    \"parameters\": {\"type\": \"object\", \"properties\": {}}}}]\nmsgs = [{\"role\": \"user\", \"content\": \"现在几点？用工具查\"}]\nr = client.chat.completions.create(model=MODEL, messages=msgs, tools=TOOLS, temperature=0)\nmsgs.append(r.choices[0].message)\nmsgs.append({\"role\": \"tool\", \"tool_call_id\": r.choices[0].message.tool_calls[0].id,\n             \"content\": \"2026-09-28 14:32\"})\nfor i, m in enumerate(msgs, 1):\n    role = m[\"role\"] if isinstance(m, dict) else m.role\n    keys = sorted(m.keys()) if isinstance(m, dict) else \"（对象，字段见 assistant 那条）\"\n    print(f\"{i}. role={role:9s} 字段={keys}\")",
  "where": "调试 Agent 最有效的一招：把 messages 打出来看",
  "gotcha": "**`assistant` 那条在代码里是对象、在列表里可以是 dict** —— 直接 `json.dumps(msgs)` 会报「不是 JSON 可序列化」。要排查就 `print(m.model_dump())`（新版 SDK）",
  "extra": "",
  "err": false,
  "verify": null,
  "out": "1. role=user      字段=['content', 'role']\n2. role=assistant 字段=（对象，字段见 assistant 那条）\n3. role=tool      字段=['content', 'role', 'tool_call_id']",
  "ok": true
 },
 {
  "id": "agent.trim",
  "lang": "py",
  "cat": "Agent",
  "stage": "阶段A",
  "name": "上下文裁剪：聊久了必须扔历史",
  "brief": "保 system + 最近 N 条；扔掉的只能扔，不能「压缩」",
  "code": "def trim(msgs, keep=3):\n    sys = [m for m in msgs if m[\"role\"] == \"system\"]\n    rest = [m for m in msgs if m[\"role\"] != \"system\"]\n    return sys + rest[-keep:]\n\nhist = [{\"role\": \"system\", \"content\": \"你是助手\"}] + [\n    {\"role\": \"user\" if i % 2 else \"assistant\", \"content\": f\"第{i}句\"} for i in range(1, 11)]\nout = trim(hist, keep=3)\nprint(\"原长 =\", len(hist), \"→ 裁后 =\", len(out))\nprint(\"留下 =\", [(m[\"role\"], m[\"content\"]) for m in out])",
  "where": "长对话、长任务（Agent 跑几十步）迟早撞上",
  "gotcha": "⚠️ 裁剪会**切断「工具调用 → 工具结果」的配对**（tool 消息的 tool_call_id 找不到对应的 assistant）—— 有些厂商会直接报错。要按「一轮」为单位裁，不要按条数乱切",
  "extra": "",
  "err": false,
  "verify": null,
  "out": "原长 = 11 → 裁后 = 4\n留下 = [('system', '你是助手'), ('assistant', '第8句'), ('user', '第9句'), ('assistant', '第10句')]",
  "ok": true
 },
 {
  "id": "agent.budget",
  "lang": "py",
  "cat": "Agent",
  "stage": "阶段A",
  "name": "上下文预算：本机显存是硬约束",
  "brief": "同一个问题，给模型多少上下文，直接决定它会不会崩",
  "code": "import requests\ndef ask(num_ctx):\n    r = requests.post(\"http://127.0.0.1:11434/api/chat\", timeout=120, json={\n        \"model\": \"qwen2.5:3b\", \"stream\": False, \"options\": {\"temperature\": 0, \"num_ctx\": num_ctx},\n        \"messages\": [{\"role\": \"user\", \"content\": \"只回：好\"}]}).json()\n    return r.get(\"message\", {}).get(\"content\", \"（空）\")\nfor n in (512, 4096):\n    print(f\"num_ctx={n:5d} → 答 = {ask(n)[:10]}\")",
  "where": "本机跑模型的必备知识；也是 Agent 消融实验能跑完 100 次调用的原因",
  "gotcha": "🔑 **上下文不是越大越好**：KV cache 随 num_ctx 线性吃显存。你 8G 显存实测 32768 会崩，`4096` 之后 30 次突发调用零失败。**判断原则：够放「system + 检索资料 + 最近几轮」就行**",
  "extra": "",
  "err": false,
  "verify": null,
  "out": "num_ctx=  512 → 答 = 好\nnum_ctx= 4096 → 答 = 好",
  "ok": true
 },
 {
  "id": "agent.multi_tools",
  "lang": "py",
  "cat": "Agent",
  "stage": "阶段A",
  "name": "一次返回多个工具调用",
  "brief": "模型可以一轮里同时要求调几个工具 —— 你要按顺序都执行完",
  "code": "import json\nTOOLS = [\n {\"type\": \"function\", \"function\": {\"name\": \"get_weather\", \"description\": \"查城市天气\",\n   \"parameters\": {\"type\": \"object\", \"properties\": {\"city\": {\"type\": \"string\"}}, \"required\": [\"city\"]}}},\n {\"type\": \"function\", \"function\": {\"name\": \"get_time\", \"description\": \"查城市当前时间\",\n   \"parameters\": {\"type\": \"object\", \"properties\": {\"city\": {\"type\": \"string\"}}, \"required\": [\"city\"]}}}]\nr = client.chat.completions.create(model=MODEL, temperature=0, tools=TOOLS,\n        messages=[{\"role\": \"user\", \"content\": \"合肥和杭州的天气、时间都查一下，两个工具都用\"}])\ntcs = r.choices[0].message.tool_calls or []\nprint(\"这一轮要求调\", len(tcs), \"个工具：\",\n      [(c.function.name, json.loads(c.function.arguments)) for c in tcs])",
  "where": "用户问「A 和 B 都查一下」时就是这个形态",
  "gotcha": "**每个 tool_call 都要各自回一条 `role='tool'` 消息**（用各自的 id）。只回一条、或漏掉某一个 id → 模型会以为那个工具还没跑完，然后重复要求调用它",
  "extra": "",
  "err": false,
  "verify": null,
  "out": "这一轮要求调 4 个工具： [('get_weather', {'city': '合肥'}), ('get_time', {'city': '合肥'}), ('get_weather', {'city': '杭州'}), ('get_time', {'city': '杭州'})]",
  "ok": true
 },
 {
  "id": "agent.react",
  "lang": "py",
  "cat": "Agent",
  "stage": "阶段A",
  "name": "ReAct：先写「想法」再决定动作",
  "brief": "强制模型把推理过程说出来，比直接让它调工具更稳",
  "code": "SYS = (\"你是一个会用工具的助手。每次回复必须先写一行「想法：…」（说明你打算怎么做），\"\n       \"再决定是否调用工具。不要跳步。\")\nr = client.chat.completions.create(model=MODEL, temperature=0, max_tokens=60,\n        messages=[{\"role\": \"system\", \"content\": SYS},\n                  {\"role\": \"user\", \"content\": \"我要把 17 和 25 相加再加 8，你打算分几步做？\"}])\nprint(r.choices[0].message.content.strip()[:120])",
  "where": "书上第 1 章的起点思想；调试 Agent 时把想法打出来就知道它哪一步想歪了",
  "gotcha": "「想法」是**给人和给下一轮用的中间产物**，不是真理 —— 模型写「想法：先查天气」然后调了别的工具，这种不一致很常见，要靠工具结果回灌把它拽回来",
  "extra": "",
  "err": false,
  "verify": null,
  "out": "想法：解决这个问题只需要一步，因为它是一个简单的数学计算问题。我们可以直接计算17 + 25 + 8。\n想法：调用工具：None，因为这个问题可以通过简单的数学计算来解决。",
  "ok": true
 },
 {
  "id": "agent.state",
  "lang": "py",
  "cat": "Agent",
  "stage": "阶段A",
  "name": "把 Agent 的状态存下来",
  "brief": "步数、工具调用次数、trace —— 没有它，出了错你只能瞎猜",
  "code": "import json\nstate = {\"steps\": 0, \"tool_calls\": [], \"finished\": False}\ndef step(state, tool_name, result):\n    state[\"steps\"] += 1\n    state[\"tool_calls\"].append({\"step\": state[\"steps\"], \"tool\": tool_name, \"result\": result})\n    if state[\"steps\"] >= 3:\n        state[\"finished\"] = True\n    return state\nstep(state, \"add\", 42); step(state, \"add\", 50)\nprint(json.dumps(state, ensure_ascii=False, indent=1))",
  "where": "跑评测（你的消融实验）时靠它记录每一步，而不是只看最后答案",
  "gotcha": "你 09-21 那次「模型崩了却继续输出垃圾、每道题都答 23」能被发现，正是因为**留了每次的原始回答**。**只记总分，会把「蒙对」藏起来**（那是 W-26 的教训）",
  "extra": "",
  "err": false,
  "verify": null,
  "out": "{\n \"steps\": 2,\n \"tool_calls\": [\n  {\n   \"step\": 1,\n   \"tool\": \"add\",\n   \"result\": 42\n  },\n  {\n   \"step\": 2,\n   \"tool\": \"add\",\n   \"result\": 50\n  }\n ],\n \"finished\": false\n}",
  "ok": true
 },
 {
  "id": "rag.chunk",
  "lang": "py",
  "cat": "RAG",
  "stage": "阶段A",
  "name": "切块：长文本要切开才能检索",
  "brief": "按长度切、留一点重叠 —— 重叠是为了不让一句话被切断在两块里",
  "code": "def chunk(text, size=18, overlap=4):\n    out, i = [], 0\n    while i < len(text):\n        out.append(text[i:i + size])\n        if i + size >= len(text):\n            break\n        i += size - overlap\n    return out\ndoc = \"数据库系统概论讲关系模型和SQL语言。索引能加快查询速度。事务保证数据一致性。\"\nfor i, c in enumerate(chunk(doc), 1):\n    print(f\"{i}. {c}\")",
  "where": "RAG 第一步。docx/pdf 抽出来的长文本必须切",
  "gotcha": "块切太小 → 检索到的片段缺上下文，模型答不全；切太大 → 一块里混了好几个主题，相似度被稀释。**没有标准答案，要拿你的问题去试**",
  "extra": "",
  "err": false,
  "verify": null,
  "out": "1. 数据库系统概论讲关系模型和SQL语言\n2. QL语言。索引能加快查询速度。事务保\n3. 。事务保证数据一致性。",
  "ok": true
 },
 {
  "id": "rag.cosine",
  "lang": "py",
  "cat": "RAG",
  "stage": "阶段A",
  "name": "余弦相似度：两个向量像不像",
  "brief": "点积 / 模长乘积；结果在 -1~1，越大越像",
  "code": "import numpy as np\ndef cos(a, b):\n    a, b = np.asarray(a, dtype=float), np.asarray(b, dtype=float)\n    return float(a @ b / (np.linalg.norm(a) * np.linalg.norm(b)))\nprint(\"自己 == 自己      =\", round(cos([1, 2, 3], [1, 2, 3]), 4))\nprint(\"同方向、长度不同  =\", round(cos([1, 2, 3], [2, 4, 6]), 4))\nprint(\"垂直              =\", round(cos([1, 0], [0, 1]), 4))\nprint(\"相反              =\", round(cos([1, 0], [-1, 0]), 4))",
  "where": "所有语义检索的核心运算；你 `rag/01` 里的排序就是它",
  "gotcha": "**余弦只看方向、不看长度** —— 所以文本长短不影响它，这是它比欧氏距离更适合做文本检索的原因。但它对「模型本身好不好」无能为力：embedding 差，余弦再准也搜不到",
  "extra": "",
  "err": false,
  "verify": null,
  "out": "自己 == 自己      = 1.0\n同方向、长度不同  = 1.0\n垂直              = 0.0\n相反              = -1.0",
  "ok": true
 },
 {
  "id": "rag.topk",
  "lang": "py",
  "cat": "RAG",
  "stage": "阶段A",
  "name": "top-k 检索：排序取前 k 条",
  "brief": "真实用法：把问题也变成向量，和每条资料算相似度，取最大的 k 个",
  "code": "import numpy as np\ndocs = [\"数据库系统概论讲关系模型和SQL\", \"高数讲极限和导数\", \"膳食指南建议少油少盐\"]\nq = \"SQL 是什么\"\n# 这里用字符重合度代替真 embedding，只为演示排序逻辑；真实项目换成 bge-m3\nscore = [len(set(q) & set(d)) / len(set(q) | set(d)) for d in docs]\norder = np.argsort(score)[::-1]\nfor rank, i in enumerate(order[:2], 1):\n    print(f\"第{rank}名  相似度={score[i]:.4f}  {docs[i]}\")",
  "where": "RAG 的「检索」就是这十行；换掉打分函数就是真语义检索",
  "gotcha": "⚠️ 本卡用**字符重合度**代替真 embedding，只为让你看清排序逻辑 —— **这种「零依赖伪向量」对同义词完全无效**（你 09-21 实测：「免疫」「体虚乏力」全部 0 命中，见 W-18）。真项目必须上 `bge-m3`",
  "extra": "",
  "err": false,
  "verify": null,
  "out": "第1名  相似度=0.1579  数据库系统概论讲关系模型和SQL\n第2名  相似度=0.0000  膳食指南建议少油少盐",
  "ok": true
 },
 {
  "id": "rag.tfidf",
  "lang": "py",
  "cat": "RAG",
  "stage": "阶段A",
  "name": "TF-IDF：不上模型的检索基线",
  "brief": "关键词权重检索。做 RAG 时要拿它当对照，才知道语义检索到底赢了多少",
  "code": "from sklearn.feature_extraction.text import TfidfVectorizer\ndocs = [\"数据库系统概论讲关系模型和SQL\", \"高数讲极限和导数\", \"数据库索引加快查询\"]\nv = TfidfVectorizer(analyzer=\"char\", ngram_range=(1, 2))\nX = v.fit_transform(docs)\nprint(\"矩阵形状（文档数 × 特征数）=\", X.shape)\nq = v.transform([\"数据库 索引\"])\nprint(\"每条得分 =\", [round(float(x), 3) for x in (X @ q.T).toarray().ravel()])",
  "where": "物联网线的「服务发现」如果不上模型，就是这个；也是论文里常见的 baseline",
  "gotcha": "`analyzer='char'` 是为中文准备的（中文默认按词切会切错）。**TF-IDF 完全不理解同义词** —— 搜「索引」不会命中「index」，这是它和语义检索的分水岭",
  "extra": "",
  "err": false,
  "verify": null,
  "out": "矩阵形状（文档数 × 特征数）= (3, 53)\n每条得分 = [0.205, 0.08, 0.621]",
  "ok": true
 },
 {
  "id": "rag.assemble",
  "lang": "py",
  "cat": "RAG",
  "stage": "阶段A",
  "name": "把检索到的资料塞进 prompt",
  "brief": "检索 → 拼提示词 → 生成。这一步错了，前面检索再准也白搭",
  "code": "docs = [\"数据库系统概论讲关系模型和 SQL 语言\", \"索引能加快查询速度\"]\nq = \"为什么要建索引\"\nctx = \"\\n\".join(f\"[{i+1}] {d}\" for i, d in enumerate(docs))\nprompt = f\"只根据下面资料回答；资料里没有就说不知道。\\n{ctx}\\n\\n问题：{q}\"\nprint(\"拼好的提示词 ↓\")\nprint(prompt)\nprint(\"模型答：\", client.chat.completions.create(model=MODEL, temperature=0, max_tokens=40,\n        messages=[{\"role\": \"user\", \"content\": prompt}]).choices[0].message.content.strip()[:50])",
  "where": "RAG 的第三步；也是 `rag/02` 干的事",
  "gotcha": "⚠️ **必须写「资料里没有就说不知道」**，否则模型会拿它自己的知识编 —— 那就不叫 RAG 了。但这条又不能写太狠：你 09-21 实测过，过度防御的提示词会让模型「装死」（检索明明命中却说没有，见 W-19）",
  "extra": "",
  "err": false,
  "verify": null,
  "out": "拼好的提示词 ↓\n只根据下面资料回答；资料里没有就说不知道。\n[1] 数据库系统概论讲关系模型和 SQL 语言\n[2] 索引能加快查询速度\n\n问题：为什么要建索引\n模型答： 索引能加快查询速度，因为通过在数据库表中创建索引，可以提高数据检索的速度，特别是在需要频繁查询的列上",
  "ok": true
 },
 {
  "id": "rag.recall",
  "lang": "py",
  "cat": "RAG",
  "stage": "阶段A",
  "name": "评测检索质量：Recall@k 和 MRR",
  "brief": "没有评测的 RAG 只是「感觉还行」—— 你那次量化到 Recall@1 87%",
  "code": "def recall_at_k(ranks, k):        # ranks: 每条问题的正确资料排在第几名（从 1 开始）\n    return sum(1 for r in ranks if r <= k) / len(ranks)\ndef mrr(ranks):\n    return sum(1 / r for r in ranks) / len(ranks)\nranks = [1, 1, 2, 1, 3, 1, 1, 5, 1, 2]     # 10 个问题的正确命中位次\nprint(f\"Recall@1 = {recall_at_k(ranks, 1):.0%}   Recall@3 = {recall_at_k(ranks, 3):.0%}\")\nprint(f\"MRR      = {mrr(ranks):.3f}\")",
  "where": "要向导师/面试官说「我的检索效果是 X%」时，必须有这个数",
  "gotcha": "**评测集必须是你自己标的**（哪条资料才是正确答案）。用模型自己判断对错 = 自己给自己打分。你的 RAG 那次是手工标的小集，样本量小 —— 报数字时要一起说样本量，别只报百分比",
  "extra": "",
  "err": false,
  "verify": null,
  "out": "Recall@1 = 60%   Recall@3 = 90%\nMRR      = 0.753",
  "ok": true
 },
 {
  "id": "rag.cache",
  "lang": "py",
  "cat": "RAG",
  "stage": "阶段A",
  "name": "把向量缓存到本地",
  "brief": "embedding 是确定的，算一次就够了 —— 省时间，也省钱",
  "code": "import json, hashlib, tempfile, os, shutil\ndef key(t):\n    return hashlib.md5(t.encode(\"utf-8\")).hexdigest()[:12]\nd = tempfile.mkdtemp(); p = os.path.join(d, \"cache.json\")\ndocs = [\"数据库系统概论\", \"高数讲义\"]\ncache = {key(t): [1, 2, 3] for t in docs}          # 假装这里是真的 1024 维向量\nwith open(p, \"w\", encoding=\"utf-8\") as f:\n    json.dump(cache, f, ensure_ascii=False)\nagain = json.load(open(p, encoding=\"utf-8\"))\nprint(\"缓存键 =\", list(again))\nprint(\"命中第一条 =\", key(\"数据库系统概论\") in again, \"| 维度 =\", len(again[key(\"数据库系统概论\")]))\nshutil.rmtree(d, ignore_errors=True)",
  "where": "你 `rag/_embeddings-cache.json` 就是干这个的（170 KB）",
  "gotcha": "缓存键要用**文本的 hash**，不要用「第几条」—— 文档一增删，序号全乱，缓存就变成了错答案。换 embedding 模型时**必须清缓存**（不同模型的向量不可比）",
  "extra": "",
  "err": false,
  "verify": null,
  "out": "缓存键 = ['a71b1e14fec6', 'c83a669ffc07']\n命中第一条 = True | 维度 = 3",
  "ok": true
 },
 {
  "id": "pd.read_csv",
  "lang": "py",
  "cat": "数据",
  "stage": "阶段A",
  "name": "pandas 读 CSV",
  "brief": "两行读进来，形状、列名、前几行立刻能看到",
  "code": "import pandas as pd, tempfile, os, shutil\nd = tempfile.mkdtemp(); p = os.path.join(d, \"people.csv\")\nopen(p, \"w\", encoding=\"utf-8\").write(\"姓名,年龄,标签\\n王奶奶,78,独居\\n李爷爷,82,糖尿病\\n\")\ndf = pd.read_csv(p, encoding=\"utf-8\")\nprint(\"形状（行, 列）=\", df.shape)\nprint(\"列名 =\", list(df.columns))\nprint(df.to_string(index=False))\nshutil.rmtree(d, ignore_errors=True)",
  "where": "物联网线要处理老人数据；任何 Excel/CSV 分析的第一步",
  "gotcha": "⚠️ 中文 CSV 常是 **GBK**：`encoding='utf-8'` 报 `UnicodeDecodeError` 时换 `'gbk'`。还有 `dtype={'手机号': str}` —— 不然前导 0 和长数字会被 pandas 改掉",
  "extra": "",
  "err": false,
  "verify": null,
  "out": "形状（行, 列）= (2, 3)\n列名 = ['姓名', '年龄', '标签']\n 姓名  年龄  标签\n王奶奶  78  独居\n李爷爷  82 糖尿病",
  "ok": true
 },
 {
  "id": "pd.select",
  "lang": "py",
  "cat": "数据",
  "stage": "阶段A",
  "name": "选列 / 按条件筛选",
  "brief": "`df[列名]` 取列、`df[布尔条件]` 取行",
  "code": "import pandas as pd\ndf = pd.DataFrame({\"姓名\": [\"王奶奶\", \"李爷爷\", \"张阿姨\"], \"年龄\": [78, 82, 65],\n                   \"标签\": [\"独居\", \"糖尿病\", \"独居\"]})\nprint(\"只取一列 →\", list(df[\"年龄\"]))\nprint(\"按条件筛 →\")\nprint(df[df[\"年龄\"] > 70].to_string(index=False))\nprint(\"两个条件要用 & 并加括号 →\", len(df[(df[\"年龄\"] > 70) & (df[\"标签\"] == \"独居\")]))",
  "where": "清洗数据、挑出要分析的那部分",
  "gotcha": "**多条件必须用 `&` `|`，不能用 `and` `or`**，而且**每个条件都要自己加括号** —— `df[df.a > 1 & df.b < 2]` 不会报错，只会给你错结果（运算符优先级）",
  "extra": "",
  "err": false,
  "verify": null,
  "out": "只取一列 → [78, 82, 65]\n按条件筛 →\n 姓名  年龄  标签\n王奶奶  78  独居\n李爷爷  82 糖尿病\n两个条件要用 & 并加括号 → 1",
  "ok": true
 },
 {
  "id": "pd.groupby",
  "lang": "py",
  "cat": "数据",
  "stage": "阶段A",
  "name": "groupby：pandas 里的分堆统计",
  "brief": "和第 7 章 SQL 的 `GROUP BY` 是同一件事，只是换了语言",
  "code": "import pandas as pd\ndf = pd.DataFrame({\"标签\": [\"独居\", \"糖尿病\", \"独居\", \"糖尿病\", \"独居\"],\n                   \"年龄\": [78, 82, 65, 71, 88]})\ng = df.groupby(\"标签\")[\"年龄\"]\nprint(\"每组人数 =\"); print(g.count().to_string())\nprint(\"每组平均 =\"); print(g.mean().round(1).to_string())\nprint(\"一次算多个 =\"); print(g.agg([\"count\", \"mean\", \"max\"]).to_string())",
  "where": "统计分布；对应你 SQL 里刚学的 `GROUP BY cid, COUNT(*)`",
  "gotcha": "`groupby` **默认把分组列变成索引**；想让它留成普通列加 `as_index=False` 或 `.reset_index()`。忘了这一步，后面 `merge` 会莫名其妙对不上",
  "extra": "",
  "err": false,
  "verify": null,
  "out": "每组人数 =\n标签\n独居     3\n糖尿病    2\n每组平均 =\n标签\n独居     77.0\n糖尿病    76.5\n一次算多个 =\n     count  mean  max\n标签                   \n独居       3  77.0   88\n糖尿病      2  76.5   82",
  "ok": true
 },
 {
  "id": "pd.merge",
  "lang": "py",
  "cat": "数据",
  "stage": "阶段A",
  "name": "merge：pandas 的 JOIN（和第 3 课一模一样）",
  "brief": "参数就是 `left_on` / `right_on` / `how` —— how 就是 INNER / LEFT",
  "code": "import pandas as pd\n老人 = pd.DataFrame({\"id\": [1, 2, 3], \"姓名\": [\"王奶奶\", \"李爷爷\", \"张阿姨\"]})\n需求 = pd.DataFrame({\"老人id\": [1, 1, 2], \"需求\": [\"助餐\", \"陪诊\", \"助浴\"]})\ninner = 老人.merge(需求, left_on=\"id\", right_on=\"老人id\", how=\"inner\")\nleft  = 老人.merge(需求, left_on=\"id\", right_on=\"老人id\", how=\"left\")\nprint(\"inner（两边都配上才留）行数 =\", len(inner))\nprint(inner[[\"姓名\", \"需求\"]].to_string(index=False))\nprint(\"left（左边一个都不能丢）行数 =\", len(left), \"| 没需求的显示 =\", left[\"需求\"].isna().sum(), \"个 NaN\")",
  "where": "🔑 **你刚学的 JOIN 直接迁移过来** —— 同一个概念换个语言；物联网线合并两张表靠它",
  "gotcha": "和 SQL 同一个坑：**`how='left'` 去掉就是 inner，左边的行会整个消失**。另外 pandas 里 NULL 显示成 `NaN`，判断要用 `isna()` 而不是 `== None`",
  "extra": "",
  "err": false,
  "verify": null,
  "out": "inner（两边都配上才留）行数 = 3\n 姓名 需求\n王奶奶 助餐\n王奶奶 陪诊\n李爷爷 助浴\nleft（左边一个都不能丢）行数 = 4 | 没需求的显示 = 1 个 NaN",
  "ok": true
 },
 {
  "id": "pd.to_json",
  "lang": "py",
  "cat": "数据",
  "stage": "阶段A",
  "name": "DataFrame → 喂给模型 / 存盘",
  "brief": "转成 dict/list 再 `json.dumps`，就能塞进 prompt 或发出去",
  "code": "import pandas as pd, json\ndf = pd.DataFrame({\"姓名\": [\"王奶奶\", \"李爷爷\"], \"年龄\": [78, 82]})\nprint(\"转 dict 列表 =\", df.to_dict(orient=\"records\"))\nprint(\"紧凑 JSON =\", df.to_json(orient=\"records\", force_ascii=False))\nprint(\"给模型的表格文本 ↓\")\nprint(df.to_csv(index=False, sep=\"|\").strip())",
  "where": "让模型「看」表格数据：最省 token 的方式是 CSV 文本，不是 JSON",
  "gotcha": "**JSON 比 CSV 费 token**（每个字段名重复一遍）。行数多的时候优先给 CSV。`to_json` 默认把中文转成 `\\\\uXXXX`，要 `force_ascii=False`",
  "extra": "",
  "err": false,
  "verify": null,
  "out": "转 dict 列表 = [{'姓名': '王奶奶', '年龄': 78}, {'姓名': '李爷爷', '年龄': 82}]\n紧凑 JSON = [{\"姓名\":\"王奶奶\",\"年龄\":78},{\"姓名\":\"李爷爷\",\"年龄\":82}]\n给模型的表格文本 ↓\n姓名|年龄\r\n王奶奶|78\r\n李爷爷|82",
  "ok": true
 },
 {
  "id": "np.vector",
  "lang": "py",
  "cat": "数据",
  "stage": "阶段A",
  "name": "numpy 向量化：别写 for 循环算数",
  "brief": "同样的计算，向量化版本短得多、快得多",
  "code": "import numpy as np, time\na = np.arange(200_000); b = np.arange(200_000)\nt = time.perf_counter(); c1 = [x + y for x, y in zip(a.tolist(), b.tolist())]; t1 = time.perf_counter() - t\nt = time.perf_counter(); c2 = a + b; t2 = time.perf_counter() - t\nprint(f\"循环 {t1*1000:.1f} ms   向量化 {t2*1000:.1f} ms   快 {t1/t2:.0f} 倍\")\nprint(\"结果相同 =\", c1[:3] == list(c2[:3]))",
  "where": "处理几万条老人数据时，这是「跑得动」和「跑不动」的区别",
  "gotcha": "**向量化不是「更快的循环」，是「根本不循环」**（底层 C 一次算一批）。但遇到「这一步依赖上一步结果」的逻辑，向量化写不出来 —— 该用循环就用循环",
  "extra": "",
  "err": false,
  "verify": null,
  "out": "循环 17.8 ms   向量化 0.7 ms   快 24 倍\n结果相同 = True",
  "ok": true
 },
 {
  "id": "np.norm",
  "lang": "py",
  "cat": "数据",
  "stage": "阶段A",
  "name": "归一化：把向量变成单位长度",
  "brief": "除以模长。语义检索里提前归一化，后面算相似度就只剩点积",
  "code": "import numpy as np\nv = np.array([3.0, 4.0])\nu = v / np.linalg.norm(v)\nprint(\"原向量 =\", v, \" 模长 =\", np.linalg.norm(v))\nprint(\"单位向量 =\", u, \" 新模长 =\", round(float(np.linalg.norm(u)), 6))\nprint(\"归一化后 点积 == 余弦 =\", round(float(u @ u), 6))",
  "where": "批量检索时先归一化 → 相似度计算退化成一个矩阵乘法，快很多",
  "gotcha": "**零向量不能归一化**（除以 0 → `nan`），检索时会静默排到最后。如果某条资料抽出来是空文本，它的向量就是零向量 —— 要先过滤掉",
  "extra": "",
  "err": false,
  "verify": null,
  "out": "原向量 = [3. 4.]  模长 = 5.0\n单位向量 = [0.6 0.8]  新模长 = 1.0\n归一化后 点积 == 余弦 = 1.0",
  "ok": true
 },
 {
  "id": "pd.datetime",
  "lang": "py",
  "cat": "数据",
  "stage": "阶段A",
  "name": "时间列：字符串 → 真时间",
  "brief": "`to_datetime` 之后才能排序、算间隔、按月分组",
  "code": "import pandas as pd\ndf = pd.DataFrame({\"服务日期\": [\"2026-03-01\", \"2026-03-15\", \"2026-04-02\"], \"时长\": [40, 60, 30]})\ndf[\"服务日期\"] = pd.to_datetime(df[\"服务日期\"])\ndf[\"月份\"] = df[\"服务日期\"].dt.strftime(\"%Y-%m\")\nprint(df.to_string(index=False))\nprint(\"按月合计时长 =\"); print(df.groupby(\"月份\")[\"时长\"].sum().to_string())",
  "where": "时间序列分析；你那 52,482 条真实活动数据必然用得上",
  "gotcha": "**不转 `to_datetime` 就 `.dt` 会报错** —— 字符串没有 `.dt`。格式不统一（`2026/3/1` 混 `2026-03-01`）时要加 `format='mixed'` 或 `dayfirst=`",
  "extra": "",
  "err": false,
  "verify": null,
  "out": "      服务日期  时长      月份\n2026-03-01  40 2026-03\n2026-03-15  60 2026-03\n2026-04-02  30 2026-04\n按月合计时长 =\n月份\n2026-03    100\n2026-04     30",
  "ok": true
 },
 {
  "id": "fa.app",
  "lang": "py",
  "cat": "FastAPI",
  "stage": "阶段A",
  "name": "最小应用 + 一个接口",
  "brief": "装饰器写路径，函数返回什么就发什么（dict 自动变 JSON）",
  "code": "from fastapi import FastAPI\napp = FastAPI()\n@app.get(\"/hello\")\ndef hello():\n    return {\"msg\": \"你好\"}\nprint(\"路径表 =\", [r.path for r in app.routes if r.path.startswith(\"/\")])\nprint(\"方法   =\", [sorted(r.methods)[0] for r in app.routes if r.path == \"/hello\"])",
  "where": "你 `api.py` 的骨架；服务器 8009 端口上跑的就是这个",
  "gotcha": "**返回 dict 就会被自动转成 JSON** —— 你不需要 `json.dumps`。但返回一个不能序列化的对象（比如 datetime 以外的自定义类）会 500",
  "extra": "",
  "err": false,
  "verify": null,
  "out": "路径表 = ['/openapi.json', '/docs', '/docs/oauth2-redirect', '/redoc', '/hello']\n方法   = ['GET']",
  "ok": true
 },
 {
  "id": "fa.testclient",
  "lang": "py",
  "cat": "FastAPI",
  "stage": "阶段A",
  "name": "不启服务器也能测接口",
  "brief": "`TestClient` 直接把请求喂给 app —— 你 27 个测试就是这么跑的",
  "code": "from fastapi import FastAPI\nfrom fastapi.testclient import TestClient\napp = FastAPI()\n@app.get(\"/add\")\ndef add(a: int, b: int):\n    return {\"result\": a + b}\nc = TestClient(app)\nr = c.get(\"/add\", params={\"a\": 17, \"b\": 25})\nprint(\"状态码 =\", r.status_code)\nprint(\"返回 JSON =\", r.json())\nbad = c.get(\"/add\", params={\"a\": \"abc\", \"b\": 1})\nprint(\"传错类型 → 状态码 =\", bad.status_code, \"| 详情里有 =\", list(bad.json()[\"detail\"][0].keys()))",
  "where": "写测试的正确姿势：不起服务器、不占端口、毫秒级",
  "gotcha": "**必填参数没传 → 422 不是 400**（FastAPI 的校验错误码是 422）。另外返回的 `r.json()` 才是 dict，`r.text` 是字符串",
  "extra": "",
  "err": false,
  "verify": null,
  "out": "状态码 = 200\n返回 JSON = {'result': 42}\n传错类型 → 状态码 = 422 | 详情里有 = ['type', 'loc', 'msg', 'input']",
  "ok": true
 },
 {
  "id": "fa.pydantic",
  "lang": "py",
  "cat": "FastAPI",
  "stage": "阶段A",
  "name": "请求体 + 自动校验（Pydantic）",
  "brief": "定义模型 → 参数写模型 → 校验、文档、类型全自动",
  "code": "from fastapi import FastAPI\nfrom fastapi.testclient import TestClient\nfrom pydantic import BaseModel, Field\nclass 老人需求(BaseModel):\n    老人编号: int = Field(gt=0, description=\"必须正整数\")\n    需求: list[str] = Field(min_length=1)\n    预算: float | None = None\napp = FastAPI()\n@app.post(\"/needs\")\ndef add_need(n: 老人需求):\n    return {\"收到\": n.需求, \"条数\": len(n.需求)}\nc = TestClient(app)\nprint(c.post(\"/needs\", json={\"老人编号\": 1, \"需求\": [\"助餐\"], \"预算\": 30.0}).json())\nprint(\"需求给空列表 →\", c.post(\"/needs\", json={\"老人编号\": 1, \"需求\": []}).status_code)\nprint(\"编号给 0 →\", c.post(\"/needs\", json={\"老人编号\": 0, \"需求\": [\"助餐\"]}).status_code)",
  "where": "接口的「守门员」；字段一多，手写校验必然出错",
  "gotcha": "**`预算: float | None = None` 才是可选的**；写成 `预算: float = None` 类型标注就骗人了。另外字段名用中文是可以的（Python 3 标识符支持），但**发给别人用时会很难受**，慎用",
  "extra": "",
  "err": false,
  "verify": null,
  "out": "{'收到': ['助餐'], '条数': 1}\n需求给空列表 → 422\n编号给 0 → 422",
  "ok": true
 },
 {
  "id": "fa.error",
  "lang": "py",
  "cat": "FastAPI",
  "stage": "阶段A",
  "name": "主动返回错误：HTTPException",
  "brief": "业务上「不允许」要自己抛，顺便给前端一句人话",
  "code": "from fastapi import FastAPI, HTTPException\nfrom fastapi.testclient import TestClient\napp = FastAPI()\nDB = {1: \"王奶奶\"}\n@app.get(\"/elder/{eid}\")\ndef get_elder(eid: int):\n    if eid not in DB:\n        raise HTTPException(status_code=404, detail=f\"没有编号为 {eid} 的老人\")\n    return {\"姓名\": DB[eid]}\nc = TestClient(app)\nprint(\"存在 →\", c.get(\"/elder/1\").json())\nr = c.get(\"/elder/99\")\nprint(\"不存在 →\", r.status_code, r.json()[\"detail\"])",
  "where": "第 2 课那个 404 排查法讲的就是这个；现在你能造 404 了",
  "gotcha": "**`detail` 会被原样发给调用方** —— 不要把堆栈、SQL、路径塞进去（信息泄露）。想统一改返回格式，用 `@app.exception_handler`",
  "extra": "",
  "err": false,
  "verify": null,
  "out": "存在 → {'姓名': '王奶奶'}\n不存在 → 404 没有编号为 99 的老人",
  "ok": true
 },
 {
  "id": "fa.query",
  "lang": "py",
  "cat": "FastAPI",
  "stage": "阶段A",
  "name": "路径参数 / 查询参数 / 默认值",
  "brief": "路径里的用 `{}`，问号后面的自动变函数参数",
  "code": "from fastapi import FastAPI\nfrom fastapi.testclient import TestClient\napp = FastAPI()\n@app.get(\"/search\")\ndef search(q: str, limit: int = 5, exact: bool = False):\n    return {\"查\": q, \"限制\": limit, \"精确\": exact}\nc = TestClient(app)\nprint(\"/search?q=助餐            →\", c.get(\"/search\", params={\"q\": \"助餐\"}).json())\nprint(\"/search?q=助餐&limit=2    →\", c.get(\"/search\", params={\"q\": \"助餐\", \"limit\": 2}).json())\nprint(\"不传 q（必填）→ 状态码\", c.get(\"/search\").status_code)",
  "where": "所有带筛选/分页的接口",
  "gotcha": "**`limit: int = 5` 写在函数签名里就同时完成了三件事**：类型转换、校验、默认值 —— 这就是 FastAPI 的价值。不写默认值 = 必填，不传就 422",
  "extra": "",
  "err": false,
  "verify": null,
  "out": "/search?q=助餐            → {'查': '助餐', '限制': 5, '精确': False}\n/search?q=助餐&limit=2    → {'查': '助餐', '限制': 2, '精确': False}\n不传 q（必填）→ 状态码 422",
  "ok": true
 },
 {
  "id": "fa.uvicorn",
  "lang": "py",
  "cat": "FastAPI",
  "stage": "阶段A",
  "name": "把它跑起来（以及线上怎么跑）",
  "brief": "`uvicorn` 是服务器；本机开发带 reload，线上不带",
  "code": "import uvicorn\ncfg = uvicorn.Config(\"main:app\", host=\"127.0.0.1\", port=8009, reload=False)\nprint(\"host =\", cfg.host, \"| port =\", cfg.port, \"| reload =\", cfg.reload)\nprint(\"app  =\", cfg.app)\nprint(\"（真启动的命令见卡片下方说明；别在脚本里 run —— 会占住终端）\")",
  "where": "你服务器上 8009 端口 + Docker 跑的就是它",
  "gotcha": "⚠️ `uvicorn.run(...)` **会阻塞住当前进程**（一直跑服务器），所以它只该出现在`if __name__ == \"__main__\":` 里 —— 否则你 import 这个模块时测试就卡死了。线上要关掉 `reload`（它靠监控文件变化工作，占资源且不安全）",
  "extra": "开发时：`uvicorn main:app --reload --port 8009`　｜　线上：`uvicorn main:app --host 0.0.0.0 --port 8009`（去掉 reload）",
  "err": false,
  "verify": null,
  "out": "host = 127.0.0.1 | port = 8009 | reload = False\napp  = main:app\n（真启动的命令见卡片下方说明；别在脚本里 run —— 会占住终端）",
  "ok": true
 },
 {
  "id": "fa.stream",
  "lang": "py",
  "cat": "FastAPI",
  "stage": "阶段A",
  "name": "流式返回：把模型的字一个个传给前端",
  "brief": "`StreamingResponse` + 生成器；配 `llm.stream` 就是「AI 边写边显示」",
  "code": "from fastapi import FastAPI\nfrom fastapi.responses import StreamingResponse\nfrom fastapi.testclient import TestClient\napp = FastAPI()\ndef gen():\n    for piece in [\"数据\", \"库\", \"很\", \"有用\"]:\n        yield piece\n@app.get(\"/chat\")\ndef chat():\n    return StreamingResponse(gen(), media_type=\"text/plain; charset=utf-8\")\nr = TestClient(app).get(\"/chat\")\nprint(\"状态码 =\", r.status_code, \"| Content-Type =\", r.headers[\"content-type\"])\nprint(\"拼起来 =\", r.text)",
  "where": "做 AI 聊天界面的必备件（否则用户要等整段生成完才看到字）",
  "gotcha": "**生成器里 `yield` 的是字符串/字节，不能 yield dict**。而且流式一开，就没法再改状态码了 —— 出错只能在流里发一个约定的错误标记",
  "extra": "",
  "err": false,
  "verify": null,
  "out": "状态码 = 200 | Content-Type = text/plain; charset=utf-8\n拼起来 = 数据库很有用",
  "ok": true
 }
];
