/* 自动生成 —— 不要手改这个文件！
   事实源：tools/build_fn_cards.py（卡片文字 + 示例代码）
   这里是它真跑一遍之后的输出，每张卡带 ok / out 两个字段。
   重跑：python tools/build_fn_cards.py */
window.LAB_FN_CARDS = [
 {
  "id": "sql.skeleton",
  "lang": "sql",
  "cat": "SQL",
  "stage": "本周",
  "name": "SELECT … FROM …",
  "brief": "所有查询的骨架：先说「要哪几列」，再说「从哪张表」",
  "code": "SELECT name, class FROM students;",
  "where": "第3课① · 任何一条 SQL 都长这样",
  "gotcha": "`SELECT *` 能跑但别常用 —— 列的顺序以后会变，代码会悄悄错位",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "name | class  \n-----+--------\n韩立 | 讯飞班 \n小明 | 讯飞班 \n小红 | 计科1班\n小刚 | 计科1班\n小美 | 计科1班\n（5 行）",
  "ok": true
 },
 {
  "id": "sql.where",
  "lang": "sql",
  "cat": "SQL",
  "stage": "本周",
  "name": "WHERE",
  "brief": "先在脑子里选出全部，再一条条筛掉不要的",
  "code": "SELECT name, class FROM students WHERE class = '讯飞班';",
  "where": "第3课 · 筛选；D8 作业至少要用一次",
  "gotcha": "筛完只剩 2 行不是因为「表里只有 2 行」，是 WHERE 把它们筛掉了",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "name | class \n-----+-------\n韩立 | 讯飞班\n小明 | 讯飞班\n（2 行）",
  "ok": true
 },
 {
  "id": "sql.on_vs_where",
  "lang": "sql",
  "cat": "SQL",
  "stage": "本周",
  "name": "ON / WHERE 分工",
  "brief": "ON = 怎么配对（横着拼），WHERE = 要哪些（竖着筛）",
  "code": "SELECT s.name, e.cid\nFROM students s\nJOIN enrollments e ON s.id = e.sid\nWHERE e.cid = 1;",
  "where": "第3课④ · 全课最该分清的一对",
  "gotcha": "把 `e.cid = 1` 挪到 ON 里，INNER JOIN 结果一样 —— 但换成 LEFT JOIN 就天差地别（留在 ON 里 = 右表筛完再拼，放 WHERE 里 = 拼完再筛，会把 NULL 行筛掉）",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "name | cid\n-----+----\n韩立 | 1  \n小明 | 1  \n（2 行）",
  "ok": true
 },
 {
  "id": "sql.order_by",
  "lang": "sql",
  "cat": "SQL",
  "stage": "本月",
  "name": "ORDER BY",
  "brief": "排序；默认升序，DESC 反过来",
  "code": "SELECT s.name, e.grade\nFROM enrollments e JOIN students s ON s.id = e.sid\nORDER BY e.grade DESC;",
  "where": "出榜单 / 看最大的那个",
  "gotcha": "NULL 在 SQLite 里排在最前（DESC 时排最后）—— 想让它垫底要写 `ORDER BY grade IS NULL, grade DESC`",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "name | grade\n-----+------\n小明 | 92.0 \n韩立 | 88.5 \n小明 | 81.0 \n韩立 | 76.0 \n小红 | 59.0 \n小刚 | NULL \n（6 行）",
  "ok": true
 },
 {
  "id": "sql.limit",
  "lang": "sql",
  "cat": "SQL",
  "stage": "本月",
  "name": "LIMIT / OFFSET",
  "brief": "只要前 N 条 / 跳过前 N 条（分页就靠它）",
  "code": "SELECT name, credit FROM courses ORDER BY credit DESC LIMIT 2;",
  "where": "Top-N 排行榜；翻页",
  "gotcha": "`LIMIT` 没有 `ORDER BY` 时顺序是**未定义**的 —— 每次跑可能不一样",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "name   | credit\n-------+-------\n高数   | 5     \n数据库 | 3     \n（2 行）",
  "ok": true
 },
 {
  "id": "sql.distinct",
  "lang": "sql",
  "cat": "SQL",
  "stage": "本月",
  "name": "DISTINCT",
  "brief": "一行里多个列都相同才算重复，去重后只剩一种",
  "code": "SELECT DISTINCT class FROM students;",
  "where": "「有几种」而不是「有几条」",
  "gotcha": "`COUNT(DISTINCT 列)` 才是「数几种」；`COUNT(*)` 数的是行数",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "class  \n-------\n讯飞班 \n计科1班\n（2 行）",
  "ok": true
 },
 {
  "id": "sql.and_or",
  "lang": "sql",
  "cat": "SQL",
  "stage": "本月",
  "name": "AND / OR 的优先级",
  "brief": "AND 比 OR 先算 —— 所以 OR 两边一定要加括号",
  "code": "SELECT name, class FROM students\nWHERE (class = '讯飞班' OR class = '计科1班') AND name <> '小红';",
  "where": "多条件筛选",
  "gotcha": "不加括号会变成「讯飞班的人，或者（计科1班且不叫小红的人）」—— 结果多出来的人你还不一定看得出来",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "name | class  \n-----+--------\n韩立 | 讯飞班 \n小明 | 讯飞班 \n小刚 | 计科1班\n小美 | 计科1班\n（4 行）",
  "ok": true
 },
 {
  "id": "sql.in",
  "lang": "sql",
  "cat": "SQL",
  "stage": "本月",
  "name": "IN",
  "brief": "一个字段对一串值，比写一堆 OR 干净",
  "code": "SELECT name FROM students WHERE class IN ('讯飞班', '计科1班');",
  "where": "按一批 id 批量查（爬虫/接口返回的 id 列表）",
  "gotcha": "`NOT IN` 遇到 NULL 会整体变空 —— 子查询里可能有 NULL 时别用",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "name\n----\n韩立\n小明\n小红\n小刚\n小美\n（5 行）",
  "ok": true
 },
 {
  "id": "sql.between",
  "lang": "sql",
  "cat": "SQL",
  "stage": "本月",
  "name": "BETWEEN",
  "brief": "区间筛选，**两头都算在内**",
  "code": "SELECT name, credit FROM courses WHERE credit BETWEEN 2 AND 5;",
  "where": "按时间/分数区间查",
  "gotcha": "`BETWEEN 2 AND 5` = `>= 2 AND <= 5`（含 5）—— 差一个边界是常见 off-by-one",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "name     | credit\n---------+-------\n数据库   | 3     \n高数     | 5     \n机器学习 | 2     \n英语     | 2     \n（4 行）",
  "ok": true
 },
 {
  "id": "sql.like",
  "lang": "sql",
  "cat": "SQL",
  "stage": "本月",
  "name": "LIKE 通配",
  "brief": "`%` = 任意多个字符，`_` = 正好一个字符",
  "code": "SELECT id, name FROM courses WHERE name LIKE '_数';",
  "where": "模糊搜索 / 清洗数据时找脏值",
  "gotcha": "SQLite 的 LIKE 对 ASCII **大小写不敏感**，对中文当然无所谓 —— 但换成 PostgreSQL 就敏感了",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "id | name\n---+-----\n2  | 高数\n（1 行）",
  "ok": true
 },
 {
  "id": "sql.count",
  "lang": "sql",
  "cat": "SQL",
  "stage": "本周",
  "name": "COUNT(*) / COUNT(列)",
  "brief": "COUNT(*) 数行；COUNT(列) 只数**这一列不是 NULL** 的行",
  "code": "SELECT COUNT(*) AS rows_all, COUNT(grade) AS rows_graded FROM enrollments;",
  "where": "第3课⑥ 诊断第一步：单独数绳子表",
  "gotcha": "两者不一样就说明这列有 NULL —— 这个差值本身就是线索，不是 bug",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "rows_all | rows_graded\n---------+------------\n6        | 5          \n（1 行）",
  "ok": true
 },
 {
  "id": "sql.count_distinct",
  "lang": "sql",
  "cat": "SQL",
  "stage": "本月",
  "name": "COUNT(DISTINCT 列)",
  "brief": "数「有几种」，不是「有几条」",
  "code": "SELECT COUNT(*) AS rows_all, COUNT(DISTINCT cid) AS kinds FROM enrollments;",
  "where": "统计去重后的数量（多少门课被选过）",
  "gotcha": "`COUNT(DISTINCT a, b)` 在 SQLite 里是**语法错误**，多列去重得用子查询",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "rows_all | kinds\n---------+------\n6        | 5    \n（1 行）",
  "ok": true
 },
 {
  "id": "sql.aggregate",
  "lang": "sql",
  "cat": "SQL",
  "stage": "本月",
  "name": "SUM / AVG / MIN / MAX / ROUND",
  "brief": "五个聚合函数，NULL 一律不参与计算",
  "code": "SELECT ROUND(AVG(grade), 1) AS avg_g, MAX(grade) AS top, MIN(grade) AS low\nFROM enrollments WHERE grade IS NOT NULL;",
  "where": "算总分/均分；第7章预习要用",
  "gotcha": "`AVG` 忽略 NULL，所以分母是「有分数的行数」而不是总行数 —— 拿不准就先 `COUNT(*)` 和 `COUNT(列)` 都打出来看",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "avg_g | top  | low \n------+------+-----\n79.3  | 92.0 | 59.0\n（1 行）",
  "ok": true
 },
 {
  "id": "sql.group_by",
  "lang": "sql",
  "cat": "SQL",
  "stage": "本月",
  "name": "GROUP BY",
  "brief": "把行按某列分成堆，每堆出一行（聚合函数的分母就变成「这一堆」）",
  "code": "SELECT cid, COUNT(*) AS n FROM enrollments GROUP BY cid ORDER BY n DESC;",
  "where": "第7章预习 · 每个群的成员数这种「分堆统计」",
  "gotcha": "SELECT 里只能出现**分组列 + 聚合函数**，出现别的列时 SQLite 不报错但会随便挑一行给你（别的数据库直接报错）",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "cid | n\n----+--\n1   | 2\n5   | 1\n4   | 1\n3   | 1\n2   | 1\n（5 行）",
  "ok": true
 },
 {
  "id": "sql.having",
  "lang": "sql",
  "cat": "SQL",
  "stage": "本月",
  "name": "HAVING",
  "brief": "筛「堆」。WHERE 筛行、发生在分组前，HAVING 筛堆、发生在分组后",
  "code": "SELECT cid, COUNT(*) AS n FROM enrollments GROUP BY cid HAVING COUNT(*) > 1;",
  "where": "第7章预习 · 「选课人数 > 1 的课」",
  "gotcha": "写成 `WHERE COUNT(*) > 1` 会直接报错 —— 因为 WHERE 执行时还没分组，没有「每堆」这个概念",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "cid | n\n----+--\n1   | 2\n（1 行）",
  "ok": true
 },
 {
  "id": "sql.where_aggregate_err",
  "lang": "sql",
  "cat": "SQL",
  "stage": "本月",
  "name": "坑：WHERE 里用聚合函数",
  "brief": "WHERE 比 GROUP BY 先执行，所以它根本看不到 COUNT(*)",
  "code": "SELECT cid FROM enrollments WHERE COUNT(*) > 1 GROUP BY cid;",
  "where": "报错现场",
  "gotcha": "看到 `misuse of aggregate function` 就一个动作：把条件从 WHERE 挪到 HAVING",
  "verify": null,
  "err": true,
  "extra": "",
  "out": "OperationalError: misuse of aggregate: COUNT()",
  "ok": false
 },
 {
  "id": "sql.coalesce",
  "lang": "sql",
  "cat": "SQL",
  "stage": "本月",
  "name": "IFNULL / COALESCE",
  "brief": "NULL 换个默认值再显示（NULL 参与算术会让整行变 NULL）",
  "code": "SELECT sid, cid, IFNULL(grade, 0) AS grade FROM enrollments;",
  "where": "配 LEFT JOIN 用：没匹配上的那侧全是 NULL",
  "gotcha": "别用 `IFNULL(grade,0)` 去「修」平均值 —— 用 0 冒充「没考」会把均分拉低，该用 `WHERE grade IS NOT NULL`",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "sid | cid | grade\n----+-----+------\n1   | 1   | 88.5 \n1   | 2   | 76.0 \n2   | 1   | 92.0 \n2   | 3   | 81.0 \n3   | 5   | 59.0 \n4   | 4   | 0    \n（6 行）",
  "ok": true
 },
 {
  "id": "sql.null_eq_trap",
  "lang": "sql",
  "cat": "SQL",
  "stage": "本月",
  "name": "坑：`= NULL` 永远查不出东西",
  "brief": "NULL 的意思是「不知道」，所以「等不等于不知道」的答案是「我也不知道」",
  "code": "SELECT sid, cid FROM enrollments WHERE grade = NULL;",
  "where": "查「没填的那几条」时最常踩",
  "gotcha": "要判 NULL 只能用 `IS NULL` / `IS NOT NULL` —— 这个坑**不报错、只是静默返回 0 行**",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "sid | cid\n----+----\n（0 行）",
  "ok": true
 },
 {
  "id": "sql.is_null",
  "lang": "sql",
  "cat": "SQL",
  "stage": "本月",
  "name": "IS NULL / IS NOT NULL",
  "brief": "判断「这格是不是空的」唯一正确写法",
  "code": "SELECT sid, cid FROM enrollments WHERE grade IS NULL;",
  "where": "找脏数据 / 找漏填的记录",
  "gotcha": "反过来记住：`WHERE grade <> 80` **也不会**把 NULL 的行选出来（NULL 不满足任何比较）",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "sid | cid\n----+----\n4   | 4  \n（1 行）",
  "ok": true
 },
 {
  "id": "sql.case_when",
  "lang": "sql",
  "cat": "SQL",
  "stage": "以后",
  "name": "CASE WHEN",
  "brief": "SQL 里的 if-else，可以放在 SELECT 里造一个新列",
  "code": "SELECT name, CASE WHEN credit >= 3 THEN 'major' ELSE 'minor' END AS weight\nFROM courses;",
  "where": "给数据打标签（分数段/等级），打标后直接喂给模型",
  "gotcha": "不写 `ELSE` 时默认是 NULL，不是原值",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "name     | weight\n---------+-------\n数据库   | major \n高数     | major \n机器学习 | minor \n体育     | minor \n英语     | minor \n（5 行）",
  "ok": true
 },
 {
  "id": "sql.cast",
  "lang": "sql",
  "cat": "SQL",
  "stage": "以后",
  "name": "CAST",
  "brief": "改类型。SQLite 类型松，但拼接/比较时该转还得转",
  "code": "SELECT CAST('42' AS INTEGER) + 1 AS n, CAST(3.7 AS INTEGER) AS i;",
  "where": "从文本里提出来的数字要参与计算时",
  "gotcha": "`CAST(3.7 AS INTEGER)` 是**截断**不是四舍五入（得 3）；要四舍五入用 `ROUND`",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "n  | i\n---+--\n43 | 3\n（1 行）",
  "ok": true
 },
 {
  "id": "sql.string_fn",
  "lang": "sql",
  "cat": "SQL",
  "stage": "以后",
  "name": "UPPER / LOWER / LENGTH",
  "brief": "大小写与长度。注意 LENGTH 数的是**字符**，不是字节",
  "code": "SELECT UPPER('abc') AS u, LOWER('ABC') AS l, LENGTH('数据库') AS n;",
  "where": "数据清洗；校验字段长度",
  "gotcha": "`LENGTH('数据库')` = 3（SQLite 数字符），但 `LENGTH(CAST('数据库' AS BLOB))` = 9 —— 中文是 3 字节",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "u   | l   | n\n----+-----+--\nABC | abc | 3\n（1 行）",
  "ok": true
 },
 {
  "id": "sql.substr_replace",
  "lang": "sql",
  "cat": "SQL",
  "stage": "以后",
  "name": "SUBSTR / REPLACE / TRIM",
  "brief": "截取、替换、去首尾空格 —— 清洗三件套",
  "code": "SELECT SUBSTR('2026-09-24', 1, 4) AS y, REPLACE('a-b', '-', '/') AS r, TRIM('  x  ') AS t;",
  "where": "日志/网页文本清洗",
  "gotcha": "SQLite 的 `SUBSTR` 下标**从 1 开始**（Python 从 0 开始），`SUBSTR(s, 1, 4)` 才是钱 4 个字符",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "y    | r   | t\n-----+-----+--\n2026 | a/b | x\n（1 行）",
  "ok": true
 },
 {
  "id": "sql.date_fn",
  "lang": "sql",
  "cat": "SQL",
  "stage": "以后",
  "name": "date('now') / strftime",
  "brief": "SQLite 没有专门的日期类型，日期就是文本，靠这些函数算",
  "code": "SELECT date('now') AS today, strftime('%Y-%m', 'now') AS ym,\n       CAST(julianday('now') - julianday('2026-09-21') AS INTEGER) AS days;",
  "where": "按天统计；算「距今几天」",
  "gotcha": "`date('now')` 取的是 **UTC** —— 想按北京时间算要写 `date('now','+8 hours')`",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "today      | ym      | days\n-----------+---------+-----\n2026-09-23 | 2026-09 | 2   \n（1 行）",
  "ok": true
 },
 {
  "id": "sql.group_concat",
  "lang": "sql",
  "cat": "SQL",
  "stage": "以后",
  "name": "GROUP_CONCAT",
  "brief": "把一堆行的某列拼成一个字符串（默认用逗号）",
  "code": "SELECT cid, GROUP_CONCAT(sid) AS sids FROM enrollments GROUP BY cid;",
  "where": "「这个群都有谁」 —— 一行拿到全部成员",
  "gotcha": "拼接顺序不保证；要固定顺序得先在外面排序（SQLite 3.44+ 才支持 `GROUP_CONCAT(x ORDER BY y)`）",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "cid | sids\n----+-----\n1   | 1,2 \n2   | 1   \n3   | 2   \n4   | 4   \n5   | 3   \n（5 行）",
  "ok": true
 },
 {
  "id": "sql.join2",
  "lang": "sql",
  "cat": "SQL",
  "stage": "本周",
  "name": "JOIN … ON（两表）",
  "brief": "拿一边的 id 去另一边配对，配对成功才出一行",
  "code": "SELECT s.name, e.cid\nFROM students s\nJOIN enrollments e ON s.id = e.sid;",
  "where": "第3课④ · 本课核心",
  "gotcha": "结果行数 = **配对成功的次数**，不是任何一张表的行数",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "name | cid\n-----+----\n韩立 | 1  \n韩立 | 2  \n小明 | 1  \n小明 | 3  \n小红 | 5  \n小刚 | 4  \n（6 行）",
  "ok": true
 },
 {
  "id": "sql.join3",
  "lang": "sql",
  "cat": "SQL",
  "stage": "本周",
  "name": "三表 JOIN（中间那张是「绳子」）",
  "brief": "行数由中间那张绳子表说了算；两头都只是「换名字」",
  "code": "SELECT s.name AS student, c.name AS course, e.grade\nFROM students s\nJOIN enrollments e ON s.id = e.sid\nJOIN courses     c ON e.cid = c.id;",
  "where": "第3课④ · 第6章换皮就是把它改名",
  "gotcha": "三张表的顺序可以换，但**每一句 ON 必须紧跟着它要拼的那张表**",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "student | course   | grade\n--------+----------+------\n韩立    | 数据库   | 88.5 \n韩立    | 高数     | 76.0 \n小明    | 数据库   | 92.0 \n小明    | 机器学习 | 81.0 \n小红    | 英语     | 59.0 \n小刚    | 体育     | NULL \n（6 行）",
  "ok": true
 },
 {
  "id": "sql.join_alias",
  "lang": "sql",
  "cat": "SQL",
  "stage": "本周",
  "name": "坑：两边都有 id，不给表起别名",
  "brief": "两张表都有 `id` 列时，`ON students.id = courses.id` 里的 id 到底是谁的？",
  "code": "SELECT id, name FROM students JOIN courses ON students.id = courses.id;",
  "where": "报错现场 —— 别名就是为了解决它",
  "gotcha": "`ambiguous column name` 的正确解法是给表起别名然后写全：`s.id`、`c.id`",
  "verify": null,
  "err": true,
  "extra": "",
  "out": "OperationalError: ambiguous column name: id",
  "ok": false
 },
 {
  "id": "sql.join_wrong_zero",
  "lang": "sql",
  "cat": "SQL",
  "stage": "本周",
  "name": "坑①：ON 接反 → 0 行（不报错）",
  "brief": "groups.id 是 1/2/3，group_members.uid 是 7/9/7 —— 一个都对不上",
  "code": "SELECT persons.name AS person, groups.name AS grp\nFROM groups\nJOIN group_members ON groups.id = group_members.uid\nJOIN persons       ON group_members.gid = persons.id;",
  "where": "第3课④ 实测反例 1（低危：空的一眼看得出来）",
  "gotcha": "**JOIN 查出空表时的第一反应应该是「怀疑 ON」，而不是「数据没了」**",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "person | grp\n-------+----\n（0 行）",
  "ok": true
 },
 {
  "id": "sql.join_wrong_fake",
  "lang": "sql",
  "cat": "SQL",
  "stage": "本周",
  "name": "坑②：id 重叠 → 照样出数据（最危险）",
  "brief": "students.id 和 courses.id 都从 1 开始，接反了照样配得上 —— 于是给你一张看着完全合理的假表",
  "code": "SELECT s.name AS student, c.name AS course\nFROM students s\nJOIN enrollments e ON s.id = e.cid\nJOIN courses     c ON e.sid = c.id;",
  "where": "第3课④ 实测反例 2（🔴 高危：静默错误）",
  "gotcha": "「不为空」**绝不等于**「对」。唯一的防线是**挑一行人工核对内容**——这张表里有**根本没选课的小美**、还有对不上课的小红，一眼就能看出不对",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "student | course  \n--------+---------\n韩立    | 数据库  \n小明    | 数据库  \n韩立    | 高数    \n小红    | 高数    \n小美    | 机器学习\n小刚    | 体育    \n（6 行）",
  "ok": true
 },
 {
  "id": "sql.fake_proof",
  "lang": "sql",
  "cat": "SQL",
  "stage": "本周",
  "name": "证明它到底错在哪：行数一样，内容不同",
  "brief": "同一批数据，正确写法和接反写法**都出 6 行**；真正差的是其中 2 行的内容",
  "code": "SELECT\n (SELECT COUNT(*) FROM (\n    SELECT s.name, c.name FROM students s\n      JOIN enrollments e ON s.id = e.sid JOIN courses c ON e.cid = c.id\n    EXCEPT\n    SELECT s.name, c.name FROM students s\n      JOIN enrollments e ON s.id = e.cid JOIN courses c ON e.sid = c.id\n )) AS missing_in_wrong,\n (SELECT COUNT(*) FROM (\n    SELECT s.name, c.name FROM students s\n      JOIN enrollments e ON s.id = e.cid JOIN courses c ON e.sid = c.id\n    EXCEPT\n    SELECT s.name, c.name FROM students s\n      JOIN enrollments e ON s.id = e.sid JOIN courses c ON e.cid = c.id\n )) AS rows_that_are_fake;",
  "where": "第3课④ 那张假数据卡的下半句 —— 用 SQL 自己证明",
  "gotcha": "左边 = 正确结果里有、接反结果里没有的（**漏了 2 行**）；右边 = 接反结果凭空多出来的（**假了 2 行**）。⇒ 只数行数永远发现不了，必须看内容",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "missing_in_wrong | rows_that_are_fake\n-----------------+-------------------\n2                | 2                 \n（1 行）",
  "ok": true
 },
 {
  "id": "sql.diagnose",
  "lang": "sql",
  "cat": "SQL",
  "stage": "本周",
  "name": "诊断三步：先数绳子，再数结果",
  "brief": "① 单独数绳子表 ② 数 JOIN 结果 ③ 两数一致不算过关，再挑一行核对内容",
  "code": "SELECT (SELECT COUNT(*) FROM enrollments) AS rope_rows,\n       (SELECT COUNT(*) FROM students s JOIN enrollments e ON s.id = e.sid) AS join_rows;",
  "where": "第3课⑥ · 本课最实用的迁移技能",
  "gotcha": "数字对不上（空 / 多很多）→ 几乎一定是 ON；数字**对得上**也可能内容错（id 重叠时）",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "rope_rows | join_rows\n----------+----------\n6         | 6        \n（1 行）",
  "ok": true
 },
 {
  "id": "sql.left_join",
  "lang": "sql",
  "cat": "SQL",
  "stage": "本周",
  "name": "LEFT JOIN",
  "brief": "左表一行都不能丢；右表配不上就整行填 NULL",
  "code": "SELECT s.name, e.cid, e.grade\nFROM students s LEFT JOIN enrollments e ON s.id = e.sid;",
  "where": "第3课⑤ 换皮3 · 统计时最常见",
  "gotcha": "把 `LEFT` 去掉，**没选课的人会整个消失** —— 人数从 5 变 4，而且不报错",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "name | cid  | grade\n-----+------+------\n韩立 | 1    | 88.5 \n韩立 | 2    | 76.0 \n小明 | 1    | 92.0 \n小明 | 3    | 81.0 \n小红 | 5    | 59.0 \n小刚 | 4    | NULL \n小美 | NULL | NULL \n（7 行）",
  "ok": true
 },
 {
  "id": "sql.inner_vs_left",
  "lang": "sql",
  "cat": "SQL",
  "stage": "本周",
  "name": "INNER vs LEFT：差在哪一行",
  "brief": "同一条查询，只差 `LEFT` 四个字母，结果少一行",
  "code": "SELECT s.name FROM students s JOIN enrollments e ON s.id = e.sid;",
  "where": "对照上一张卡看：5 个人变成了 4 个人，小美没了",
  "gotcha": "要「一个都不漏」的清单（点名、对账、覆盖率）时必须 LEFT",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "name\n----\n韩立\n韩立\n小明\n小明\n小红\n小刚\n（6 行）",
  "ok": true
 },
 {
  "id": "sql.subquery",
  "lang": "sql",
  "cat": "SQL",
  "stage": "以后",
  "name": "子查询",
  "brief": "把一条 SELECT 的结果当另一条的条件用",
  "code": "SELECT name FROM courses\nWHERE id IN (SELECT cid FROM enrollments WHERE grade > 85);",
  "where": "两步查询懒得写两遍时",
  "gotcha": "`IN (子查询)` 里如果出现 NULL，`NOT IN` 会整体返回空 —— 拿不准就用 `EXISTS`",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "name  \n------\n数据库\n（1 行）",
  "ok": true
 },
 {
  "id": "sql.union",
  "lang": "sql",
  "cat": "SQL",
  "stage": "以后",
  "name": "UNION",
  "brief": "上下摞两条结果集；UNION 去重，UNION ALL 不去重（也更快）",
  "code": "SELECT name FROM students WHERE class = '讯飞班'\nUNION\nSELECT name FROM students WHERE id <= 3;",
  "where": "合并两张结构相同的表（比如两个月的日志）",
  "gotcha": "两边**列数必须一样**，列名以第一条为准 —— 列对不齐时不报错，只会悄悄错位",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "name\n----\n小明\n小红\n韩立\n（3 行）",
  "ok": true
 },
 {
  "id": "sql.tables",
  "lang": "sql",
  "cat": "SQL",
  "stage": "本周",
  "name": "看这个库有哪些表",
  "brief": "不用装数据库工具，一条 SQL 就能看清家底",
  "code": "SELECT name FROM sqlite_master WHERE type = 'table' ORDER BY name;",
  "where": "第3课① 「这库里一共几张表」那道题的正确做法",
  "gotcha": "`sqlite_master` 是 SQLite 专有；MySQL 里叫 `SHOW TABLES`",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "name         \n-------------\ncourses      \nenrollments  \ngroup_members\ngroups       \npersons      \nstudents     \n（6 行）",
  "ok": true
 },
 {
  "id": "sql.pragma",
  "lang": "sql",
  "cat": "SQL",
  "stage": "本周",
  "name": "看一张表的结构",
  "brief": "列名、类型、是否主键，一条 PRAGMA 全给你",
  "code": "PRAGMA table_info(enrollments);",
  "where": "忘了列名时先看这个，别猜",
  "gotcha": "`PRAGMA` 不是标准 SQL（且不吃 `?` 占位符）—— 表名只能拼字符串，只用于自己写死的表名",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "cid | name  | type    | notnull | dflt_value | pk\n----+-------+---------+---------+------------+---\n0   | sid   | INTEGER | 0       | NULL       | 0 \n1   | cid   | INTEGER | 0       | NULL       | 0 \n2   | grade | REAL    | 0       | NULL       | 0 \n（3 行）",
  "ok": true
 },
 {
  "id": "sql.create_table",
  "lang": "sql",
  "cat": "SQL",
  "stage": "本周",
  "name": "CREATE TABLE",
  "brief": "并列三件事：列定义、主键、外键约束",
  "code": "CREATE TABLE enrollments_new (\n    sid   INTEGER NOT NULL REFERENCES students(id),\n    cid   INTEGER NOT NULL REFERENCES courses(id),\n    grade REAL,\n    PRIMARY KEY (sid, cid)\n);",
  "where": "第3课③ · D8 作业的第一件事",
  "gotcha": "**复合主键** `PRIMARY KEY (sid, cid)` 直接防住「同一个人重复选同一门课」—— 比在 Python 里查一遍再插可靠",
  "verify": "PRAGMA table_info(enrollments_new);",
  "err": false,
  "extra": "",
  "out": "cid | name  | type    | notnull | dflt_value | pk\n----+-------+---------+---------+------------+---\n0   | sid   | INTEGER | 1       | NULL       | 1 \n1   | cid   | INTEGER | 1       | NULL       | 2 \n2   | grade | REAL    | 0       | NULL       | 0 \n（3 行）",
  "ok": true
 },
 {
  "id": "sql.insert",
  "lang": "sql",
  "cat": "SQL",
  "stage": "本周",
  "name": "INSERT INTO",
  "brief": "列名写全，值用 `?` 占位（Python 里）",
  "code": "INSERT INTO students (id, name, class) VALUES (6, '小七', '计科1班');",
  "where": "D8 作业：插 3 行数据",
  "gotcha": "列名和值**数量必须一致**，否则报 `table has N columns but M values were supplied`",
  "verify": "SELECT * FROM students WHERE id = 6;",
  "err": false,
  "extra": "",
  "out": "id | name | class  \n---+------+--------\n6  | 小七 | 计科1班\n（1 行）",
  "ok": true
 },
 {
  "id": "sql.update",
  "lang": "sql",
  "cat": "SQL",
  "stage": "本月",
  "name": "UPDATE … WHERE",
  "brief": "改数据。**没有 WHERE 就是改全表**（没有撤销）",
  "code": "UPDATE enrollments SET grade = 90 WHERE sid = 3 AND cid = 5;",
  "where": "补分数、改状态",
  "gotcha": "养成习惯：先把 `WHERE` 那段单拎出来 `SELECT` 一遍，确认命中行数，再改成 UPDATE",
  "verify": "SELECT sid, cid, grade FROM enrollments WHERE sid = 3 AND cid = 5;",
  "err": false,
  "extra": "",
  "out": "sid | cid | grade\n----+-----+------\n3   | 5   | 90.0 \n（1 行）",
  "ok": true
 },
 {
  "id": "sql.delete",
  "lang": "sql",
  "cat": "SQL",
  "stage": "本月",
  "name": "DELETE FROM … WHERE",
  "brief": "删行。同样：**没有 WHERE 就是清空整张表**",
  "code": "DELETE FROM students WHERE id = 5;",
  "where": "删脏数据",
  "gotcha": "删之前先 `SELECT COUNT(*)`；真删表用 `DROP TABLE`（连表结构一起没）",
  "verify": "SELECT COUNT(*) AS left_rows FROM students;",
  "err": false,
  "extra": "",
  "out": "left_rows\n---------\n4        \n（1 行）",
  "ok": true
 },
 {
  "id": "py.sqlite_skeleton",
  "lang": "py",
  "cat": "sqlite3",
  "stage": "本周",
  "name": "六行骨架：连接 → 游标 → 执行 → 取 → 关",
  "brief": "连 Python 和数据库的全部动作就这六行",
  "code": "import sqlite3\nconn = sqlite3.connect(\":memory:\")          # 文件路径；:memory: = 内存库\ncur  = conn.cursor()\ncur.execute(\"CREATE TABLE t (x)\")\ncur.execute(\"INSERT INTO t VALUES (1), (2)\")\nconn.commit()                               # 写操作必须 commit\nfor row in cur.execute(\"SELECT x FROM t\"):\n    print(row)\nconn.close()",
  "where": "第3课 · 所有 SQL 作业的外壳",
  "gotcha": "`commit()` 忘写的后果见下一张卡 —— 它和 `close()` 是**两件事**",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "(1,)\n(2,)",
  "ok": true
 },
 {
  "id": "py.sqlite_commit",
  "lang": "py",
  "cat": "sqlite3",
  "stage": "本周",
  "name": "commit() vs close()：谁在丢数据",
  "brief": "P-014 的实测：换一个连接去读，看数据还在不在",
  "code": "import sqlite3, tempfile, os, shutil\nd = tempfile.mkdtemp(); p = os.path.join(d, \"k.db\")\n\nc = sqlite3.connect(p); c.execute(\"CREATE TABLE t(x)\")\nc.execute(\"INSERT INTO t VALUES (1)\")\nc.close()                                   # 只 close，不 commit\nc2 = sqlite3.connect(p)\nprint(\"commit ✗ / close ✓  → 另一个连接读到\", c2.execute(\"SELECT COUNT(*) FROM t\").fetchone()[0], \"行\")\nc2.close()\n\nc = sqlite3.connect(p); c.execute(\"INSERT INTO t VALUES (2)\")\nc.commit(); c.close()                       # 先 commit，再 close\nc2 = sqlite3.connect(p)\nprint(\"commit ✓ / close ✓  → 另一个连接读到\", c2.execute(\"SELECT COUNT(*) FROM t\").fetchone()[0], \"行\")\nc2.close(); shutil.rmtree(d, ignore_errors=True)",
  "where": "第3课① 检索题（当场答错的那道）· P-014",
  "gotcha": "**丢数据的凶手是 `commit`，不是 `close`。** `close()` 忘写的代价是占资源（见下张卡），不是丢数据",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "commit ✗ / close ✓  → 另一个连接读到 0 行\ncommit ✓ / close ✓  → 另一个连接读到 1 行",
  "ok": true
 },
 {
  "id": "py.sqlite_close",
  "lang": "py",
  "cat": "sqlite3",
  "stage": "本周",
  "name": "close() 忘了写会怎样",
  "brief": "连接不关 → 文件被锁住 → 连删都删不掉",
  "code": "import sqlite3, tempfile, os, shutil\nd = tempfile.mkdtemp(); p = os.path.join(d, \"k.db\")\nc = sqlite3.connect(p); c.execute(\"CREATE TABLE t(x)\"); c.commit()\ntry:\n    os.remove(p)                            # 连接还开着，Windows 不让删\n    print(\"删掉了（没锁）\")\nexcept PermissionError as e:\n    print(\"PermissionError:\", e)\nc.close()\nos.remove(p)                                # 关掉之后再删就成功了\nprint(\"close 之后再删：成功\")\nshutil.rmtree(d, ignore_errors=True)",
  "where": "P-014 的另一半：close 的真实代价",
  "gotcha": "Linux/Mac 上删得掉，**只有 Windows 会当场报 `WinError 32`** —— 所以这个坑在 Windows 上反而更容易被发现",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'E:\\\\Temp\\\\tmpd_i50r_1\\\\k.db'\nclose 之后再删：成功",
  "ok": true
 },
 {
  "id": "py.sqlite_fetch",
  "lang": "py",
  "cat": "sqlite3",
  "stage": "本周",
  "name": "fetchone / fetchall / 直接遍历",
  "brief": "三种取结果的方式，选中一条就不可能再回头",
  "code": "import sqlite3\nconn = sqlite3.connect(\":memory:\")\nconn.execute(\"CREATE TABLE t(x)\")\nconn.executemany(\"INSERT INTO t VALUES (?)\", [(1,), (2,), (3,)])\ncur = conn.cursor()\ncur.execute(\"SELECT x FROM t\")\nprint(\"fetchone →\", cur.fetchone())         # 拿走第 1 行，游标前移\nprint(\"fetchall →\", cur.fetchall())         # 剩下的全拿走\ncur.execute(\"SELECT x FROM t\")\nprint(\"遍历     →\", [r[0] for r in cur])\nconn.close()",
  "where": "取查询结果",
  "gotcha": "游标是**一次性**的：`fetchone()` 之后再 `fetchall()` 拿不到已经取走的那行。要重复用就把结果存进 list",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "fetchone → (1,)\nfetchall → [(2,), (3,)]\n遍历     → [1, 2, 3]",
  "ok": true
 },
 {
  "id": "py.sqlite_executemany",
  "lang": "py",
  "cat": "sqlite3",
  "stage": "本周",
  "name": "executemany() 批量插入",
  "brief": "一次插 20 行，别写 20 条 execute",
  "code": "import sqlite3\nconn = sqlite3.connect(\":memory:\")\nconn.execute(\"CREATE TABLE s(name TEXT, score REAL)\")\nrows = [(\"小明\", 88.5), (\"小红\", 92.0), (\"小刚\", 76.5)]\nconn.executemany(\"INSERT INTO s VALUES (?, ?)\", rows)\nconn.commit()\nprint(conn.execute(\"SELECT COUNT(*) FROM s\").fetchone()[0], \"行\")\nfor r in conn.execute(\"SELECT * FROM s ORDER BY score DESC\"):\n    print(r)\nconn.close()",
  "where": "灌测试数据 / 批量写爬下来的数据",
  "gotcha": "参数是**一个可迭代对象**，每项对应一条语句；写成 `executemany(sql, (1,2))` 会把它当成两行单列",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "3 行\n('小红', 92.0)\n('小明', 88.5)\n('小刚', 76.5)",
  "ok": true
 },
 {
  "id": "py.sqlite_param",
  "lang": "py",
  "cat": "sqlite3",
  "stage": "本周",
  "name": "`?` 占位符（防注入）",
  "brief": "值永远走参数，不要用 f-string 拼进 SQL",
  "code": "import sqlite3\nconn = sqlite3.connect(\":memory:\")\nconn.execute(\"CREATE TABLE t(name TEXT)\"); conn.execute(\"INSERT INTO t VALUES ('小明')\")\nwho = \"小明' OR '1'='1\"                     # 想注入的人会这么输\nn = conn.execute(\"SELECT COUNT(*) FROM t WHERE name = ?\", (who,)).fetchone()[0]\nprint(\"参数化（对）→\", n, \"行\")\nbad = \"SELECT COUNT(*) FROM t WHERE name = '%s'\" % who\nn2 = conn.execute(bad).fetchone()[0]\nprint(\"拼字符串（错）→\", n2, \"行\")\nconn.close()",
  "where": "所有带用户输入的查询",
  "gotcha": "**单元素也必须写成 `(who,)`** —— 少了逗号 `(who)` 只是个字符串，会被当成一个可迭代对象逐字符拆开，报 `Incorrect number of bindings`",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "参数化（对）→ 0 行\n拼字符串（错）→ 1 行",
  "ok": true
 },
 {
  "id": "py.sqlite_row",
  "lang": "py",
  "cat": "sqlite3",
  "stage": "本周",
  "name": "row_factory：按列名取值",
  "brief": "设一次 `row_factory`，之后 `row['name']` 就能用",
  "code": "import sqlite3\nconn = sqlite3.connect(\":memory:\")\nconn.row_factory = sqlite3.Row          # ← 就这一行\nconn.execute(\"CREATE TABLE s(id INTEGER, name TEXT)\")\nconn.execute(\"INSERT INTO s VALUES (1, '小明')\")\nrow = conn.execute(\"SELECT id, name FROM s\").fetchone()\nprint(\"按下标 →\", row[0], row[1])\nprint(\"按列名 →\", row['id'], row['name'])\nprint(\"变字典 →\", dict(row))\nconn.close()",
  "where": "结果列一多，下标就记不住了",
  "gotcha": "`row_factory` 设在 **connection** 上，不是 cursor 上（设 cursor 上是另一套写法）",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "按下标 → 1 小明\n按列名 → 1 小明\n变字典 → {'id': 1, 'name': '小明'}",
  "ok": true
 },
 {
  "id": "py.sqlite_with",
  "lang": "py",
  "cat": "sqlite3",
  "stage": "以后",
  "name": "with：自动 commit / rollback",
  "brief": "`with conn:` 出块时自动提交，出异常自动回滚 —— 但**不会关连接**",
  "code": "import sqlite3\nconn = sqlite3.connect(\":memory:\")\nwith conn:                                  # 成功 → 自动 commit\n    conn.execute(\"CREATE TABLE t(x)\")\n    conn.execute(\"INSERT INTO t VALUES (1)\")\ntry:\n    with conn:                              # 失败 → 自动 rollback\n        conn.execute(\"INSERT INTO t VALUES (2)\")\n        raise ValueError(\"假装中途出错\")\nexcept ValueError as e:\n    print(\"捕获到：\", e)\nprint(\"表里剩\", conn.execute(\"SELECT COUNT(*) FROM t\").fetchone()[0], \"行\")\nconn.close()",
  "where": "写多步操作时不想每步都 commit",
  "gotcha": "`with conn:` ≠ `with sqlite3.connect() as conn:`。后者出块时**会关连接**，很多教程混着讲",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "捕获到： 假装中途出错\n表里剩 1 行",
  "ok": true
 },
 {
  "id": "py.sqlite_error",
  "lang": "py",
  "cat": "sqlite3",
  "stage": "以后",
  "name": "捕获数据库错误",
  "brief": "`IntegrityError` 是约束被违反，`OperationalError` 是表/列名写错",
  "code": "import sqlite3\nconn = sqlite3.connect(\":memory:\")\nconn.execute(\"CREATE TABLE s(id INTEGER PRIMARY KEY, name TEXT UNIQUE)\")\nconn.execute(\"INSERT INTO s VALUES (1, '小明')\")\ntry:\n    conn.execute(\"INSERT INTO s VALUES (2, '小明')\")   # name 重复\nexcept sqlite3.IntegrityError as e:\n    print(\"IntegrityError →\", e)\ntry:\n    conn.execute(\"SELECT * FROM 不存在的表\")\nexcept sqlite3.OperationalError as e:\n    print(\"OperationalError →\", e)\nconn.close()",
  "where": "爬虫/批量写数据时，重复行不该让整个程序崩",
  "gotcha": "两个异常都继承自 `sqlite3.Error`，图省事可以只 `except sqlite3.Error`；但**不要裸 `except:`** —— 会把键盘中断也吞掉",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "IntegrityError → UNIQUE constraint failed: s.name\nOperationalError → no such table: 不存在的表",
  "ok": true
 },
 {
  "id": "py.json_dumps",
  "lang": "py",
  "cat": "标准库",
  "stage": "本月",
  "name": "json.dumps",
  "brief": "Python 对象 → JSON 字符串（接口/存盘都用它）",
  "code": "import json\nd = {\"name\": \"韩立\", \"score\": 88.5, \"tags\": [\"python\", \"sql\"]}\nprint(json.dumps(d, ensure_ascii=False))\nprint(json.dumps(d, ensure_ascii=False, indent=2))",
  "where": "调大模型 API 的请求体；把结果存成文件",
  "gotcha": "`ensure_ascii=False` 不加，中文会变成 `\\u97e9\\u7acb` —— 能用但没法看",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "{\"name\": \"韩立\", \"score\": 88.5, \"tags\": [\"python\", \"sql\"]}\n{\n  \"name\": \"韩立\",\n  \"score\": 88.5,\n  \"tags\": [\n    \"python\",\n    \"sql\"\n  ]\n}",
  "ok": true
 },
 {
  "id": "py.json_loads",
  "lang": "py",
  "cat": "标准库",
  "stage": "本月",
  "name": "json.loads",
  "brief": "JSON 字符串 → Python 对象（大模型返回的就是个字符串）",
  "code": "import json\ns = '{\"answer\": 42, \"ok\": true, \"items\": [1, 2]}'\nd = json.loads(s)\nprint(type(d).__name__, d[\"answer\"], d[\"ok\"], d[\"items\"][1])\nprint(\"访问不存在的键 →\", end=\" \")\ntry:\n    d[\"nope\"]\nexcept KeyError as e:\n    print(\"KeyError\", e)",
  "where": "解析接口/大模型返回",
  "gotcha": "`loads` 吃字符串，`load` 吃文件对象 —— 差一个 s 是两种用法，报错信息很像（都叫 JSONDecodeError）",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "dict 42 True 2\n访问不存在的键 → KeyError 'nope'",
  "ok": true
 },
 {
  "id": "py.json_file",
  "lang": "py",
  "cat": "标准库",
  "stage": "本月",
  "name": "json.dump / json.load 直接读写文件",
  "brief": "省掉 open 那一步",
  "code": "import json, tempfile, os, shutil\nd = tempfile.mkdtemp(); p = os.path.join(d, \"out.json\")\nwith open(p, \"w\", encoding=\"utf-8\") as f:\n    json.dump({\"n\": 3, \"who\": \"韩立\"}, f, ensure_ascii=False)\nwith open(p, encoding=\"utf-8\") as f:\n    print(\"读回来 →\", json.load(f))\nshutil.rmtree(d, ignore_errors=True)",
  "where": "把中间结果存盘，下次不用重跑",
  "gotcha": "**一定要写 `encoding='utf-8'`** —— Windows 默认编码不是 utf-8，中文会乱码或直接 `UnicodeEncodeError`",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "读回来 → {'n': 3, 'who': '韩立'}",
  "ok": true
 },
 {
  "id": "py.open_read",
  "lang": "py",
  "cat": "标准库",
  "stage": "本月",
  "name": "with open(...) 读文件",
  "brief": "`with` 会自动关文件，不用手动 close",
  "code": "import tempfile, os, shutil\nd = tempfile.mkdtemp(); p = os.path.join(d, \"a.txt\")\nopen(p, \"w\", encoding=\"utf-8\").write(\"第一行\\n第二行\\n\")\nwith open(p, encoding=\"utf-8\") as f:\n    for i, line in enumerate(f, 1):\n        print(i, line.rstrip())          # rstrip 去掉行尾换行\nshutil.rmtree(d, ignore_errors=True)",
  "where": "读日志/读 txt 语料",
  "gotcha": "`line` 自带 `\\n`，直接 print 会多一个空行 —— 要么 `rstrip()`，要么 print 时加 `end=''`",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "1 第一行\n2 第二行",
  "ok": true
 },
 {
  "id": "py.open_write",
  "lang": "py",
  "cat": "标准库",
  "stage": "本月",
  "name": "open(..., 'w') 写文件",
  "brief": "`w` 覆盖、`a` 追加，都要显式写编码",
  "code": "import tempfile, os, shutil\nd = tempfile.mkdtemp(); p = os.path.join(d, \"log.txt\")\nwith open(p, \"w\", encoding=\"utf-8\") as f:\n    f.write(\"第一次\\n\")\nwith open(p, \"a\", encoding=\"utf-8\") as f:      # a = 追加，不会覆盖\n    f.write(\"第二次\\n\")\nprint(open(p, encoding=\"utf-8\").read().strip())\nshutil.rmtree(d, ignore_errors=True)",
  "where": "记运行日志 / 导出结果",
  "gotcha": "**`'w'` 会立刻清空原文件** —— 想追加却写了 `'w'`，上一次的结果就没了（且没有提示）",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "第一次\n第二次",
  "ok": true
 },
 {
  "id": "py.os_path",
  "lang": "py",
  "cat": "标准库",
  "stage": "本月",
  "name": "os.path.join / exists",
  "brief": "拼路径永远用 join，别手写 `+ '/' +`",
  "code": "import os\np = os.path.join(\"E:\\\\项目学习\", \"交互演示\", \"函数卡.html\")\nprint(p)\nprint(\"存在吗 →\", os.path.exists(p))\nprint(\"目录名 →\", os.path.dirname(p))\nprint(\"文件名 →\", os.path.basename(p))\nprint(\"扩展名 →\", os.path.splitext(p)[1])",
  "where": "所有涉及文件路径的代码",
  "gotcha": "`os.path.join('E:\\\\a', '/b')` 里第二个参数带开头的斜杠时，**前面的路径会被整个丢掉** —— 得到 `/b`",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "E:\\项目学习\\交互演示\\函数卡.html\n存在吗 → True\n目录名 → E:\\项目学习\\交互演示\n文件名 → 函数卡.html\n扩展名 → .html",
  "ok": true
 },
 {
  "id": "py.os_makedirs",
  "lang": "py",
  "cat": "标准库",
  "stage": "本月",
  "name": "os.makedirs(..., exist_ok=True)",
  "brief": "建多层目录；`exist_ok=True` 让「已存在」不报错",
  "code": "import os, tempfile, shutil\nd = tempfile.mkdtemp()\ntarget = os.path.join(d, \"导出\", \"2026-09\")\nos.makedirs(target, exist_ok=True)\nos.makedirs(target, exist_ok=True)          # 第二次不报错\nprint(\"建好了 →\", os.path.isdir(target))\nshutil.rmtree(d, ignore_errors=True)",
  "where": "写文件前确保目录存在（爬虫存图、导出报告）",
  "gotcha": "不写 `exist_ok=True`，跑第二遍就 `FileExistsError` —— 这是「只在第二次运行才炸」的经典 bug",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "建好了 → True",
  "ok": true
 },
 {
  "id": "py.os_listdir",
  "lang": "py",
  "cat": "标准库",
  "stage": "本月",
  "name": "os.listdir / glob 过滤",
  "brief": "列目录，再按后缀筛",
  "code": "import os, tempfile, shutil\nd = tempfile.mkdtemp()\nfor n in [\"a.txt\", \"b.txt\", \"c.csv\"]:\n    open(os.path.join(d, n), \"w\").close()\nnames = os.listdir(d)\nprint(\"全部 →\", sorted(names))\nprint(\"只要 txt →\", sorted(n for n in names if n.endswith(\".txt\")))\nshutil.rmtree(d, ignore_errors=True)",
  "where": "批量处理一个文件夹里的文件",
  "gotcha": "`listdir` 给的是**文件名**不是完整路径 —— 要打开它得再 `join` 一次（这是最常见的「文件找不到」原因）",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "全部 → ['a.txt', 'b.txt', 'c.csv']\n只要 txt → ['a.txt', 'b.txt']",
  "ok": true
 },
 {
  "id": "py.pathlib",
  "lang": "py",
  "cat": "标准库",
  "stage": "以后",
  "name": "pathlib.Path",
  "brief": "同一件事的现代写法：`/` 拼路径、`.suffix` 取后缀",
  "code": "from pathlib import Path\np = Path(\"E:/项目学习\") / \"交互演示\" / \"函数卡.html\"\nprint(p)\nprint(\"后缀 →\", p.suffix, \"｜ 名字 →\", p.stem, \"｜ 父目录 →\", p.parent.name)\nprint(\"存在吗 →\", p.exists(), \"｜ 是文件吗 →\", p.is_file())",
  "where": "新写的脚本（老代码里 os.path 也常见，两种都要能读）",
  "gotcha": "`Path` 对象不能直接丢给老函数当字符串用 —— 必要时 `str(p)`",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "E:\\项目学习\\交互演示\\函数卡.html\n后缀 → .html ｜ 名字 → 函数卡 ｜ 父目录 → 交互演示\n存在吗 → True ｜ 是文件吗 → True",
  "ok": true
 },
 {
  "id": "py.re_findall",
  "lang": "py",
  "cat": "标准库",
  "stage": "本月",
  "name": "re.findall",
  "brief": "在一段文本里捞出所有符合模式的片段",
  "code": "import re\ntext = \"订单 A1001 金额 88 元；订单 A1002 金额 192 元\"\nprint(\"所有订单号 →\", re.findall(r\"A\\d{4}\", text))\nprint(\"所有数字   →\", re.findall(r\"\\d+\", text))\nprint(\"成对取     →\", re.findall(r\"(A\\d{4}).*?(\\d+) 元\", text))",
  "where": "从网页/日志里提取字段",
  "gotcha": "模式字符串前面**一定要加 r**（原始字符串）—— 不加的话 `\\d` 会被 Python 先当成转义字符处理",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "所有订单号 → ['A1001', 'A1002']\n所有数字   → ['1001', '88', '1002', '192']\n成对取     → [('A1001', '88'), ('A1002', '192')]",
  "ok": true
 },
 {
  "id": "py.re_search",
  "lang": "py",
  "cat": "标准库",
  "stage": "本月",
  "name": "re.search + 分组",
  "brief": "只找第一个；用括号分组把想要的部分单独取出来",
  "code": "import re\nm = re.search(r\"(\\d{4})-(\\d{2})-(\\d{2})\", \"今天是 2026-09-24 周四\")\nif m:\n    print(\"整段 →\", m.group(0))\n    print(\"年 →\", m.group(1), \"｜ 月 →\", m.group(2), \"｜ 日 →\", m.group(3))\n    print(\"命名分组写法 →\", re.search(r\"(?P<y>\\d{4})\", \"2026\").group(\"y\"))\nprint(\"没找到时 →\", re.search(r\"zzz\", \"abc\"))",
  "where": "解析日期、版本号、URL 参数",
  "gotcha": "`re.search` 找不到时返回 **None**，直接 `.group()` 会 `AttributeError` —— 先 `if m:`",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "整段 → 2026-09-24\n年 → 2026 ｜ 月 → 09 ｜ 日 → 24\n命名分组写法 → 2026\n没找到时 → None",
  "ok": true
 },
 {
  "id": "py.re_sub",
  "lang": "py",
  "cat": "标准库",
  "stage": "本月",
  "name": "re.sub",
  "brief": "按模式替换（清洗文本的主力）",
  "code": "import re\ns = \"价格：￥1,299.00 元  （含税）\"\nprint(re.sub(r\"[￥,]\", \"\", s))\nprint(re.sub(r\"\\s+\", \" \", s).strip())\nprint(re.sub(r\"(\\d+)\\.(\\d+)\", r\"\\2.\\1\", \"3.14\"))     # 分组反向引用",
  "where": "清洗爬下来的文本 / 归一化输入",
  "gotcha": "`re.sub` 默认**替换所有**匹配；只想换第一个要加 `count=1`",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "价格：1299.00 元  （含税）\n价格：￥1,299.00 元 （含税）\n14.3",
  "ok": true
 },
 {
  "id": "py.datetime_now",
  "lang": "py",
  "cat": "标准库",
  "stage": "本月",
  "name": "datetime.now() / strftime",
  "brief": "取当前时间，格式化成字符串",
  "code": "from datetime import datetime\nnow = datetime.now()\nprint(\"原样 →\", now)\nprint(\"常用 →\", now.strftime(\"%Y-%m-%d %H:%M:%S\"))\nprint(\"文件名用 →\", now.strftime(\"%Y%m%d-%H%M\"))\nprint(\"星期日历 →\", now.strftime(\"%Y-%m-%d %A\"))",
  "where": "给导出文件起名；记日志时间戳",
  "gotcha": "Windows 上 `strftime('%Y-%m-%d')` 没问题，但**文件名里不能有 `:`** —— `%H:%M` 直接拿去当文件名会失败",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "原样 → 2026-09-24 00:31:57.566138\n常用 → 2026-09-24 00:31:57\n文件名用 → 20260924-0031\n星期日历 → 2026-09-24 Thursday",
  "ok": true
 },
 {
  "id": "py.datetime_strptime",
  "lang": "py",
  "cat": "标准库",
  "stage": "本月",
  "name": "strptime：字符串 → 时间",
  "brief": "把文本日期变成能计算的对象（转回来才能减）",
  "code": "from datetime import datetime\nd = datetime.strptime(\"2026-09-21\", \"%Y-%m-%d\")\nprint(\"解析 →\", d, type(d).__name__)\nprint(\"换一种格式 →\", d.strftime(\"%Y年%m月%d日\"))\ntry:\n    datetime.strptime(\"2026/09/21\", \"%Y-%m-%d\")\nexcept ValueError as e:\n    print(\"格式对不上 →\", e)",
  "where": "算复习到期日 / 算实习倒计时",
  "gotcha": "格式串必须和输入**严格一致**（`2026/09/21` 配 `%Y-%m-%d` 会报 `does not match format`）",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "解析 → 2026-09-21 00:00:00 datetime\n换一种格式 → 2026年09月21日\n格式对不上 → time data '2026/09/21' does not match format '%Y-%m-%d'",
  "ok": true
 },
 {
  "id": "py.timedelta",
  "lang": "py",
  "cat": "标准库",
  "stage": "本月",
  "name": "timedelta：日期加减",
  "brief": "算差几天、N 天后是哪天",
  "code": "from datetime import date, timedelta\nanchor = date(2026, 9, 23)                  # 你的倒推起点\nfor n in (1, 3, 7, 30):\n    print(f\"第 {n:>2} 天 →\", anchor + timedelta(days=n))\ngap = date(2027, 3, 1) - anchor\nprint(\"到 2027.03 还有\", gap.days, \"天 ≈\", gap.days // 7, \"周\")",
  "where": "1-3-7-30 复习日程；倒推链",
  "gotcha": "`date - date` 得到 `timedelta`，取天数用 `.days`；`//7` 是**向下取整**的周数（不是四舍五入）",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "第  1 天 → 2026-09-24\n第  3 天 → 2026-09-26\n第  7 天 → 2026-09-30\n第 30 天 → 2026-10-23\n到 2027.03 还有 159 天 ≈ 22 周",
  "ok": true
 },
 {
  "id": "py.counter",
  "lang": "py",
  "cat": "标准库",
  "stage": "以后",
  "name": "collections.Counter",
  "brief": "数词频，一行搞定（比手写字典 +1 干净）",
  "code": "from collections import Counter\nwords = \"数据 数据库 数据 模型 数据库 数据\".split()\nc = Counter(words)\nprint(c)\nprint(\"前三 →\", c.most_common(3))\nprint(\"'数据' 出现 →\", c[\"数据\"], \"次\")\nprint(\"没出现过的词 →\", c[\"不存在\"], \"次（不报错，返回 0）\")",
  "where": "统计标签分布 / 看数据里哪类最多",
  "gotcha": "取不存在的键返回 **0 而不是 KeyError** —— 好处是省事，坏处是拼错词也照样得 0，不报错",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "Counter({'数据': 3, '数据库': 2, '模型': 1})\n前三 → [('数据', 3), ('数据库', 2), ('模型', 1)]\n'数据' 出现 → 3 次\n没出现过的词 → 0 次（不报错，返回 0）",
  "ok": true
 },
 {
  "id": "py.defaultdict",
  "lang": "py",
  "cat": "标准库",
  "stage": "以后",
  "name": "defaultdict(list)：分组",
  "brief": "按 key 把东西塞进不同的桶，不用先判断 key 在不在",
  "code": "from collections import defaultdict\nrows = [(\"讯飞班\", \"韩立\"), (\"计科1班\", \"小红\"), (\"讯飞班\", \"小明\")]\ng = defaultdict(list)\nfor cls, name in rows:\n    g[cls].append(name)\nprint(dict(g))\nprint(\"不存在的班 →\", g[\"不存在\"], \"（自动建了空 list）\")",
  "where": "把一堆 (分类, 内容) 聚成 {分类: [内容]}",
  "gotcha": "读一个不存在的 key 会**顺手创建它** —— 遍历时边读边写会报 `dictionary changed size during iteration`",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "{'讯飞班': ['韩立', '小明'], '计科1班': ['小红']}\n不存在的班 → [] （自动建了空 list）",
  "ok": true
 },
 {
  "id": "py.random",
  "lang": "py",
  "cat": "标准库",
  "stage": "以后",
  "name": "random.choice / sample / randint",
  "brief": "抽一个、抽几个不重复的、抽一个整数",
  "code": "import random\nrandom.seed(42)                             # 固定种子 → 结果可复现\nprint(\"抽一个 →\", random.choice([\"A\", \"B\", \"C\"]))\nprint(\"抽2个不重复 →\", random.sample(range(1, 50), 2))\nprint(\"1~6 的整数 →\", random.randint(1, 6))\nrandom.shuffle(lst := [1, 2, 3, 4])\nprint(\"打乱 →\", lst)",
  "where": "造测试数据 / 切分训练集",
  "gotcha": "`random.seed(42)` 是**可复现**的关键 —— 不设种子，同样的代码每次都出不同结果，bug 就复现不了",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "抽一个 → C\n抽2个不重复 → [8, 2]\n1~6 的整数 → 6\n打乱 → [2, 4, 1, 3]",
  "ok": true
 },
 {
  "id": "py.requests_sig",
  "lang": "py",
  "cat": "第三方",
  "stage": "以后",
  "name": "requests.get（只看签名）",
  "brief": "HTTP 请求最常用的库。这条**只实测了签名**，没联网",
  "code": "import inspect, requests\nprint(\"requests\", requests.__version__)\nprint(\"get\", inspect.signature(requests.get))\nprint(\"post 有 params/data/json →\",\n      all(k in inspect.signature(requests.post).parameters for k in (\"params\", \"data\", \"json\")))",
  "where": "之后调接口 / 爬虫 / 调大模型 API",
  "gotcha": "⚠️ 这段**没有真的发请求**（不允许联网实测）。用法要点：`resp.status_code` 判断成败、`resp.json()` 取 JSON、`resp.text` 取原文、`timeout=` 一定要给（不给会永久挂住）",
  "verify": null,
  "err": false,
  "extra": "[外源] 未联网验证",
  "out": "requests 2.32.5\nget (url, params=None, **kwargs)\npost 有 params/data/json → False",
  "ok": true
 },
 {
  "id": "py.pandas_sig",
  "lang": "py",
  "cat": "第三方",
  "stage": "以后",
  "name": "pandas.read_csv（只看签名）",
  "brief": "读表格数据的事实标准。同样**只实测了签名**",
  "code": "import inspect, pandas as pd\nprint(\"pandas\", pd.__version__)\nprint(\"read_csv\", inspect.signature(pd.read_csv))\ndf = pd.DataFrame({\"a\": [1, 2], \"b\": [\"x\", \"y\"]})\nprint(df.to_string(index=False))",
  "where": "之后做数据分析 / 处理表格数据",
  "gotcha": "⚠️ 只验证了 DataFrame 构造，**没有真读 csv 文件**。要点：`encoding='utf-8'`（中文 csv 常是 `gbk`）、`dtype=` 防手机号被当数字",
  "verify": null,
  "err": false,
  "extra": "[外源] 未读实际文件",
  "out": "pandas 2.3.3\nread_csv (filepath_or_buffer: 'FilePath | ReadCsvBuffer[bytes] | ReadCsvBuffer[str]', *, sep: 'str | None | lib.NoDefault' = <no_default>, delimiter: 'str | None | lib.NoDefault' = None, header: \"int | Sequence[int] | None | Literal['infer']\" = 'infer', names: 'Sequence[Hashable] | None | lib.NoDefault' = <no_default>, index_col: 'IndexLabel | Literal[False] | None' = None, usecols: 'UsecolsArgType' = None, dtype: 'DtypeArg | None' = None, engine: 'CSVEngine | None' = None, converters: 'Mapping[Hashable, Callable] | None' = None, true_values: 'list | None' = None, false_values: 'list | None' = None, skipinitialspace: 'bool' = False, skiprows: 'list[int] | int | Callable[[Hashable], bool] | None' = None, skipfooter: 'int' = 0, nrows: 'int | None' = None, na_values: 'Hashable | Iterable[Hashable] | Mapping[Hashable, Iterable[Hashable]] | None' = None, keep_default_na: 'bool' = True, na_filter: 'bool' = True, verbose: 'bool | lib.NoDefault' = <no_default>, skip_blank_lines: 'bool' = True, parse_dates: 'bool | Sequence[Hashable] | None' = None, infer_datetime_format: 'bool | lib.NoDefault' = <no_default>, keep_date_col: 'bool | lib.NoDefault' = <no_default>, date_parser: 'Callable | lib.NoDefault' = <no_default>, date_format: 'str | dict[Hashable, str] | None' = None, dayfirst: 'bool' = False, cache_dates: 'bool' = True, iterator: 'bool' = False, chunksize: 'int | None' = None, compression: 'CompressionOptions' = 'infer', thousands: 'str | None' = None, decimal: 'str' = '.', lineterminator: 'str | None' = None, quotechar: 'str' = '\"', quoting: 'int' = 0, doublequote: 'bool' = True, escapechar: 'str | None' = None, comment: 'str | None' = None, encoding: 'str | None' = None, encoding_errors: 'str | None' = 'strict', dialect: 'str | csv.Dialect | None' = None, on_bad_lines: 'str' = 'error', delim_whitespace: 'bool | lib.NoDefault' = <no_default>, low_memory: 'bool' = True, memory_map: 'bool' = False, float_precision: \"Literal['high', 'legacy'] | None\" = None, storage_options: 'StorageOptions | None' = None, dtype_backend: 'DtypeBackend | lib.NoDefault' = <no_default>) -> 'DataFrame | TextFileReader'\n a b\n 1 x\n 2 y",
  "ok": true
 },
 {
  "id": "bi.len_range",
  "lang": "py",
  "cat": "内置",
  "stage": "以后",
  "name": "len / range",
  "brief": "len 数长度；range 造一串数字（Python 里**从 0 开始、不含结尾**）",
  "code": "s = \"数据库\"\nprint(\"len →\", len(s), \"｜ range(3) →\", list(range(3)), \"｜ range(1,4) →\", list(range(1, 4)))\nprint(\"倒着数 →\", list(range(3, 0, -1)))\nfor i in range(len(s)):\n    print(i, s[i])",
  "where": "到处都在用",
  "gotcha": "`range(1, 5)` 是 1,2,3,4（**没有 5**）—— 差一个数的 bug 八成来自这里",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "len → 3 ｜ range(3) → [0, 1, 2] ｜ range(1,4) → [1, 2, 3]\n倒着数 → [3, 2, 1]\n0 数\n1 据\n2 库",
  "ok": true
 },
 {
  "id": "bi.enumerate",
  "lang": "py",
  "cat": "内置",
  "stage": "以后",
  "name": "enumerate",
  "brief": "边遍历边拿到序号，别自己维护计数器",
  "code": "for i, name in enumerate([\"小明\", \"小红\"], start=1):\n    print(i, name)\nprint(\"不加 start →\", list(enumerate(\"ab\")))",
  "where": "要「第几条」的时候",
  "gotcha": "`enumerate(x, start=1)` 才是从 1 开始；默认从 **0** 开始",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "1 小明\n2 小红\n不加 start → [(0, 'a'), (1, 'b')]",
  "ok": true
 },
 {
  "id": "bi.zip",
  "lang": "py",
  "cat": "内置",
  "stage": "以后",
  "name": "zip",
  "brief": "把两个列表按位置配对，一次遍历两个",
  "code": "names = [\"小明\", \"小红\", \"小刚\"]\nscores = [88, 92, 76]\nfor n, s in zip(names, scores):\n    print(n, s)\nprint(\"配对成字典 →\", dict(zip(names, scores)))\nprint(\"长度不等时 →\", list(zip([1, 2, 3], \"ab\")))",
  "where": "两个来源的数据要一起处理",
  "gotcha": "长度不等时**按短的截断，不报错** —— 数据对不齐时会静默丢数据（Python 3.10+ 可用 `strict=True` 让它报错）",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "小明 88\n小红 92\n小刚 76\n配对成字典 → {'小明': 88, '小红': 92, '小刚': 76}\n长度不等时 → [(1, 'a'), (2, 'b')]",
  "ok": true
 },
 {
  "id": "bi.sorted_key",
  "lang": "py",
  "cat": "内置",
  "stage": "本月",
  "name": "sorted(key=…)",
  "brief": "排序的万能钥匙：`key` 决定「按什么排」",
  "code": "rows = [(\"小明\", 88.5), (\"小红\", 92.0), (\"小刚\", 76.5)]\nprint(\"按分数 →\", sorted(rows, key=lambda r: r[1], reverse=True))\nd = {\"b\": 2, \"a\": 3, \"c\": 1}\nprint(\"字典按值排 →\", sorted(d.items(), key=lambda kv: kv[1]))\nprint(\"多级排序 →\", sorted(rows, key=lambda r: (-r[1], r[0])))",
  "where": "排行榜 / 按时间排日志 / 结果稳定输出",
  "gotcha": "`key=` 收到的是**函数**，写 `key=r[1]` 会直接报错；`list.sort()` 是原地改，`sorted()` 返回新列表",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "按分数 → [('小红', 92.0), ('小明', 88.5), ('小刚', 76.5)]\n字典按值排 → [('c', 1), ('b', 2), ('a', 3)]\n多级排序 → [('小红', 92.0), ('小明', 88.5), ('小刚', 76.5)]",
  "ok": true
 },
 {
  "id": "bi.sum_min_max",
  "lang": "py",
  "cat": "内置",
  "stage": "以后",
  "name": "sum / min / max",
  "brief": "三个聚合内置，都能配 `key=` 和默认值",
  "code": "nums = [3, 1, 4, 1, 5]\nprint(\"sum →\", sum(nums), \"｜ min →\", min(nums), \"｜ max →\", max(nums))\nprint(\"带初值 →\", sum(nums, 100))\nprint(\"空列表 →\", sum([]), end=\" / \")\ntry:\n    min([])\nexcept ValueError as e:\n    print(\"min 报错：\", e)\nprint(\"按 key 取最大 →\", max([\"aa\", \"bbb\", \"c\"], key=len))",
  "where": "算总分、找最长的那条",
  "gotcha": "`sum([])` 是 0，但 **`min([])` / `max([])` 会报 ValueError** —— 空列表要先用 `default=`（3.4+）或自己判断",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "sum → 14 ｜ min → 1 ｜ max → 5\n带初值 → 114\n空列表 → 0 / min 报错： min() iterable argument is empty\n按 key 取最大 → bbb",
  "ok": true
 },
 {
  "id": "bi.any_all",
  "lang": "py",
  "cat": "内置",
  "stage": "以后",
  "name": "any / all",
  "brief": "一串条件里「有没有一个真的」 / 「是不是全都真」",
  "code": "nums = [2, 4, 6, 8]\nprint(\"全是偶数 →\", all(n % 2 == 0 for n in nums))\nprint(\"有大于 5 的 →\", any(n > 5 for n in nums))\nprint(\"空列表的默认 →\", any([]), all([]))",
  "where": "批量校验（检查所有字段都非空）",
  "gotcha": "空列表时 `all([])` 是 **True**（「全都满足」在逻辑上成立）—— 拿它当「数据没问题」的判断会漏掉空数据的情况",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "全是偶数 → True\n有大于 5 的 → True\n空列表的默认 → False True",
  "ok": true
 },
 {
  "id": "bi.type_cast",
  "lang": "py",
  "cat": "内置",
  "stage": "本月",
  "name": "int / float / str 类型转换",
  "brief": "输入永远是字符串，要算就得先转",
  "code": "print(int(\"42\") + 1, float(\"3.5\") * 2, str(42) + \"!\")\nprint(\"取整 →\", int(3.9), \"（截断不是四舍五入）｜ round →\", round(3.9))\nprint(\"转不了会炸 →\", end=\" \")\ntry:\n    int(\"abc\")\nexcept ValueError as e:\n    print(\"ValueError:\", e)",
  "where": "读用户输入、读文件里的数字",
  "gotcha": "`int(3.9)` 是 **3**（截断）；要四舍五入用 `round()`。`int('3.5')` 也会报错，得先 `float()`",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "43 7.0 42!\n取整 → 3 （截断不是四舍五入）｜ round → 4\n转不了会炸 → ValueError: invalid literal for int() with base 10: 'abc'",
  "ok": true
 },
 {
  "id": "bi.fstring",
  "lang": "py",
  "cat": "内置",
  "stage": "本月",
  "name": "f-string 格式化",
  "brief": "在字符串里直接写变量，还能控制小数位和对齐",
  "code": "name, score = \"韩立\", 88.4567\nprint(f\"{name} 的分数是 {score}\")\nprint(f\"保留两位 → {score:.2f}\")\nprint(f\"百分比   → {score / 100:.1%}\")\nprint(f\"右对齐   → |{name:>8}|｜左对齐 → |{name:<8}|｜补零 → {7:03d}\")",
  "where": "拼日志、拼输出的每一处",
  "gotcha": "f-string 只在字符串**前面有 f** 时生效；`\\n` 在 f-string 里是换行，但**表达式里不能有反斜杠**（3.12 前）",
  "verify": null,
  "err": false,
  "extra": "",
  "out": "韩立 的分数是 88.4567\n保留两位 → 88.46\n百分比   → 88.5%\n右对齐   → |      韩立|｜左对齐 → |韩立      |｜补零 → 007",
  "ok": true
 }
];
